/* Generated by gbrecomp from Lufia - The Legend Returns (USA) */
#include "Lufia___The_Legend_Returns__USA__internal.h"

/* Shared body at 75:489b */
static void body_75_489b(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x489b: goto loc_75_489b;
        case 0x489c: goto pc_489c;
        case 0x489d: goto pc_489d;
        case 0x489e: goto pc_489e;
        case 0x48a0: goto pc_48a0;
        case 0x48a1: goto pc_48a1;
        case 0x48a2: goto pc_48a2;
        case 0x48a3: goto loc_75_48a3;
        case 0x48a4: goto pc_48a4;
        case 0x48a7: goto pc_48a7;
        case 0x48a8: goto pc_48a8;
        case 0x48a9: goto pc_48a9;
        case 0x48aa: goto loc_75_48aa;
        case 0x48ab: goto pc_48ab;
        case 0x48ac: goto pc_48ac;
        case 0x48ad: goto pc_48ad;
        case 0x48ae: goto loc_75_48ae;
        case 0x48af: goto pc_48af;
        case 0x48b2: goto pc_48b2;
        case 0x48b3: goto pc_48b3;
        case 0x48b4: goto pc_48b4;
        case 0x48b5: goto pc_48b5;
        case 0x48b6: goto pc_48b6;
        case 0x48b7: goto pc_48b7;
        case 0x48b8: goto pc_48b8;
        case 0x48b9: goto loc_75_48b9;
        case 0x48bb: goto pc_48bb;
        case 0x48bc: goto pc_48bc;
        case 0x48bd: goto pc_48bd;
        case 0x48be: goto pc_48be;
        case 0x48bf: goto pc_48bf;
        case 0x48c0: goto pc_48c0;
        case 0x48c1: goto pc_48c1;
        case 0x48c3: goto pc_48c3;
        case 0x48c4: goto pc_48c4;
        case 0x48c5: goto pc_48c5;
        case 0x48c8: goto pc_48c8;
        case 0x48ca: goto pc_48ca;
        case 0x48cb: goto pc_48cb;
        case 0x48cc: goto pc_48cc;
        case 0x48cf: goto pc_48cf;
        case 0x48d1: goto pc_48d1;
        case 0x48d2: goto pc_48d2;
        case 0x48d3: goto pc_48d3;
        case 0x48d4: goto pc_48d4;
        case 0x48d5: goto pc_48d5;
        case 0x48d8: goto pc_48d8;
        case 0x48d9: goto pc_48d9;
        case 0x48da: goto pc_48da;
        case 0x48db: goto pc_48db;
        case 0x48dc: goto pc_48dc;
        case 0x48df: goto pc_48df;
        case 0x48e0: goto pc_48e0;
        case 0x48e1: goto pc_48e1;
        case 0x48e2: goto pc_48e2;
        case 0x48e3: goto pc_48e3;
        case 0x48e6: goto pc_48e6;
        case 0x48e7: goto pc_48e7;
        case 0x48e8: goto pc_48e8;
        case 0x48e9: goto pc_48e9;
        case 0x48ea: goto pc_48ea;
        case 0x48ed: goto pc_48ed;
        case 0x48ee: goto pc_48ee;
        case 0x48ef: goto pc_48ef;
        case 0x48f0: goto pc_48f0;
        case 0x48f1: goto pc_48f1;
        case 0x48f4: goto pc_48f4;
        case 0x48f5: goto pc_48f5;
        case 0x48f6: goto pc_48f6;
        case 0x48f7: goto pc_48f7;
        case 0x48f8: goto pc_48f8;
        case 0x48fb: goto pc_48fb;
        case 0x48fc: goto pc_48fc;
        case 0x48fd: goto pc_48fd;
        case 0x48ff: goto pc_48ff;
        case 0x4900: goto pc_4900;
        case 0x4901: goto pc_4901;
        case 0x4902: goto pc_4902;
        case 0x4905: goto pc_4905;
        case 0x4906: goto pc_4906;
        case 0x4907: goto pc_4907;
        default: break;
    }

loc_75_489b:
    /* LD L,H */
    /* 75:489b */     ctx->l = ctx->h;
    ctx->pc = 0x489c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_489c:
    /* 75:489c */     ctx->d = ctx->b;
    ctx->pc = 0x489d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_489d:
    /* 75:489d */     /* NOP */
    ctx->pc = 0x489e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $6c */
pc_489e:
    /* 75:489e */     gb_cp8(ctx, 0x6c);
    ctx->pc = 0x48a0;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,E */
pc_48a0:
    /* 75:48a0 */     ctx->d = ctx->e;
    ctx->pc = 0x48a1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_48a1:
    /* 75:48a1 */     /* NOP */
    ctx->pc = 0x48a2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_48a2:
    /* 75:48a2 */     gbrt_timed_rst(ctx, 0x38, 0x48a3);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_75_48a3:
    /* SCF */
    /* 75:48a3 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x48a4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_48a4:
    /* 75:48a4 */     ctx->bc = 0x6cce;
    ctx->pc = 0x48a7;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_48a7:
    /* 75:48a7 */     ctx->d = ctx->b;
    ctx->pc = 0x48a8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_48a8:
    /* 75:48a8 */     /* NOP */
    ctx->pc = 0x48a9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_48a9:
    /* 75:48a9 */     gbrt_timed_rst(ctx, 0x38, 0x48aa);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_75_48aa:
    /* LD L,H */
    /* 75:48aa */     ctx->l = ctx->h;
    ctx->pc = 0x48ab;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,E */
pc_48ab:
    /* 75:48ab */     ctx->d = ctx->e;
    ctx->pc = 0x48ac;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_48ac:
    /* 75:48ac */     /* NOP */
    ctx->pc = 0x48ad;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_48ad:
    /* 75:48ad */     gbrt_timed_rst(ctx, 0x38, 0x48ae);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_75_48ae:
    /* SCF */
    /* 75:48ae */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x48af;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_48af:
    /* 75:48af */     ctx->bc = 0x6cce;
    ctx->pc = 0x48b2;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_48b2:
    /* 75:48b2 */     ctx->d = ctx->b;
    ctx->pc = 0x48b3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_48b3:
    /* 75:48b3 */     /* NOP */
    ctx->pc = 0x48b4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_48b4:
    /* 75:48b4 */     /* NOP */
    ctx->pc = 0x48b5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_48b5:
    /* 75:48b5 */     ctx->l = ctx->h;
    ctx->pc = 0x48b6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,E */
pc_48b6:
    /* 75:48b6 */     ctx->d = ctx->e;
    ctx->pc = 0x48b7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_48b7:
    /* 75:48b7 */     /* NOP */
    ctx->pc = 0x48b8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_48b8:
    /* 75:48b8 */     gbrt_timed_rst(ctx, 0x38, 0x48b9);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_75_48b9:
    /* LD L,$53 */
    /* 75:48b9 */     ctx->l = 0x53;
    ctx->pc = 0x48bb;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_48bb:
    /* 75:48bb */     ctx->l = ctx->h;
    ctx->pc = 0x48bc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_48bc:
    /* 75:48bc */     ctx->d = ctx->b;
    ctx->pc = 0x48bd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_48bd:
    /* 75:48bd */     /* NOP */
    ctx->pc = 0x48be;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_48be:
    /* 75:48be */     /* NOP */
    ctx->pc = 0x48bf;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_48bf:
    /* 75:48bf */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x48c0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_48c0:
    /* 75:48c0 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x48c1;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,$6c */
pc_48c1:
    /* 75:48c1 */     gb_adc8(ctx, 0x6c);
    ctx->pc = 0x48c3;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_48c3:
    /* 75:48c3 */     ctx->d = ctx->b;
    ctx->pc = 0x48c4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_48c4:
    /* 75:48c4 */     /* NOP */
    ctx->pc = 0x48c5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0137 */
pc_48c5:
    /* 75:48c5 */     ctx->bc = 0x0137;
    ctx->pc = 0x48c8;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,$6c */
pc_48c8:
    /* 75:48c8 */     gb_adc8(ctx, 0x6c);
    ctx->pc = 0x48ca;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_48ca:
    /* 75:48ca */     ctx->d = ctx->b;
    ctx->pc = 0x48cb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_48cb:
    /* 75:48cb */     /* NOP */
    ctx->pc = 0x48cc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0137 */
pc_48cc:
    /* 75:48cc */     ctx->bc = 0x0137;
    ctx->pc = 0x48cf;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,$6c */
pc_48cf:
    /* 75:48cf */     gb_adc8(ctx, 0x6c);
    ctx->pc = 0x48d1;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_48d1:
    /* 75:48d1 */     ctx->d = ctx->b;
    ctx->pc = 0x48d2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_48d2:
    /* 75:48d2 */     /* NOP */
    ctx->pc = 0x48d3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_48d3:
    /* 75:48d3 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x48d4;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_48d4:
    /* 75:48d4 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x48d5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_48d5:
    /* 75:48d5 */     ctx->bc = 0x6cce;
    ctx->pc = 0x48d8;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_48d8:
    /* 75:48d8 */     ctx->d = ctx->b;
    ctx->pc = 0x48d9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_48d9:
    /* 75:48d9 */     /* NOP */
    ctx->pc = 0x48da;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_48da:
    /* 75:48da */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x48db;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_48db:
    /* 75:48db */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x48dc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_48dc:
    /* 75:48dc */     ctx->bc = 0x6cce;
    ctx->pc = 0x48df;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_48df:
    /* 75:48df */     ctx->d = ctx->b;
    ctx->pc = 0x48e0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_48e0:
    /* 75:48e0 */     /* NOP */
    ctx->pc = 0x48e1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_48e1:
    /* 75:48e1 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x48e2;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_48e2:
    /* 75:48e2 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x48e3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_48e3:
    /* 75:48e3 */     ctx->bc = 0x6cce;
    ctx->pc = 0x48e6;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_48e6:
    /* 75:48e6 */     ctx->d = ctx->b;
    ctx->pc = 0x48e7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_48e7:
    /* 75:48e7 */     /* NOP */
    ctx->pc = 0x48e8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_48e8:
    /* 75:48e8 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x48e9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_48e9:
    /* 75:48e9 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x48ea;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_48ea:
    /* 75:48ea */     ctx->bc = 0x6cce;
    ctx->pc = 0x48ed;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_48ed:
    /* 75:48ed */     ctx->d = ctx->b;
    ctx->pc = 0x48ee;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_48ee:
    /* 75:48ee */     /* NOP */
    ctx->pc = 0x48ef;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_48ef:
    /* 75:48ef */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x48f0;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_48f0:
    /* 75:48f0 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x48f1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_48f1:
    /* 75:48f1 */     ctx->bc = 0x6cce;
    ctx->pc = 0x48f4;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_48f4:
    /* 75:48f4 */     ctx->d = ctx->b;
    ctx->pc = 0x48f5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_48f5:
    /* 75:48f5 */     /* NOP */
    ctx->pc = 0x48f6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_48f6:
    /* 75:48f6 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x48f7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_48f7:
    /* 75:48f7 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x48f8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$2ece */
pc_48f8:
    /* 75:48f8 */     ctx->bc = 0x2ece;
    ctx->pc = 0x48fb;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_48fb:
    /* 75:48fb */     ctx->d = ctx->b;
    ctx->pc = 0x48fc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_48fc:
    /* 75:48fc */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x48fd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,$ce */
pc_48fd:
    /* 75:48fd */     ctx->e = 0xce;
    ctx->pc = 0x48ff;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CPL */
pc_48ff:
    /* 75:48ff */     ctx->a = ~ctx->a; ctx->f_n = 1; ctx->f_h = 1;
    ctx->pc = 0x4900;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_4900:
    /* 75:4900 */     ctx->d = ctx->b;
    ctx->pc = 0x4901;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,BC */
pc_4901:
    /* 75:4901 */     gb_add16(ctx, ctx->bc);
    ctx->pc = 0x4902;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$502d */
pc_4902:
    /* 75:4902 */     ctx->bc = 0x502d;
    ctx->pc = 0x4905;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_4905:
    /* 75:4905 */     ctx->l = ctx->h;
    ctx->pc = 0x4906;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_4906:
    /* 75:4906 */     ctx->d = ctx->b;
    ctx->pc = 0x4907;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4907:
    /* 75:4907 */     /* NOP */
    ctx->pc = 0x4908;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x4908 in bank 117 */
    return;
}

void func_75_489b(GBContext* ctx) {
    body_75_489b(ctx);
}

/* Shared body at 75:4956 */
static void body_75_4956(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4956: goto loc_75_4956;
        case 0x4957: goto pc_4957;
        case 0x4959: goto pc_4959;
        case 0x495c: goto loc_75_495c;
        case 0x495d: goto pc_495d;
        case 0x495e: goto pc_495e;
        case 0x495f: goto pc_495f;
        case 0x4960: goto pc_4960;
        case 0x4961: goto pc_4961;
        case 0x4962: goto pc_4962;
        case 0x4963: goto pc_4963;
        case 0x4964: goto pc_4964;
        case 0x4965: goto pc_4965;
        case 0x4966: goto pc_4966;
        case 0x4967: goto pc_4967;
        case 0x4968: goto pc_4968;
        case 0x4969: goto pc_4969;
        case 0x496a: goto pc_496a;
        case 0x496b: goto pc_496b;
        case 0x496c: goto pc_496c;
        case 0x496d: goto pc_496d;
        case 0x496e: goto pc_496e;
        case 0x496f: goto pc_496f;
        case 0x4970: goto pc_4970;
        case 0x4971: goto pc_4971;
        case 0x4972: goto pc_4972;
        case 0x4973: goto pc_4973;
        case 0x4974: goto pc_4974;
        case 0x4975: goto pc_4975;
        case 0x4978: goto pc_4978;
        case 0x4979: goto pc_4979;
        case 0x497c: goto pc_497c;
        case 0x497d: goto pc_497d;
        case 0x497e: goto pc_497e;
        case 0x4980: goto loc_75_4980;
        case 0x4981: goto pc_4981;
        case 0x4982: goto loc_75_4982;
        case 0x4985: goto pc_4985;
        case 0x4988: goto pc_4988;
        case 0x498b: goto pc_498b;
        case 0x498e: goto pc_498e;
        case 0x4991: goto loc_75_4991;
        case 0x4992: goto pc_4992;
        case 0x4995: goto pc_4995;
        case 0x4996: goto pc_4996;
        case 0x4997: goto pc_4997;
        case 0x4999: goto pc_4999;
        case 0x499c: goto pc_499c;
        case 0x499d: goto pc_499d;
        case 0x499e: goto pc_499e;
        case 0x49a1: goto pc_49a1;
        case 0x49a2: goto pc_49a2;
        case 0x49a3: goto pc_49a3;
        case 0x49a5: goto pc_49a5;
        case 0x49a7: goto pc_49a7;
        case 0x49aa: goto pc_49aa;
        case 0x49ad: goto pc_49ad;
        case 0x49b0: goto pc_49b0;
        case 0x49b3: goto loc_75_49b3;
        case 0x49b6: goto pc_49b6;
        case 0x49b7: goto pc_49b7;
        case 0x49ba: goto pc_49ba;
        case 0x49bb: goto pc_49bb;
        case 0x49bc: goto loc_75_49bc;
        case 0x49bf: goto pc_49bf;
        case 0x49c0: goto pc_49c0;
        case 0x49c3: goto pc_49c3;
        case 0x49c4: goto pc_49c4;
        case 0x49c7: goto pc_49c7;
        case 0x49c8: goto pc_49c8;
        case 0x49c9: goto pc_49c9;
        case 0x49ca: goto pc_49ca;
        default: break;
    }

loc_75_4956:
    /* SCF */
    /* 75:4956 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x4957;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,$ce */
pc_4957:
    /* 75:4957 */     ctx->e = 0xce;
    ctx->pc = 0x4959;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL NZ,$0709 */
pc_4959:
    /* 75:4959 */     if (!ctx->f_z) {
        gbrt_timed_call(ctx, 0x709, 0x495c);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        func_0709(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x495c, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_75_495c:
    /* LD (BC),A */
    /* 75:495c */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x495d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CPL */
pc_495d:
    /* 75:495d */     ctx->a = ~ctx->a; ctx->f_n = 1; ctx->f_h = 1;
    ctx->pc = 0x495e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,E */
pc_495e:
    /* 75:495e */     ctx->d = ctx->e;
    ctx->pc = 0x495f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC BC */
pc_495f:
    /* 75:495f */     gbrt_timed_dec16(ctx, &ctx->bc);
    ctx->pc = 0x4960;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,BC */
pc_4960:
    /* 75:4960 */     gb_add16(ctx, ctx->bc);
    ctx->pc = 0x4961;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC L */
pc_4961:
    /* 75:4961 */     ctx->l = gb_dec8(ctx, ctx->l);
    ctx->pc = 0x4962;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,E */
pc_4962:
    /* 75:4962 */     ctx->d = ctx->e;
    ctx->pc = 0x4963;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CPL */
pc_4963:
    /* 75:4963 */     ctx->a = ~ctx->a; ctx->f_n = 1; ctx->f_h = 1;
    ctx->pc = 0x4964;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_4964:
    /* 75:4964 */     ctx->d = ctx->b;
    ctx->pc = 0x4965;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC BC */
pc_4965:
    /* 75:4965 */     gbrt_timed_dec16(ctx, &ctx->bc);
    ctx->pc = 0x4966;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_4966:
    /* 75:4966 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4967;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC L */
pc_4967:
    /* 75:4967 */     ctx->l = gb_dec8(ctx, ctx->l);
    ctx->pc = 0x4968;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_4968:
    /* 75:4968 */     ctx->d = ctx->b;
    ctx->pc = 0x4969;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC E */
pc_4969:
    /* 75:4969 */     ctx->e = gb_dec8(ctx, ctx->e);
    ctx->pc = 0x496a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_496a:
    /* 75:496a */     /* NOP */
    ctx->pc = 0x496b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC E */
pc_496b:
    /* 75:496b */     ctx->e = gb_inc8(ctx, ctx->e);
    ctx->pc = 0x496c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC E */
pc_496c:
    /* 75:496c */     ctx->e = gb_inc8(ctx, ctx->e);
    ctx->pc = 0x496d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC SP */
pc_496d:
    /* 75:496d */     gbrt_timed_inc16(ctx, &ctx->sp);
    ctx->pc = 0x496e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RLA */
pc_496e:
    /* 75:496e */     gb_rla(ctx);
    ctx->pc = 0x496f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_496f:
    /* 75:496f */     /* NOP */
    ctx->pc = 0x4970;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_4970:
    /* 75:4970 */     ctx->l = ctx->h;
    ctx->pc = 0x4971;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_4971:
    /* 75:4971 */     ctx->d = ctx->b;
    ctx->pc = 0x4972;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4972:
    /* 75:4972 */     /* NOP */
    ctx->pc = 0x4973;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_4973:
    /* 75:4973 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x4974;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_4974:
    /* 75:4974 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x4975;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$1fce */
pc_4975:
    /* 75:4975 */     ctx->bc = 0x1fce;
    ctx->pc = 0x4978;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4978:
    /* 75:4978 */     /* NOP */
    ctx->pc = 0x4979;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$1114 */
pc_4979:
    /* 75:4979 */     ctx->bc = 0x1114;
    ctx->pc = 0x497c;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_497c:
    /* 75:497c */     /* NOP */
    ctx->pc = 0x497d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_497d:
    /* 75:497d */     /* NOP */
    ctx->pc = 0x497e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,51 */
pc_497e:
    /* 75:497e */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x49b3, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x4980, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_75_4980:
    /* RLA */
    /* 75:4980 */     gb_rla(ctx);
    ctx->pc = 0x4981;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_4981:
    /* 75:4981 */     gbrt_timed_rst(ctx, 0x38, 0x4982);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_75_4982:
    /* LD SP,$0051 */
    /* 75:4982 */     ctx->sp = 0x0051;
    ctx->pc = 0x4985;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD SP,$0100 */
pc_4985:
    /* 75:4985 */     ctx->sp = 0x0100;
    ctx->pc = 0x4988;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD SP,$0101 */
pc_4988:
    /* 75:4988 */     ctx->sp = 0x0101;
    ctx->pc = 0x498b;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD SP,$0103 */
pc_498b:
    /* 75:498b */     ctx->sp = 0x0103;
    ctx->pc = 0x498e;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL NZ,$0707 */
pc_498e:
    /* 75:498e */     if (!ctx->f_z) {
        gbrt_timed_call(ctx, 0x707, 0x4991);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        func_0707(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x4991, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_75_4991:
    /* LD (BC),A */
    /* 75:4991 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4992;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD SP,$0301 */
pc_4992:
    /* 75:4992 */     ctx->sp = 0x0301;
    ctx->pc = 0x4995;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC (HL) */
pc_4995:
    /* 75:4995 */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_dec8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x4996;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_4996:
    /* 75:4996 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4997;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,$09 */
pc_4997:
    /* 75:4997 */     ctx->b = 0x09;
    ctx->pc = 0x4999;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0035 */
pc_4999:
    /* 75:4999 */     ctx->bc = 0x0035;
    ctx->pc = 0x499c;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RLCA */
pc_499c:
    /* 75:499c */     gb_rlca(ctx);
    ctx->pc = 0x499d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,BC */
pc_499d:
    /* 75:499d */     gb_add16(ctx, ctx->bc);
    ctx->pc = 0x499e;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0036 */
pc_499e:
    /* 75:499e */     ctx->bc = 0x0036;
    ctx->pc = 0x49a1;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* POP DE */
pc_49a1:
    /* 75:49a1 */     ctx->de = gbrt_timed_pop16(ctx);
    ctx->pc = 0x49a2;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,C */
pc_49a2:
    /* 75:49a2 */     ctx->d = ctx->c;
    ctx->pc = 0x49a3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,$37 */
pc_49a3:
    /* 75:49a3 */     ctx->b = 0x37;
    ctx->pc = 0x49a5;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,$ce */
pc_49a5:
    /* 75:49a5 */     ctx->e = 0xce;
    ctx->pc = 0x49a7;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD SP,$0200 */
pc_49a7:
    /* 75:49a7 */     ctx->sp = 0x0200;
    ctx->pc = 0x49aa;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD SP,$0201 */
pc_49aa:
    /* 75:49aa */     ctx->sp = 0x0201;
    ctx->pc = 0x49ad;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD SP,$0203 */
pc_49ad:
    /* 75:49ad */     ctx->sp = 0x0203;
    ctx->pc = 0x49b0;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD SP,$0250 */
pc_49b0:
    /* 75:49b0 */     ctx->sp = 0x0250;
    ctx->pc = 0x49b3;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_75_49b3:
    /* LD SP,$0151 */
    /* 75:49b3 */     ctx->sp = 0x0151;
    ctx->pc = 0x49b6;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_49b6:
    /* 75:49b6 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x49b7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$33ce */
pc_49b7:
    /* 75:49b7 */     ctx->bc = 0x33ce;
    ctx->pc = 0x49ba;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,C */
pc_49ba:
    /* 75:49ba */     ctx->d = ctx->c;
    ctx->pc = 0x49bb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_49bb:
    /* 75:49bb */     gbrt_timed_rst(ctx, 0x38, 0x49bc);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_75_49bc:
    /* LD BC,$5136 */
    /* 75:49bc */     ctx->bc = 0x5136;
    ctx->pc = 0x49bf;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_49bf:
    /* 75:49bf */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x49c0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$33ce */
pc_49c0:
    /* 75:49c0 */     ctx->bc = 0x33ce;
    ctx->pc = 0x49c3;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,C */
pc_49c3:
    /* 75:49c3 */     ctx->d = ctx->c;
    ctx->pc = 0x49c4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$3602 */
pc_49c4:
    /* 75:49c4 */     ctx->bc = 0x3602;
    ctx->pc = 0x49c7;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,C */
pc_49c7:
    /* 75:49c7 */     ctx->d = ctx->c;
    ctx->pc = 0x49c8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_49c8:
    /* 75:49c8 */     ctx->l = ctx->h;
    ctx->pc = 0x49c9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,C */
pc_49c9:
    /* 75:49c9 */     ctx->d = ctx->c;
    ctx->pc = 0x49ca;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_49ca:
    /* 75:49ca */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x49cb;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x49cb in bank 117 */
    return;
}

void func_75_4956(GBContext* ctx) {
    body_75_4956(ctx);
}

/* Shared body at 75:5536 */
static void body_75_5536(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_75_5536:
    /* JP HL */
    /* 75:5536 */     gbrt_timed_jump(ctx, ctx->hl, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
}

void func_75_5536(GBContext* ctx) {
    body_75_5536(ctx);
}

/* Shared body at 75:5656 */
static void body_75_5656(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_75_5656:
    /* RETI */
    /* 75:5656 */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x5657 in bank 117 */
    return;
}

void func_75_5656(GBContext* ctx) {
    body_75_5656(ctx);
}

