/* Generated by gbrecomp */
#ifndef Lufia___The_Legend_Returns__USA__H
#define Lufia___The_Legend_Returns__USA__H

#include "gbrt.h"

const GBConfig* Lufia___The_Legend_Returns__USA__default_config(void);
void Lufia___The_Legend_Returns__USA__run(GBContext* ctx);
void Lufia___The_Legend_Returns__USA__init(GBContext* ctx, const uint8_t* rom_data, size_t rom_size);
int Lufia___The_Legend_Returns__USA__main(int argc, char* argv[]);

#endif
