/* Generated by gbrecomp from Lufia - The Legend Returns (USA) */
#include "Lufia___The_Legend_Returns__USA__internal.h"

/* Shared body at 68:5acd */
static void body_68_5acd(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x5aae: goto loc_68_5aae;
        case 0x5ab0: goto pc_5ab0;
        case 0x5ab1: goto pc_5ab1;
        case 0x5ab4: goto pc_5ab4;
        case 0x5ab5: goto pc_5ab5;
        case 0x5ab8: goto pc_5ab8;
        case 0x5abb: goto pc_5abb;
        case 0x5abc: goto pc_5abc;
        case 0x5abe: goto pc_5abe;
        case 0x5ac1: goto pc_5ac1;
        case 0x5ac2: goto pc_5ac2;
        case 0x5acd: goto loc_68_5acd;
        case 0x5ace: goto loc_68_5ace;
        case 0x5acf: goto pc_5acf;
        case 0x5ad1: goto loc_68_5ad1;
        case 0x5ad2: goto pc_5ad2;
        case 0x5ad3: goto pc_5ad3;
        case 0x5ad4: goto pc_5ad4;
        case 0x5ad5: goto pc_5ad5;
        case 0x5ad7: goto loc_68_5ad7;
        case 0x5ad8: goto pc_5ad8;
        case 0x5ada: goto loc_68_5ada;
        case 0x5adb: goto pc_5adb;
        case 0x5adc: goto pc_5adc;
        case 0x5add: goto pc_5add;
        case 0x5ade: goto pc_5ade;
        case 0x5adf: goto pc_5adf;
        case 0x5ae1: goto loc_68_5ae1;
        case 0x5ae2: goto pc_5ae2;
        case 0x5ae3: goto pc_5ae3;
        case 0x5ae4: goto pc_5ae4;
        case 0x5ae5: goto loc_68_5ae5;
        case 0x5ae6: goto pc_5ae6;
        case 0x5ae9: goto pc_5ae9;
        case 0x5aeb: goto loc_68_5aeb;
        case 0x5aed: goto loc_68_5aed;
        case 0x5aef: goto loc_68_5aef;
        case 0x5af0: goto pc_5af0;
        case 0x5af1: goto pc_5af1;
        case 0x5af3: goto loc_68_5af3;
        case 0x5af4: goto pc_5af4;
        case 0x5af5: goto pc_5af5;
        case 0x5af6: goto pc_5af6;
        case 0x5af7: goto pc_5af7;
        case 0x5af8: goto pc_5af8;
        case 0x5af9: goto pc_5af9;
        case 0x5afb: goto pc_5afb;
        case 0x5afe: goto pc_5afe;
        case 0x5aff: goto loc_68_5aff;
        case 0x5b00: goto pc_5b00;
        case 0x5b01: goto loc_68_5b01;
        case 0x5b02: goto pc_5b02;
        case 0x5b03: goto pc_5b03;
        case 0x5b04: goto pc_5b04;
        case 0x5b07: goto loc_68_5b07;
        case 0x5b08: goto pc_5b08;
        case 0x5b0a: goto pc_5b0a;
        case 0x5b0b: goto pc_5b0b;
        case 0x5b0c: goto pc_5b0c;
        case 0x5b0d: goto pc_5b0d;
        case 0x5b0e: goto pc_5b0e;
        case 0x5b0f: goto pc_5b0f;
        case 0x5b10: goto pc_5b10;
        case 0x5b12: goto pc_5b12;
        case 0x5b13: goto loc_68_5b13;
        case 0x5b14: goto pc_5b14;
        case 0x5b15: goto pc_5b15;
        case 0x5b16: goto pc_5b16;
        case 0x5b18: goto pc_5b18;
        case 0x5b19: goto pc_5b19;
        case 0x5b1a: goto pc_5b1a;
        case 0x5b1b: goto pc_5b1b;
        case 0x5b1c: goto pc_5b1c;
        case 0x5b1d: goto pc_5b1d;
        case 0x5b1e: goto pc_5b1e;
        case 0x5b1f: goto pc_5b1f;
        case 0x5b20: goto loc_68_5b20;
        case 0x5b21: goto pc_5b21;
        case 0x5b22: goto pc_5b22;
        case 0x5b23: goto pc_5b23;
        case 0x5b24: goto pc_5b24;
        case 0x5b25: goto pc_5b25;
        case 0x5b26: goto loc_68_5b26;
        case 0x5b27: goto loc_68_5b27;
        case 0x5b28: goto loc_68_5b28;
        case 0x5b2b: goto pc_5b2b;
        case 0x5b2c: goto pc_5b2c;
        case 0x5b2d: goto pc_5b2d;
        case 0x5b2e: goto pc_5b2e;
        case 0x5b2f: goto loc_68_5b2f;
        case 0x5b30: goto loc_68_5b30;
        case 0x5b31: goto loc_68_5b31;
        case 0x5b34: goto pc_5b34;
        case 0x5b35: goto pc_5b35;
        case 0x5b36: goto pc_5b36;
        case 0x5b37: goto pc_5b37;
        case 0x5b38: goto pc_5b38;
        case 0x5b39: goto pc_5b39;
        case 0x5b3b: goto pc_5b3b;
        case 0x5b3c: goto loc_68_5b3c;
        case 0x5b3d: goto pc_5b3d;
        case 0x5b3e: goto loc_68_5b3e;
        case 0x5b3f: goto pc_5b3f;
        case 0x5b40: goto pc_5b40;
        case 0x5b41: goto pc_5b41;
        case 0x5b43: goto pc_5b43;
        case 0x5b44: goto loc_68_5b44;
        case 0x5b45: goto pc_5b45;
        case 0x5b46: goto pc_5b46;
        case 0x5b47: goto pc_5b47;
        case 0x5b49: goto pc_5b49;
        case 0x5b4a: goto pc_5b4a;
        case 0x5b4b: goto pc_5b4b;
        case 0x5b4d: goto pc_5b4d;
        case 0x5b4e: goto pc_5b4e;
        case 0x5b4f: goto pc_5b4f;
        case 0x5b50: goto pc_5b50;
        case 0x5b51: goto pc_5b51;
        case 0x5b52: goto pc_5b52;
        case 0x5b53: goto pc_5b53;
        case 0x5b54: goto pc_5b54;
        case 0x5b55: goto pc_5b55;
        case 0x5b56: goto pc_5b56;
        case 0x5b57: goto loc_68_5b57;
        case 0x5b5a: goto pc_5b5a;
        case 0x5b5b: goto loc_68_5b5b;
        case 0x5b5c: goto loc_68_5b5c;
        case 0x5b5f: goto pc_5b5f;
        case 0x5b60: goto loc_68_5b60;
        case 0x5b61: goto loc_68_5b61;
        case 0x5b62: goto loc_68_5b62;
        case 0x5b65: goto pc_5b65;
        case 0x5b66: goto pc_5b66;
        case 0x5b67: goto pc_5b67;
        default: break;
    }

loc_68_5aae:
    /* ADC A,$31 */
    /* 68:5aae */     gb_adc8(ctx, 0x31);
    ctx->pc = 0x5ab0;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5ab0:
    /* 68:5ab0 */     /* NOP */
    ctx->pc = 0x5ab1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$5931 */
pc_5ab1:
    /* 68:5ab1 */     ctx->bc = 0x5931;
    ctx->pc = 0x5ab4;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_5ab4:
    /* 68:5ab4 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x5ab5;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD SP,$0200 */
pc_5ab5:
    /* 68:5ab5 */     ctx->sp = 0x0200;
    ctx->pc = 0x5ab8;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD SP,$0059 */
pc_5ab8:
    /* 68:5ab8 */     ctx->sp = 0x0059;
    ctx->pc = 0x5abb;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,D */
pc_5abb:
    /* 68:5abb */     gb_adc8(ctx, ctx->d);
    ctx->pc = 0x5abc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,$09 */
pc_5abc:
    /* 68:5abc */     ctx->d = 0x09;
    ctx->pc = 0x5abe;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0b01 */
pc_5abe:
    /* 68:5abe */     ctx->bc = 0x0b01;
    ctx->pc = 0x5ac1;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_5ac1:
    /* 68:5ac1 */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x5ac2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5ac2:
    /* 68:5ac2 */     /* NOP */
    ctx->pc = 0x5ac3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x5ac3 in bank 104 */
    return;
loc_68_5acd:
    /* INC D */
    /* 68:5acd */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x5ace;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_68_5ace:
    /* INC B */
    /* 68:5ace */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x5acf;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,20 */
pc_5acf:
    /* 68:5acf */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x5ae5, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_68_5ae5;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5ad1, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_68_5ad1:
    /* CP B */
    /* 68:5ad1 */     gb_cp8(ctx, ctx->b);
    ctx->pc = 0x5ad2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_5ad2:
    /* 68:5ad2 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x5ad3;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),H */
pc_5ad3:
    /* 68:5ad3 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->h);
    gb_tick(ctx, 1);
    ctx->pc = 0x5ad4;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,A */
pc_5ad4:
    /* 68:5ad4 */     ctx->l = ctx->a;
    ctx->pc = 0x5ad5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,103 */
pc_5ad5:
    /* 68:5ad5 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x5b3e, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_68_5b3e;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5ad7, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_68_5ad7:
    /* LD L,A */
    /* 68:5ad7 */     ctx->l = ctx->a;
    ctx->pc = 0x5ad8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,98 */
pc_5ad8:
    /* 68:5ad8 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x5b3c, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_68_5b3c;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5ada, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_68_5ada:
    /* LD H,L */
    /* 68:5ada */     ctx->h = ctx->l;
    ctx->pc = 0x5adb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,C */
pc_5adb:
    /* 68:5adb */     ctx->a = ctx->c;
    ctx->pc = 0x5adc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,A */
pc_5adc:
    /* 68:5adc */     ctx->l = ctx->a;
    ctx->pc = 0x5add;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,(HL) */
pc_5add:
    /* 68:5add */     gb_tick(ctx, 7);
    ctx->l = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x5ade;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,H */
pc_5ade:
    /* 68:5ade */     ctx->h = ctx->h;
    ctx->pc = 0x5adf;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,32 */
pc_5adf:
    /* 68:5adf */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x5b01, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_68_5b01;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5ae1, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_68_5ae1:
    /* INC BC */
    /* 68:5ae1 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x5ae2;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,(HL) */
pc_5ae2:
    /* 68:5ae2 */     gb_tick(ctx, 7);
    gb_sbc8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x5ae3;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
pc_5ae3:
    /* 68:5ae3 */     ctx->h = ctx->l;
    ctx->pc = 0x5ae4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,$04 */
pc_5ae4:
    /* 68:5ae4 */     ctx->l = 0x04;
    ctx->pc = 0x5ae6;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$b108 */
pc_5ae6:
    /* 68:5ae6 */     ctx->bc = GB_ERAM_BASE + 0x1108;
    ctx->pc = 0x5ae9;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,20 */
pc_5ae9:
    /* 68:5ae9 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x5aff, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_68_5aff;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5aeb, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_68_5aeb; /* fallthrough */
loc_68_5ae5:
    /* INC B */
    /* 68:5ae5 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x5ae6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$b108 */
    /* 68:5ae6 */     ctx->bc = GB_ERAM_BASE + 0x1108;
    ctx->pc = 0x5ae9;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,20 */
    /* 68:5ae9 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x5aff, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_68_5aff;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5aeb, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_68_5aeb:
    /* JR NC,110 */
    /* 68:5aeb */     if (!ctx->f_c) {
        gbrt_timed_jump(ctx, 0x5b5b, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_68_5b5b;
    } /* NC */
    gbrt_timed_jump(ctx, 0x5aed, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_68_5aed:
    /* JR NZ,-65 */
    /* 68:5aed */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x5aae, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_68_5aae;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5aef, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_68_5aef:
    /* INC BC */
    /* 68:5aef */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x5af0;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB L */
pc_5af0:
    /* 68:5af0 */     gb_sub8(ctx, ctx->l);
    ctx->pc = 0x5af1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,20 */
pc_5af1:
    /* 68:5af1 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x5b07, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_68_5b07;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5af3, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_68_5af3:
    /* SBC A,B */
    /* 68:5af3 */     gb_sbc8(ctx, ctx->b);
    ctx->pc = 0x5af4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
pc_5af4:
    /* 68:5af4 */     ctx->h = ctx->l;
    ctx->pc = 0x5af5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),D */
pc_5af5:
    /* 68:5af5 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x5af6;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_5af6:
    /* 68:5af6 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x5af7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_5af7:
    /* 68:5af7 */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x5af8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC SP */
pc_5af8:
    /* 68:5af8 */     gbrt_timed_inc16(ctx, &ctx->sp);
    ctx->pc = 0x5af9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,$04 */
pc_5af9:
    /* 68:5af9 */     ctx->l = 0x04;
    ctx->pc = 0x5afb;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$1ac4 */
pc_5afb:
    /* 68:5afb */     ctx->bc = 0x1ac4;
    ctx->pc = 0x5afe;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RLCA */
pc_5afe:
    /* 68:5afe */     gb_rlca(ctx);
    ctx->pc = 0x5aff;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_68_5aff:
    /* LD (BC),A */
    /* 68:5aff */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x5b00;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC (HL) */
pc_5b00:
    /* 68:5b00 */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_dec8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x5b01;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_68_5b01:
    /* NOP */
    /* 68:5b01 */     /* NOP */
    ctx->pc = 0x5b02;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC DE */
pc_5b02:
    /* 68:5b02 */     gbrt_timed_dec16(ctx, &ctx->de);
    ctx->pc = 0x5b03;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RLCA */
pc_5b03:
    /* 68:5b03 */     gb_rlca(ctx);
    ctx->pc = 0x5b04;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0036 */
pc_5b04:
    /* 68:5b04 */     ctx->bc = 0x0036;
    ctx->pc = 0x5b07;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_68_5b07:
    /* NOP */
    /* 68:5b07 */     /* NOP */
    ctx->pc = 0x5b08;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB $03 */
pc_5b08:
    /* 68:5b08 */     gb_sub8(ctx, 0x03);
    ctx->pc = 0x5b0a;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC DE */
pc_5b0a:
    /* 68:5b0a */     gbrt_timed_dec16(ctx, &ctx->de);
    ctx->pc = 0x5b0b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC E */
pc_5b0b:
    /* 68:5b0b */     ctx->e = gb_dec8(ctx, ctx->e);
    ctx->pc = 0x5b0c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,H */
pc_5b0c:
    /* 68:5b0c */     ctx->c = ctx->h;
    ctx->pc = 0x5b0d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_5b0d:
    /* 68:5b0d */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x5b0e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_5b0e:
    /* 68:5b0e */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x5b0f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC A */
pc_5b0f:
    /* 68:5b0f */     ctx->a = gb_inc8(ctx, ctx->a);
    ctx->pc = 0x5b10;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,$17 */
pc_5b10:
    /* 68:5b10 */     gb_adc8(ctx, 0x17);
    ctx->pc = 0x5b12;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5b12:
    /* 68:5b12 */     gbrt_timed_rst(ctx, 0x38, 0x5b13);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_68_5b13:
    /* NOP */
    /* 68:5b13 */     /* NOP */
    ctx->pc = 0x5b14;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_5b14:
    /* 68:5b14 */     ctx->d = ctx->b;
    ctx->pc = 0x5b15;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,B */
pc_5b15:
    /* 68:5b15 */     ctx->c = ctx->b;
    ctx->pc = 0x5b16;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,$00 */
pc_5b16:
    /* 68:5b16 */     ctx->c = 0x00;
    ctx->pc = 0x5b18;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (DE),A */
pc_5b18:
    /* 68:5b18 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->de, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x5b19;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5b19:
    /* 68:5b19 */     /* NOP */
    ctx->pc = 0x5b1a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC DE */
pc_5b1a:
    /* 68:5b1a */     gbrt_timed_inc16(ctx, &ctx->de);
    ctx->pc = 0x5b1b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5b1b:
    /* 68:5b1b */     /* NOP */
    ctx->pc = 0x5b1c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_5b1c:
    /* 68:5b1c */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x5b1d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5b1d:
    /* 68:5b1d */     /* NOP */
    ctx->pc = 0x5b1e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC DE */
pc_5b1e:
    /* 68:5b1e */     gbrt_timed_dec16(ctx, &ctx->de);
    ctx->pc = 0x5b1f;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5b1f:
    /* 68:5b1f */     /* NOP */
    ctx->pc = 0x5b20;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_68_5b20:
    /* INC E */
    /* 68:5b20 */     ctx->e = gb_inc8(ctx, ctx->e);
    ctx->pc = 0x5b21;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5b21:
    /* 68:5b21 */     /* NOP */
    ctx->pc = 0x5b22;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5b22:
    /* 68:5b22 */     /* NOP */
    ctx->pc = 0x5b23;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC E */
pc_5b23:
    /* 68:5b23 */     ctx->e = gb_dec8(ctx, ctx->e);
    ctx->pc = 0x5b24;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5b24:
    /* 68:5b24 */     /* NOP */
    ctx->pc = 0x5b25;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5b25:
    /* 68:5b25 */     gbrt_timed_rst(ctx, 0x38, 0x5b26);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_68_5b26:
    /* RST $38 */
    /* 68:5b26 */     gbrt_timed_rst(ctx, 0x38, 0x5b27);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_68_5b27:
    /* RST $38 */
    /* 68:5b27 */     gbrt_timed_rst(ctx, 0x38, 0x5b28);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_68_5b28:
    /* LD BC,$0023 */
    /* 68:5b28 */     ctx->bc = 0x0023;
    ctx->pc = 0x5b2b;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_5b2b:
    /* 68:5b2b */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x5b2c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC H */
pc_5b2c:
    /* 68:5b2c */     ctx->h = gb_dec8(ctx, ctx->h);
    ctx->pc = 0x5b2d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5b2d:
    /* 68:5b2d */     /* NOP */
    ctx->pc = 0x5b2e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5b2e:
    /* 68:5b2e */     gbrt_timed_rst(ctx, 0x38, 0x5b2f);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_68_5b2f:
    /* RST $38 */
    /* 68:5b2f */     gbrt_timed_rst(ctx, 0x38, 0x5b30);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_68_5b30:
    /* RST $38 */
    /* 68:5b30 */     gbrt_timed_rst(ctx, 0x38, 0x5b31);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_68_5b31:
    /* LD SP,$0000 */
    /* 68:5b31 */     ctx->sp = 0x0000;
    ctx->pc = 0x5b34;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* XOR C */
pc_5b34:
    /* 68:5b34 */     gb_xor8(ctx, ctx->c);
    ctx->pc = 0x5b35;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_5b35:
    /* 68:5b35 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x5b36;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5b36:
    /* 68:5b36 */     /* NOP */
    ctx->pc = 0x5b37;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,DE */
pc_5b37:
    /* 68:5b37 */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x5b38;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5b38:
    /* 68:5b38 */     /* NOP */
    ctx->pc = 0x5b39;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB $03 */
pc_5b39:
    /* 68:5b39 */     gb_sub8(ctx, 0x03);
    ctx->pc = 0x5b3b;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC C */
pc_5b3b:
    /* 68:5b3b */     ctx->c = gb_dec8(ctx, ctx->c);
    ctx->pc = 0x5b3c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_68_5b3c:
    /* DEC B */
    /* 68:5b3c */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x5b3d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,H */
pc_5b3d:
    /* 68:5b3d */     ctx->c = ctx->h;
    ctx->pc = 0x5b3e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_68_5b3e:
    /* LD (BC),A */
    /* 68:5b3e */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x5b3f;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_5b3f:
    /* 68:5b3f */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x5b40;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC A */
pc_5b40:
    /* 68:5b40 */     ctx->a = gb_inc8(ctx, ctx->a);
    ctx->pc = 0x5b41;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,$17 */
pc_5b41:
    /* 68:5b41 */     gb_adc8(ctx, 0x17);
    ctx->pc = 0x5b43;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5b43:
    /* 68:5b43 */     gbrt_timed_rst(ctx, 0x38, 0x5b44);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_68_5b44:
    /* NOP */
    /* 68:5b44 */     /* NOP */
    ctx->pc = 0x5b45;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_5b45:
    /* 68:5b45 */     ctx->d = ctx->b;
    ctx->pc = 0x5b46;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,B */
pc_5b46:
    /* 68:5b46 */     ctx->c = ctx->b;
    ctx->pc = 0x5b47;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,$00 */
pc_5b47:
    /* 68:5b47 */     ctx->c = 0x00;
    ctx->pc = 0x5b49;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (DE),A */
pc_5b49:
    /* 68:5b49 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->de, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x5b4a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5b4a:
    /* 68:5b4a */     /* NOP */
    ctx->pc = 0x5b4b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,$00 */
pc_5b4b:
    /* 68:5b4b */     ctx->d = 0x00;
    ctx->pc = 0x5b4d;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RLA */
pc_5b4d:
    /* 68:5b4d */     gb_rla(ctx);
    ctx->pc = 0x5b4e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5b4e:
    /* 68:5b4e */     /* NOP */
    ctx->pc = 0x5b4f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC DE */
pc_5b4f:
    /* 68:5b4f */     gbrt_timed_dec16(ctx, &ctx->de);
    ctx->pc = 0x5b50;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5b50:
    /* 68:5b50 */     /* NOP */
    ctx->pc = 0x5b51;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC E */
pc_5b51:
    /* 68:5b51 */     ctx->e = gb_inc8(ctx, ctx->e);
    ctx->pc = 0x5b52;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5b52:
    /* 68:5b52 */     /* NOP */
    ctx->pc = 0x5b53;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5b53:
    /* 68:5b53 */     /* NOP */
    ctx->pc = 0x5b54;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC E */
pc_5b54:
    /* 68:5b54 */     ctx->e = gb_dec8(ctx, ctx->e);
    ctx->pc = 0x5b55;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5b55:
    /* 68:5b55 */     /* NOP */
    ctx->pc = 0x5b56;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5b56:
    /* 68:5b56 */     gbrt_timed_rst(ctx, 0x38, 0x5b57);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_68_5b57:
    /* LD BC,$0aab */
    /* 68:5b57 */     ctx->bc = 0x0aab;
    ctx->pc = 0x5b5a;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5b5a:
    /* 68:5b5a */     gbrt_timed_rst(ctx, 0x38, 0x5b5b);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_68_5b5b:
    /* RST $38 */
    /* 68:5b5b */     gbrt_timed_rst(ctx, 0x38, 0x5b5c);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_68_5b5c:
    /* LD BC,$0023 */
    /* 68:5b5c */     ctx->bc = 0x0023;
    ctx->pc = 0x5b5f;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5b5f:
    /* 68:5b5f */     gbrt_timed_rst(ctx, 0x38, 0x5b60);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_68_5b60:
    /* RST $38 */
    /* 68:5b60 */     gbrt_timed_rst(ctx, 0x38, 0x5b61);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_68_5b61:
    /* RST $38 */
    /* 68:5b61 */     gbrt_timed_rst(ctx, 0x38, 0x5b62);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_68_5b62:
    /* LD SP,$0200 */
    /* 68:5b62 */     ctx->sp = 0x0200;
    ctx->pc = 0x5b65;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* XOR C */
pc_5b65:
    /* 68:5b65 */     gb_xor8(ctx, ctx->c);
    ctx->pc = 0x5b66;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_5b66:
    /* 68:5b66 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x5b67;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5b67:
    /* 68:5b67 */     /* NOP */
    ctx->pc = 0x5b68;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x5b68 in bank 104 */
    return;
}

void func_68_5acd(GBContext* ctx) {
    body_68_5acd(ctx);
}

void func_68_5ace(GBContext* ctx) {
    body_68_5acd(ctx);
}

void func_68_5b20(GBContext* ctx) {
    body_68_5acd(ctx);
}

/* Shared body at 68:71cd */
static void body_68_71cd(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_68_71cd:
    /* RETI */
    /* 68:71cd */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* fallthrough to function */
    func_68_71ce(ctx);
    return;
}

void func_68_71cd(GBContext* ctx) {
    body_68_71cd(ctx);
}

/* Shared body at 68:7d47 */
static void body_68_7d47(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x7d47: goto loc_68_7d47;
        case 0x7d48: goto loc_68_7d48;
        case 0x7d49: goto pc_7d49;
        case 0x7d4a: goto pc_7d4a;
        case 0x7d4b: goto pc_7d4b;
        case 0x7d4c: goto pc_7d4c;
        default: break;
    }

loc_68_7d47:
    /* RST $38 */
    /* 68:7d47 */     gbrt_timed_rst(ctx, 0x38, 0x7d48);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_68_7d48:
    /* DEC DE */
    /* 68:7d48 */     gbrt_timed_dec16(ctx, &ctx->de);
    ctx->pc = 0x7d49;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB H */
pc_7d49:
    /* 68:7d49 */     gb_sub8(ctx, ctx->h);
    ctx->pc = 0x7d4a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7d4a:
    /* 68:7d4a */     /* NOP */
    ctx->pc = 0x7d4b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC D */
pc_7d4b:
    /* 68:7d4b */     ctx->d = gb_dec8(ctx, ctx->d);
    ctx->pc = 0x7d4c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,L */
pc_7d4c:
    /* 68:7d4c */     gb_adc8(ctx, ctx->l);
    ctx->pc = 0x7d4d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x7d4d in bank 104 */
    return;
}

void func_68_7d47(GBContext* ctx) {
    body_68_7d47(ctx);
}

