/* Generated by gbrecomp from Lufia - The Legend Returns (USA) */
#include "Lufia___The_Legend_Returns__USA__internal.h"

/* Shared body at 6e:4f3a */
static void body_6e_4f3a(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_6e_4f3a:
    /* RET */
    /* 6e:4f3a */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_6e_4f3a(GBContext* ctx) {
    body_6e_4f3a(ctx);
}

/* Shared body at 6e:7343 */
static void body_6e_7343(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x7343: goto loc_6e_7343;
        case 0x7345: goto loc_6e_7345;
        case 0x7346: goto pc_7346;
        case 0x7347: goto pc_7347;
        case 0x7348: goto pc_7348;
        case 0x7349: goto loc_6e_7349;
        case 0x734a: goto pc_734a;
        case 0x734c: goto pc_734c;
        case 0x734f: goto loc_6e_734f;
        case 0x7350: goto pc_7350;
        case 0x7351: goto pc_7351;
        case 0x7352: goto pc_7352;
        case 0x7353: goto pc_7353;
        case 0x7354: goto pc_7354;
        case 0x7355: goto pc_7355;
        case 0x7356: goto pc_7356;
        case 0x7359: goto loc_6e_7359;
        case 0x735a: goto pc_735a;
        case 0x735b: goto pc_735b;
        case 0x735c: goto pc_735c;
        case 0x735d: goto pc_735d;
        case 0x735e: goto pc_735e;
        case 0x735f: goto pc_735f;
        case 0x7360: goto loc_6e_7360;
        case 0x7361: goto loc_6e_7361;
        case 0x7362: goto loc_6e_7362;
        case 0x7365: goto loc_6e_7365;
        case 0x7366: goto loc_6e_7366;
        case 0x7367: goto loc_6e_7367;
        case 0x7368: goto pc_7368;
        case 0x7369: goto pc_7369;
        case 0x736a: goto pc_736a;
        case 0x736b: goto pc_736b;
        case 0x736c: goto pc_736c;
        case 0x736d: goto pc_736d;
        case 0x736e: goto pc_736e;
        case 0x736f: goto pc_736f;
        case 0x7370: goto pc_7370;
        case 0x7371: goto pc_7371;
        case 0x7372: goto pc_7372;
        case 0x7373: goto pc_7373;
        case 0x7374: goto pc_7374;
        case 0x7375: goto pc_7375;
        case 0x7376: goto pc_7376;
        case 0x7377: goto pc_7377;
        case 0x7378: goto loc_6e_7378;
        case 0x737a: goto pc_737a;
        case 0x737b: goto pc_737b;
        case 0x737c: goto loc_6e_737c;
        case 0x737d: goto pc_737d;
        case 0x737f: goto pc_737f;
        case 0x7381: goto pc_7381;
        case 0x7382: goto pc_7382;
        case 0x7383: goto loc_6e_7383;
        case 0x7384: goto pc_7384;
        case 0x7385: goto pc_7385;
        case 0x7386: goto pc_7386;
        case 0x7387: goto pc_7387;
        case 0x7388: goto pc_7388;
        case 0x738b: goto pc_738b;
        case 0x738c: goto pc_738c;
        case 0x738d: goto pc_738d;
        case 0x738e: goto pc_738e;
        case 0x738f: goto pc_738f;
        case 0x7390: goto pc_7390;
        case 0x7391: goto pc_7391;
        case 0x7392: goto pc_7392;
        case 0x7393: goto pc_7393;
        case 0x7394: goto pc_7394;
        default: break;
    }

loc_6e_7343:
    /* JR NZ,0 */
    /* 6e:7343 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7345, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_6e_7345;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7345, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_6e_7345:
    /* NOP */
    /* 6e:7345 */     /* NOP */
    ctx->pc = 0x7346;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7346:
    /* 6e:7346 */     /* NOP */
    ctx->pc = 0x7347;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_7347:
    /* 6e:7347 */     ctx->e = ctx->c;
    ctx->pc = 0x7348;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(BC) */
pc_7348:
    /* 6e:7348 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->bc);
    gb_tick(ctx, 1);
    ctx->pc = 0x7349;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_6e_7349:
    /* HALT */
    /* 6e:7349 */     gbrt_execute_halt(ctx, 0x734a, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
    /* LD L,$00 */
pc_734a:
    /* 6e:734a */     ctx->l = 0x00;
    ctx->pc = 0x734c;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL $0054 */
pc_734c:
    /* 6e:734c */     gbrt_timed_call(ctx, 0x54, 0x734f);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_0054(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_6e_734f:
    /* CPL */
    /* 6e:734f */     ctx->a = ~ctx->a; ctx->f_n = 1; ctx->f_h = 1;
    ctx->pc = 0x7350;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,H */
pc_7350:
    /* 6e:7350 */     ctx->d = ctx->h;
    ctx->pc = 0x7351;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7351:
    /* 6e:7351 */     gb_rrca(ctx);
    ctx->pc = 0x7352;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRA */
pc_7352:
    /* 6e:7352 */     gb_rra(ctx);
    ctx->pc = 0x7353;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC (HL) */
pc_7353:
    /* 6e:7353 */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_dec8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x7354;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,H */
pc_7354:
    /* 6e:7354 */     ctx->d = ctx->h;
    ctx->pc = 0x7355;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7355:
    /* 6e:7355 */     gb_rrca(ctx);
    ctx->pc = 0x7356;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR 1 */
pc_7356:
    /* 6e:7356 */     gbrt_timed_jump(ctx, 0x7359, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_6e_7359;
    if (ctx->single_step_mode) return;
loc_6e_7359:
    /* LD D,H */
    /* 6e:7359 */     ctx->d = ctx->h;
    ctx->pc = 0x735a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,C */
pc_735a:
    /* 6e:735a */     ctx->b = ctx->c;
    ctx->pc = 0x735b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_735b:
    /* 6e:735b */     gb_rrca(ctx);
    ctx->pc = 0x735c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (DE),A */
pc_735c:
    /* 6e:735c */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->de, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x735d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_735d:
    /* 6e:735d */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x735e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC (HL) */
pc_735e:
    /* 6e:735e */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_dec8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x735f;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,H */
pc_735f:
    /* 6e:735f */     ctx->d = ctx->h;
    ctx->pc = 0x7360;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_6e_7360:
    /* RRCA */
    /* 6e:7360 */     gb_rrca(ctx);
    ctx->pc = 0x7361;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_6e_7361:
    /* LD (DE),A */
    /* 6e:7361 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->de, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7362;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_6e_7362:
    /* LD BC,$5436 */
    /* 6e:7362 */     ctx->bc = 0x5436;
    ctx->pc = 0x7365;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_6e_7365:
    /* LD B,C */
    /* 6e:7365 */     ctx->b = ctx->c;
    ctx->pc = 0x7366;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_6e_7366:
    /* RST $38 */
    /* 6e:7366 */     gbrt_timed_rst(ctx, 0x38, 0x7367);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_6e_7367:
    /* DEC D */
    /* 6e:7367 */     ctx->d = gb_dec8(ctx, ctx->d);
    ctx->pc = 0x7368;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,L */
pc_7368:
    /* 6e:7368 */     gb_adc8(ctx, ctx->l);
    ctx->pc = 0x7369;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,C */
pc_7369:
    /* 6e:7369 */     gb_add8(ctx, ctx->c);
    ctx->pc = 0x736a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,BC */
pc_736a:
    /* 6e:736a */     gb_add16(ctx, ctx->bc);
    ctx->pc = 0x736b;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),B */
pc_736b:
    /* 6e:736b */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->b);
    gb_tick(ctx, 1);
    ctx->pc = 0x736c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC E */
pc_736c:
    /* 6e:736c */     ctx->e = gb_inc8(ctx, ctx->e);
    ctx->pc = 0x736d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,C */
pc_736d:
    /* 6e:736d */     gb_add8(ctx, ctx->c);
    ctx->pc = 0x736e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,BC */
pc_736e:
    /* 6e:736e */     gb_add16(ctx, ctx->bc);
    ctx->pc = 0x736f;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_736f:
    /* 6e:736f */     /* NOP */
    ctx->pc = 0x7370;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CPL */
pc_7370:
    /* 6e:7370 */     ctx->a = ~ctx->a; ctx->f_n = 1; ctx->f_h = 1;
    ctx->pc = 0x7371;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7371:
    /* 6e:7371 */     /* NOP */
    ctx->pc = 0x7372;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7372:
    /* 6e:7372 */     gb_rrca(ctx);
    ctx->pc = 0x7373;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (DE),A */
pc_7373:
    /* 6e:7373 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->de, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7374;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC L */
pc_7374:
    /* 6e:7374 */     ctx->l = gb_dec8(ctx, ctx->l);
    ctx->pc = 0x7375;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7375:
    /* 6e:7375 */     /* NOP */
    ctx->pc = 0x7376;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,C */
pc_7376:
    /* 6e:7376 */     ctx->b = ctx->c;
    ctx->pc = 0x7377;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_7377:
    /* 6e:7377 */     gb_rrca(ctx);
    ctx->pc = 0x7378;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_6e_7378:
    /* STOP */
    /* 6e:7378 */     ctx->pc = 0x737a;
    gb_stop(ctx);
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
    /* DEC (HL) */
pc_737a:
    /* 6e:737a */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_dec8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x737b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_737b:
    /* 6e:737b */     /* NOP */
    ctx->pc = 0x737c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_6e_737c:
    /* RRCA */
    /* 6e:737c */     gb_rrca(ctx);
    ctx->pc = 0x737d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* STOP */
pc_737d:
    /* 6e:737d */     ctx->pc = 0x737f;
    gb_stop(ctx);
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$00 */
pc_737f:
    /* 6e:737f */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x7381;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,C */
pc_7381:
    /* 6e:7381 */     ctx->b = ctx->c;
    ctx->pc = 0x7382;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_7382:
    /* 6e:7382 */     gbrt_timed_rst(ctx, 0x38, 0x7383);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_6e_7383:
    /* DEC D */
    /* 6e:7383 */     ctx->d = gb_dec8(ctx, ctx->d);
    ctx->pc = 0x7384;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,L */
pc_7384:
    /* 6e:7384 */     gb_adc8(ctx, ctx->l);
    ctx->pc = 0x7385;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND E */
pc_7385:
    /* 6e:7385 */     gb_and8(ctx, ctx->e);
    ctx->pc = 0x7386;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,BC */
pc_7386:
    /* 6e:7386 */     gb_add16(ctx, ctx->bc);
    ctx->pc = 0x7387;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_7387:
    /* 6e:7387 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x7388;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$71ce */
pc_7388:
    /* 6e:7388 */     ctx->bc = 0x71ce;
    ctx->pc = 0x738b;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),D */
pc_738b:
    /* 6e:738b */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x738c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,E */
pc_738c:
    /* 6e:738c */     ctx->c = ctx->e;
    ctx->pc = 0x738d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL-),A */
pc_738d:
    /* 6e:738d */     gbrt_timed_hl_write_auto(ctx, ctx->a, -1);
    ctx->pc = 0x738e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC E */
pc_738e:
    /* 6e:738e */     ctx->e = gb_inc8(ctx, ctx->e);
    ctx->pc = 0x738f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND E */
pc_738f:
    /* 6e:738f */     gb_and8(ctx, ctx->e);
    ctx->pc = 0x7390;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,BC */
pc_7390:
    /* 6e:7390 */     gb_add16(ctx, ctx->bc);
    ctx->pc = 0x7391;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7391:
    /* 6e:7391 */     /* NOP */
    ctx->pc = 0x7392;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(DE) */
pc_7392:
    /* 6e:7392 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->de);
    gb_tick(ctx, 1);
    ctx->pc = 0x7393;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* XOR E */
pc_7393:
    /* 6e:7393 */     gb_xor8(ctx, ctx->e);
    ctx->pc = 0x7394;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7394:
    /* 6e:7394 */     /* NOP */
    ctx->pc = 0x7395;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x7395 in bank 110 */
    return;
}

void func_6e_7343(GBContext* ctx) {
    body_6e_7343(ctx);
}

void func_6e_7345(GBContext* ctx) {
    body_6e_7343(ctx);
}

void func_6e_7349(GBContext* ctx) {
    body_6e_7343(ctx);
}

void func_6e_7360(GBContext* ctx) {
    body_6e_7343(ctx);
}

void func_6e_7361(GBContext* ctx) {
    body_6e_7343(ctx);
}

void func_6e_7362(GBContext* ctx) {
    body_6e_7343(ctx);
}

void func_6e_7365(GBContext* ctx) {
    body_6e_7343(ctx);
}

void func_6e_7366(GBContext* ctx) {
    body_6e_7343(ctx);
}

void func_6e_7378(GBContext* ctx) {
    body_6e_7343(ctx);
}

void func_6e_737c(GBContext* ctx) {
    body_6e_7343(ctx);
}

