/* Generated by gbrecomp from Lufia - The Legend Returns (USA) */
#include "Lufia___The_Legend_Returns__USA__internal.h"

/* Shared body at 6c:6e03 */
static void body_6c_6e03(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_6c_6e03:
    /* JP HL */
    /* 6c:6e03 */     gbrt_timed_jump(ctx, ctx->hl, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
}

void func_6c_6e03(GBContext* ctx) {
    body_6c_6e03(ctx);
}

/* Shared body at 6c:6e89 */
static void body_6c_6e89(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x6e89: goto loc_6c_6e89;
        case 0x6e8c: goto pc_6e8c;
        case 0x6e8f: goto pc_6e8f;
        default: break;
    }

loc_6c_6e89:
    /* LD SP,$0055 */
    /* 6c:6e89 */     ctx->sp = 0x0055;
    ctx->pc = 0x6e8c;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD SP,$0053 */
pc_6e8c:
    /* 6c:6e8c */     ctx->sp = 0x0053;
    ctx->pc = 0x6e8f;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RETI */
pc_6e8f:
    /* 6c:6e8f */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* fallthrough to function */
    func_6c_6e90(ctx);
    return;
}

void func_6c_6e89(GBContext* ctx) {
    body_6c_6e89(ctx);
}

/* Shared body at 6c:7614 */
static void body_6c_7614(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x7614: goto loc_6c_7614;
        case 0x7615: goto pc_7615;
        case 0x7618: goto pc_7618;
        case 0x761b: goto pc_761b;
        default: break;
    }

loc_6c_7614:
    /* LD (BC),A */
    /* 6c:7614 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7615;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD SP,$0055 */
pc_7615:
    /* 6c:7615 */     ctx->sp = 0x0055;
    ctx->pc = 0x7618;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD SP,$0053 */
pc_7618:
    /* 6c:7618 */     ctx->sp = 0x0053;
    ctx->pc = 0x761b;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RETI */
pc_761b:
    /* 6c:761b */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x761c in bank 108 */
    return;
}

void func_6c_7614(GBContext* ctx) {
    body_6c_7614(ctx);
}

/* Shared body at 6c:7616 */
static void body_6c_7616(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x7616: goto loc_6c_7616;
        case 0x7617: goto loc_6c_7617;
        case 0x7618: goto pc_7618;
        case 0x761b: goto pc_761b;
        default: break;
    }

loc_6c_7616:
    /* LD D,L */
    /* 6c:7616 */     ctx->d = ctx->l;
    ctx->pc = 0x7617;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_6c_7617:
    /* NOP */
    /* 6c:7617 */     /* NOP */
    ctx->pc = 0x7618;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD SP,$0053 */
pc_7618:
    /* 6c:7618 */     ctx->sp = 0x0053;
    ctx->pc = 0x761b;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RETI */
pc_761b:
    /* 6c:761b */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x761c in bank 108 */
    return;
}

void func_6c_7616(GBContext* ctx) {
    body_6c_7616(ctx);
}

void func_6c_7617(GBContext* ctx) {
    body_6c_7616(ctx);
}

/* Shared body at 6c:772a */
static void body_6c_772a(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x772a: goto loc_6c_772a;
        case 0x772b: goto loc_6c_772b;
        case 0x772c: goto loc_6c_772c;
        case 0x772d: goto loc_6c_772d;
        case 0x772e: goto pc_772e;
        case 0x772f: goto pc_772f;
        default: break;
    }

loc_6c_772a:
    /* RST $38 */
    /* 6c:772a */     gbrt_timed_rst(ctx, 0x38, 0x772b);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_6c_772b:
    /* RST $38 */
    /* 6c:772b */     gbrt_timed_rst(ctx, 0x38, 0x772c);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_6c_772c:
    /* RST $38 */
    /* 6c:772c */     gbrt_timed_rst(ctx, 0x38, 0x772d);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_6c_772d:
    /* NOP */
    /* 6c:772d */     /* NOP */
    ctx->pc = 0x772e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC D */
pc_772e:
    /* 6c:772e */     ctx->d = gb_dec8(ctx, ctx->d);
    ctx->pc = 0x772f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,L */
pc_772f:
    /* 6c:772f */     gb_adc8(ctx, ctx->l);
    ctx->pc = 0x7730;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x7730 in bank 108 */
    return;
}

void func_6c_772a(GBContext* ctx) {
    body_6c_772a(ctx);
}

