/* Generated by gbrecomp from Lufia - The Legend Returns (USA) */
#include "Lufia___The_Legend_Returns__USA__internal.h"

/* Shared body at 67:6421 */
static void body_67_6421(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_67_6421:
    /* JP $9a03 */
    /* 67:6421 */     gbrt_timed_jump(ctx, 0x9a03, 16); return;
    if (ctx->single_step_mode) return;
}

void func_67_6421(GBContext* ctx) {
    body_67_6421(ctx);
}

