/* Generated by gbrecomp from Lufia - The Legend Returns (USA) */
#include "Lufia___The_Legend_Returns__USA__internal.h"

/* Shared body at 6b:45bf */
static void body_6b_45bf(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x45bf: goto loc_6b_45bf;
        case 0x45c0: goto pc_45c0;
        case 0x45c2: goto pc_45c2;
        case 0x45c3: goto pc_45c3;
        default: break;
    }

loc_6b_45bf:
    /* LD D,E */
    /* 6b:45bf */     ctx->d = ctx->e;
    ctx->pc = 0x45c0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* OR $02 */
pc_45c0:
    /* 6b:45c0 */     gb_or8(ctx, 0x02);
    ctx->pc = 0x45c2;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,H */
pc_45c2:
    /* 6b:45c2 */     ctx->d = ctx->h;
    ctx->pc = 0x45c3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RETI */
pc_45c3:
    /* 6b:45c3 */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x45c4 in bank 107 */
    return;
}

void func_6b_45bf(GBContext* ctx) {
    body_6b_45bf(ctx);
}

/* Shared body at 6b:4917 */
static void body_6b_4917(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_6b_4917:
    /* RET */
    /* 6b:4917 */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_6b_4917(GBContext* ctx) {
    body_6b_4917(ctx);
}

/* Shared body at 6b:4920 */
static void body_6b_4920(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_6b_4920:
    /* RET */
    /* 6b:4920 */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_6b_4920(GBContext* ctx) {
    body_6b_4920(ctx);
}

/* Shared body at 6b:512f */
static void body_6b_512f(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x512f: goto loc_6b_512f;
        case 0x5130: goto loc_6b_5130;
        default: break;
    }

loc_6b_512f:
    /* RST $38 */
    /* 6b:512f */     gbrt_timed_rst(ctx, 0x38, 0x5130);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_6b_5130:
    goto loc_6b_5130; /* fallthrough */
}

void func_6b_512f(GBContext* ctx) {
    body_6b_512f(ctx);
}

/* Shared body at 6b:5fc1 */
static void body_6b_5fc1(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x5fc1: goto loc_6b_5fc1;
        case 0x5fc2: goto pc_5fc2;
        case 0x5fc3: goto pc_5fc3;
        case 0x5fc4: goto pc_5fc4;
        default: break;
    }

loc_6b_5fc1:
    /* DAA */
    /* 6b:5fc1 */     gb_daa(ctx);
    ctx->pc = 0x5fc2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),E */
pc_5fc2:
    /* 6b:5fc2 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->e);
    gb_tick(ctx, 1);
    ctx->pc = 0x5fc3;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_5fc3:
    /* 6b:5fc3 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x5fc4;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP $c120 */
pc_5fc4:
    /* 6b:5fc4 */     gbrt_timed_jump(ctx, 0xc120, 16); return;
    if (ctx->single_step_mode) return;
}

void func_6b_5fc1(GBContext* ctx) {
    body_6b_5fc1(ctx);
}

/* Shared body at 6b:6144 */
static void body_6b_6144(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_6b_6144:
    /* RETI */
    /* 6b:6144 */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* fallthrough to function */
    func_6b_6145(ctx);
    return;
}

void func_6b_6144(GBContext* ctx) {
    body_6b_6144(ctx);
}

/* Shared body at 6b:6148 */
static void body_6b_6148(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_6b_6148:
    /* RETI */
    /* 6b:6148 */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x6149 in bank 107 */
    return;
}

void func_6b_6148(GBContext* ctx) {
    body_6b_6148(ctx);
}

/* Shared body at 6b:614a */
static void body_6b_614a(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_6b_614a:
    /* RETI */
    /* 6b:614a */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x614b in bank 107 */
    return;
}

void func_6b_614a(GBContext* ctx) {
    body_6b_614a(ctx);
}

/* Shared body at 6b:720d */
static void body_6b_720d(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x720d: goto loc_6b_720d;
        case 0x720e: goto pc_720e;
        default: break;
    }

loc_6b_720d:
    /* INC D */
    /* 6b:720d */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x720e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RETI */
pc_720e:
    /* 6b:720e */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* fallthrough to function */
    func_6b_720f(ctx);
    return;
}

void func_6b_720d(GBContext* ctx) {
    body_6b_720d(ctx);
}

/* Shared body at 6b:7615 */
static void body_6b_7615(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_6b_7615:
    /* JP HL */
    /* 6b:7615 */     gbrt_timed_jump(ctx, ctx->hl, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
}

void func_6b_7615(GBContext* ctx) {
    body_6b_7615(ctx);
}

