/* Generated by gbrecomp from Lufia - The Legend Returns (USA) */
#include "Lufia___The_Legend_Returns__USA__internal.h"

/* Shared body at 15:77a9 */
static void body_15_77a9(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x77a9: goto loc_15_77a9;
        case 0x77ac: goto pc_77ac;
        case 0x77ad: goto pc_77ad;
        case 0x77af: goto loc_15_77af;
        case 0x77b0: goto loc_15_77b0;
        case 0x77b1: goto pc_77b1;
        case 0x77b2: goto loc_15_77b2;
        case 0x77b5: goto loc_15_77b5;
        case 0x77b8: goto pc_77b8;
        case 0x77b9: goto pc_77b9;
        case 0x77ba: goto pc_77ba;
        case 0x77bb: goto pc_77bb;
        case 0x77bc: goto pc_77bc;
        case 0x77bd: goto pc_77bd;
        case 0x77be: goto pc_77be;
        case 0x77c1: goto pc_77c1;
        case 0x77c2: goto pc_77c2;
        case 0x77c3: goto pc_77c3;
        case 0x77c6: goto pc_77c6;
        case 0x77c7: goto pc_77c7;
        case 0x77c8: goto pc_77c8;
        case 0x77c9: goto pc_77c9;
        case 0x77ca: goto pc_77ca;
        case 0x77cc: goto pc_77cc;
        case 0x77cd: goto pc_77cd;
        case 0x77ce: goto pc_77ce;
        case 0x77cf: goto pc_77cf;
        case 0x77d0: goto pc_77d0;
        case 0x77d1: goto pc_77d1;
        case 0x77d2: goto pc_77d2;
        case 0x77d4: goto pc_77d4;
        case 0x77d5: goto loc_15_77d5;
        case 0x77d6: goto pc_77d6;
        case 0x77d7: goto pc_77d7;
        case 0x77da: goto pc_77da;
        case 0x77db: goto pc_77db;
        case 0x77dd: goto loc_15_77dd;
        case 0x77df: goto loc_15_77df;
        case 0x77e0: goto pc_77e0;
        case 0x77e1: goto pc_77e1;
        case 0x77e3: goto pc_77e3;
        case 0x77e5: goto pc_77e5;
        case 0x77e6: goto loc_15_77e6;
        case 0x77e7: goto loc_15_77e7;
        case 0x77e8: goto pc_77e8;
        case 0x77e9: goto pc_77e9;
        case 0x77ea: goto loc_15_77ea;
        case 0x77eb: goto pc_77eb;
        case 0x77ec: goto pc_77ec;
        case 0x77ee: goto pc_77ee;
        case 0x77f0: goto pc_77f0;
        case 0x77f2: goto loc_15_77f2;
        case 0x77f3: goto pc_77f3;
        case 0x77f4: goto pc_77f4;
        case 0x77f5: goto loc_15_77f5;
        case 0x77f6: goto loc_15_77f6;
        case 0x77f7: goto pc_77f7;
        case 0x77f9: goto pc_77f9;
        case 0x77fa: goto loc_15_77fa;
        case 0x77fb: goto pc_77fb;
        case 0x77fd: goto loc_15_77fd;
        case 0x77fe: goto pc_77fe;
        case 0x77ff: goto loc_15_77ff;
        case 0x7800: goto loc_15_7800;
        case 0x7801: goto loc_15_7801;
        case 0x7802: goto pc_7802;
        case 0x7803: goto loc_15_7803;
        case 0x7804: goto loc_15_7804;
        case 0x7806: goto loc_15_7806;
        case 0x7807: goto loc_15_7807;
        case 0x7808: goto loc_15_7808;
        case 0x7809: goto pc_7809;
        case 0x780a: goto pc_780a;
        case 0x780b: goto pc_780b;
        case 0x780c: goto pc_780c;
        case 0x780e: goto loc_15_780e;
        case 0x780f: goto loc_15_780f;
        case 0x7811: goto loc_15_7811;
        case 0x7812: goto pc_7812;
        case 0x7813: goto pc_7813;
        case 0x7815: goto loc_15_7815;
        case 0x7816: goto pc_7816;
        case 0x7817: goto pc_7817;
        case 0x7818: goto loc_15_7818;
        case 0x7819: goto loc_15_7819;
        case 0x781a: goto pc_781a;
        case 0x781b: goto pc_781b;
        case 0x781c: goto pc_781c;
        case 0x781d: goto pc_781d;
        case 0x7820: goto loc_15_7820;
        case 0x7821: goto loc_15_7821;
        case 0x7822: goto loc_15_7822;
        case 0x7823: goto loc_15_7823;
        case 0x7826: goto pc_7826;
        case 0x7827: goto pc_7827;
        case 0x7828: goto pc_7828;
        case 0x7829: goto pc_7829;
        case 0x782a: goto loc_15_782a;
        case 0x782b: goto pc_782b;
        case 0x782c: goto pc_782c;
        case 0x782d: goto loc_15_782d;
        case 0x782e: goto loc_15_782e;
        case 0x7830: goto pc_7830;
        case 0x7831: goto pc_7831;
        case 0x7832: goto loc_15_7832;
        case 0x7833: goto pc_7833;
        case 0x7834: goto loc_15_7834;
        case 0x7835: goto loc_15_7835;
        case 0x7836: goto pc_7836;
        case 0x7837: goto pc_7837;
        case 0x7838: goto pc_7838;
        case 0x783a: goto loc_15_783a;
        case 0x783b: goto pc_783b;
        case 0x783c: goto loc_15_783c;
        case 0x783d: goto loc_15_783d;
        case 0x783e: goto loc_15_783e;
        case 0x783f: goto loc_15_783f;
        case 0x7840: goto loc_15_7840;
        case 0x7841: goto pc_7841;
        case 0x7842: goto loc_15_7842;
        case 0x7845: goto loc_15_7845;
        case 0x7846: goto pc_7846;
        case 0x7847: goto pc_7847;
        case 0x7848: goto pc_7848;
        case 0x7849: goto pc_7849;
        case 0x784a: goto pc_784a;
        case 0x784b: goto loc_15_784b;
        case 0x784e: goto pc_784e;
        case 0x784f: goto loc_15_784f;
        case 0x7850: goto pc_7850;
        case 0x7851: goto pc_7851;
        case 0x7854: goto pc_7854;
        case 0x7855: goto loc_15_7855;
        case 0x7856: goto pc_7856;
        case 0x7858: goto pc_7858;
        case 0x785b: goto loc_15_785b;
        case 0x785c: goto pc_785c;
        case 0x785d: goto pc_785d;
        case 0x785f: goto loc_15_785f;
        case 0x7861: goto pc_7861;
        case 0x7862: goto pc_7862;
        case 0x7865: goto pc_7865;
        case 0x7866: goto pc_7866;
        case 0x7868: goto loc_15_7868;
        case 0x786a: goto loc_15_786a;
        case 0x786b: goto pc_786b;
        case 0x786c: goto pc_786c;
        case 0x786e: goto pc_786e;
        case 0x786f: goto loc_15_786f;
        case 0x7870: goto pc_7870;
        case 0x7872: goto loc_15_7872;
        case 0x7873: goto pc_7873;
        case 0x7874: goto pc_7874;
        case 0x7876: goto loc_15_7876;
        case 0x7877: goto pc_7877;
        case 0x7879: goto loc_15_7879;
        case 0x787a: goto pc_787a;
        case 0x787b: goto pc_787b;
        case 0x787e: goto pc_787e;
        case 0x7881: goto loc_15_7881;
        case 0x7884: goto pc_7884;
        case 0x7885: goto pc_7885;
        case 0x7886: goto pc_7886;
        case 0x7887: goto pc_7887;
        case 0x7888: goto pc_7888;
        case 0x7889: goto pc_7889;
        case 0x788a: goto pc_788a;
        default: break;
    }

loc_15_77a9:
    /* LD HL,$0010 */
    /* 15:77a9 */     ctx->hl = 0x0010;
    ctx->pc = 0x77ac;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,DE */
pc_77ac:
    /* 15:77ac */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x77ad;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$00 */
pc_77ad:
    /* 15:77ad */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x77af;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_77af:
    /* LD BC,$77be */
    /* 15:77af */     ctx->bc = 0x77be;
    ctx->pc = 0x77b2;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_77b2; /* fallthrough */
loc_15_77b0:
    /* CP (HL) */
    /* 15:77b0 */     gb_tick(ctx, 7);
    gb_cp8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x77b1;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),A */
pc_77b1:
    /* 15:77b1 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x77b2;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_77b2:
    /* CALL $246b */
    /* 15:77b2 */     gbrt_timed_call(ctx, 0x246b, 0x77b5);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_246b(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_15_77b5:
    /* LD HL,$0001 */
    /* 15:77b5 */     ctx->hl = 0x0001;
    ctx->pc = 0x77b8;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,DE */
pc_77b8:
    /* 15:77b8 */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x77b9;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),A */
pc_77b9:
    /* 15:77b9 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x77ba;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_77ba:
    /* 15:77ba */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x77bb;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),C */
pc_77bb:
    /* 15:77bb */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->c);
    gb_tick(ctx, 1);
    ctx->pc = 0x77bc;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_77bc:
    /* 15:77bc */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x77bd;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),B */
pc_77bd:
    /* 15:77bd */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->b);
    gb_tick(ctx, 1);
    ctx->pc = 0x77be;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$0010 */
pc_77be:
    /* 15:77be */     ctx->hl = 0x0010;
    ctx->pc = 0x77c1;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,DE */
pc_77c1:
    /* 15:77c1 */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x77c2;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL) */
pc_77c2:
    /* 15:77c2 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x77c3;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$78fd */
pc_77c3:
    /* 15:77c3 */     ctx->hl = 0x78fd;
    ctx->pc = 0x77c6;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,A */
pc_77c6:
    /* 15:77c6 */     gb_add8(ctx, ctx->a);
    ctx->pc = 0x77c7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,L */
pc_77c7:
    /* 15:77c7 */     gb_add8(ctx, ctx->l);
    ctx->pc = 0x77c8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,A */
pc_77c8:
    /* 15:77c8 */     ctx->l = ctx->a;
    ctx->pc = 0x77c9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,H */
pc_77c9:
    /* 15:77c9 */     ctx->a = ctx->h;
    ctx->pc = 0x77ca;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,$00 */
pc_77ca:
    /* 15:77ca */     gb_adc8(ctx, 0x00);
    ctx->pc = 0x77cc;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,A */
pc_77cc:
    /* 15:77cc */     ctx->h = ctx->a;
    ctx->pc = 0x77cd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,(HL) */
pc_77cd:
    /* 15:77cd */     gb_tick(ctx, 7);
    ctx->b = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x77ce;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_77ce:
    /* 15:77ce */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x77cf;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,(HL) */
pc_77cf:
    /* 15:77cf */     gb_tick(ctx, 7);
    ctx->c = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x77d0;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH DE */
pc_77d0:
    /* 15:77d0 */     gbrt_timed_push16(ctx, ctx->de);
    ctx->pc = 0x77d1;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH AF */
pc_77d1:
    /* 15:77d1 */     gb_pack_flags(ctx); gbrt_timed_push16(ctx, ctx->af & 0xFFF0);
    ctx->pc = 0x77d2;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,$00 */
pc_77d2:
    /* 15:77d2 */     ctx->a = 0x00;
    ctx->pc = 0x77d4;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH ($FF00+$4f),A */
pc_77d4:
    /* 15:77d4 */     gb_tick(ctx, 11);
    gb_write8(ctx, GB_IO_BASE + 0x4f, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x77d6;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* POP AF */
pc_77d6:
    /* 15:77d6 */     ctx->af = gbrt_timed_pop16(ctx) & 0xFFF0; gb_unpack_flags(ctx);
    ctx->pc = 0x77d7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$8100 */
pc_77d7:
    /* 15:77d7 */     ctx->hl = GB_VRAM_BASE + 0x0100;
    ctx->pc = 0x77da;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB A */
pc_77da:
    /* 15:77da */     gb_sub8(ctx, ctx->a);
    ctx->pc = 0x77db;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,$60 */
pc_77db:
    /* 15:77db */     ctx->d = 0x60;
    ctx->pc = 0x77dd;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_77dd; /* fallthrough */
loc_15_77d5:
    /* LD C,A */
    /* 15:77d5 */     ctx->c = ctx->a;
    ctx->pc = 0x77d6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* POP AF */
    /* 15:77d6 */     ctx->af = gbrt_timed_pop16(ctx) & 0xFFF0; gb_unpack_flags(ctx);
    ctx->pc = 0x77d7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$8100 */
    /* 15:77d7 */     ctx->hl = GB_VRAM_BASE + 0x0100;
    ctx->pc = 0x77da;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB A */
    /* 15:77da */     gb_sub8(ctx, ctx->a);
    ctx->pc = 0x77db;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,$60 */
    /* 15:77db */     ctx->d = 0x60;
    ctx->pc = 0x77dd;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_77dd:
    /* LD E,$04 */
    /* 15:77dd */     ctx->e = 0x04;
    ctx->pc = 0x77df;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_77df:
    /* EI */
    /* 15:77df */     ctx->ime_pending = 1;
    ctx->pc = 0x77e0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DI */
pc_77e0:
    /* 15:77e0 */     ctx->ime = 0; ctx->ime_pending = 0; /* Also cancel pending EI */
    ctx->pc = 0x77e1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH A,($FF00+$41) */
pc_77e1:
    /* 15:77e1 */     gb_tick(ctx, 11);
    ctx->a = gb_read8(ctx, GB_IO_STAT);
    gb_tick(ctx, 1);
    ctx->pc = 0x77e3;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND $02 */
pc_77e3:
    /* 15:77e3 */     gb_and8(ctx, 0x02);
    ctx->pc = 0x77e5;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-8 */
pc_77e5:
    /* 15:77e5 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x77df, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_77df;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x77e7, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_77e7; /* fallthrough */
loc_15_77e6:
    /* LD HL,SP+126 */
    /* 15:77e6 */     gbrt_timed_ld_hl_sp_n(ctx, 0x77e7);
    ctx->pc = 0x77e8;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND B */
pc_77e8:
    /* 15:77e8 */     gb_and8(ctx, ctx->b);
    ctx->pc = 0x77e9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL+),A */
pc_77e9:
    /* 15:77e9 */     gbrt_timed_hl_write_auto(ctx, ctx->a, 1);
    ctx->pc = 0x77ea;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_77ea; /* fallthrough */
loc_15_77e7:
    /* LD A,(HL) */
    /* 15:77e7 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x77e8;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND B */
    /* 15:77e8 */     gb_and8(ctx, ctx->b);
    ctx->pc = 0x77e9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL+),A */
    /* 15:77e9 */     gbrt_timed_hl_write_auto(ctx, ctx->a, 1);
    ctx->pc = 0x77ea;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_77ea:
    /* EI */
    /* 15:77ea */     ctx->ime_pending = 1;
    ctx->pc = 0x77eb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DI */
pc_77eb:
    /* 15:77eb */     ctx->ime = 0; ctx->ime_pending = 0; /* Also cancel pending EI */
    ctx->pc = 0x77ec;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH A,($FF00+$41) */
pc_77ec:
    /* 15:77ec */     gb_tick(ctx, 11);
    ctx->a = gb_read8(ctx, GB_IO_STAT);
    gb_tick(ctx, 1);
    ctx->pc = 0x77ee;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND $02 */
pc_77ee:
    /* 15:77ee */     gb_and8(ctx, 0x02);
    ctx->pc = 0x77f0;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-8 */
pc_77f0:
    /* 15:77f0 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x77ea, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_77ea;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x77f2, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_77f2:
    /* LD A,(HL) */
    /* 15:77f2 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x77f3;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND B */
pc_77f3:
    /* 15:77f3 */     gb_and8(ctx, ctx->b);
    ctx->pc = 0x77f4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL+),A */
pc_77f4:
    /* 15:77f4 */     gbrt_timed_hl_write_auto(ctx, ctx->a, 1);
    ctx->pc = 0x77f5;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_77f5:
    /* EI */
    /* 15:77f5 */     ctx->ime_pending = 1;
    ctx->pc = 0x77f6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_77f6:
    /* DI */
    /* 15:77f6 */     ctx->ime = 0; ctx->ime_pending = 0; /* Also cancel pending EI */
    ctx->pc = 0x77f7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH A,($FF00+$41) */
pc_77f7:
    /* 15:77f7 */     gb_tick(ctx, 11);
    ctx->a = gb_read8(ctx, GB_IO_STAT);
    gb_tick(ctx, 1);
    ctx->pc = 0x77f9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND $02 */
pc_77f9:
    /* 15:77f9 */     gb_and8(ctx, 0x02);
    ctx->pc = 0x77fb;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-8 */
pc_77fb:
    /* 15:77fb */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x77f5, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_77f5;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x77fd, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_77fd; /* fallthrough */
loc_15_77fa:
    /* LD (BC),A */
    /* 15:77fa */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x77fb;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-8 */
    /* 15:77fb */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x77f5, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_77f5;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x77fd, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_77fd:
    /* LD A,(HL) */
    /* 15:77fd */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x77fe;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND C */
pc_77fe:
    /* 15:77fe */     gb_and8(ctx, ctx->c);
    ctx->pc = 0x77ff;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_77ff:
    /* LD (HL+),A */
    /* 15:77ff */     gbrt_timed_hl_write_auto(ctx, ctx->a, 1);
    ctx->pc = 0x7800;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_7800:
    /* EI */
    /* 15:7800 */     ctx->ime_pending = 1;
    ctx->pc = 0x7801;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_7801:
    /* DI */
    /* 15:7801 */     ctx->ime = 0; ctx->ime_pending = 0; /* Also cancel pending EI */
    ctx->pc = 0x7802;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH A,($FF00+$41) */
pc_7802:
    /* 15:7802 */     gb_tick(ctx, 11);
    ctx->a = gb_read8(ctx, GB_IO_STAT);
    gb_tick(ctx, 1);
    ctx->pc = 0x7804;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_7804; /* fallthrough */
loc_15_7803:
    /* LD B,C */
    /* 15:7803 */     ctx->b = ctx->c;
    ctx->pc = 0x7804;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_7804:
    /* AND $02 */
    /* 15:7804 */     gb_and8(ctx, 0x02);
    ctx->pc = 0x7806;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_7806:
    /* JR NZ,-8 */
    /* 15:7806 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7800, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_7800;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7808, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_7808; /* fallthrough */
loc_15_7807:
    /* LD HL,SP+126 */
    /* 15:7807 */     gbrt_timed_ld_hl_sp_n(ctx, 0x7808);
    ctx->pc = 0x7809;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND C */
pc_7809:
    /* 15:7809 */     gb_and8(ctx, ctx->c);
    ctx->pc = 0x780a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL+),A */
pc_780a:
    /* 15:780a */     gbrt_timed_hl_write_auto(ctx, ctx->a, 1);
    ctx->pc = 0x780b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC E */
pc_780b:
    /* 15:780b */     ctx->e = gb_dec8(ctx, ctx->e);
    ctx->pc = 0x780c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-47 */
pc_780c:
    /* 15:780c */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x77df, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_77df;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x780e, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_780e; /* fallthrough */
loc_15_7808:
    /* LD A,(HL) */
    /* 15:7808 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x7809;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND C */
    /* 15:7809 */     gb_and8(ctx, ctx->c);
    ctx->pc = 0x780a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL+),A */
    /* 15:780a */     gbrt_timed_hl_write_auto(ctx, ctx->a, 1);
    ctx->pc = 0x780b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC E */
    /* 15:780b */     ctx->e = gb_dec8(ctx, ctx->e);
    ctx->pc = 0x780c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-47 */
    /* 15:780c */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x77df, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_77df;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x780e, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_780e:
    /* DEC D */
    /* 15:780e */     ctx->d = gb_dec8(ctx, ctx->d);
    ctx->pc = 0x780f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_780f:
    /* JR NZ,-52 */
    /* 15:780f */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x77dd, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_77dd;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7811, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_7811:
    /* EI */
    /* 15:7811 */     ctx->ime_pending = 1;
    ctx->pc = 0x7812;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* POP DE */
pc_7812:
    /* 15:7812 */     ctx->de = gbrt_timed_pop16(ctx);
    ctx->pc = 0x7813;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$000e */
pc_7813:
    /* 15:7813 */     ctx->hl = 0x000e;
    ctx->pc = 0x7816;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,DE */
pc_7816:
    /* 15:7816 */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x7817;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0004 */
pc_7817:
    /* 15:7817 */     ctx->bc = 0x0004;
    ctx->pc = 0x781a;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,C */
pc_781a:
    /* 15:781a */     ctx->a = ctx->c;
    ctx->pc = 0x781b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL+),A */
pc_781b:
    /* 15:781b */     gbrt_timed_hl_write_auto(ctx, ctx->a, 1);
    ctx->pc = 0x781c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),B */
pc_781c:
    /* 15:781c */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->b);
    gb_tick(ctx, 1);
    ctx->pc = 0x781d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$782d */
pc_781d:
    /* 15:781d */     ctx->bc = 0x782d;
    ctx->pc = 0x7820;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_7820; /* fallthrough */
loc_15_7815:
    /* NOP */
    /* 15:7815 */     /* NOP */
    ctx->pc = 0x7816;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,DE */
    /* 15:7816 */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x7817;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0004 */
    /* 15:7817 */     ctx->bc = 0x0004;
    ctx->pc = 0x781a;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,C */
    /* 15:781a */     ctx->a = ctx->c;
    ctx->pc = 0x781b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL+),A */
    /* 15:781b */     gbrt_timed_hl_write_auto(ctx, ctx->a, 1);
    ctx->pc = 0x781c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),B */
    /* 15:781c */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->b);
    gb_tick(ctx, 1);
    ctx->pc = 0x781d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$782d */
    /* 15:781d */     ctx->bc = 0x782d;
    ctx->pc = 0x7820;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_7820; /* fallthrough */
loc_15_7818:
    /* INC B */
    /* 15:7818 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x7819;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_7819:
    /* NOP */
    /* 15:7819 */     /* NOP */
    ctx->pc = 0x781a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,C */
    /* 15:781a */     ctx->a = ctx->c;
    ctx->pc = 0x781b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL+),A */
    /* 15:781b */     gbrt_timed_hl_write_auto(ctx, ctx->a, 1);
    ctx->pc = 0x781c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),B */
    /* 15:781c */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->b);
    gb_tick(ctx, 1);
    ctx->pc = 0x781d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$782d */
    /* 15:781d */     ctx->bc = 0x782d;
    ctx->pc = 0x7820;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_7820:
    /* CALL $246b */
    /* 15:7820 */     gbrt_timed_call(ctx, 0x246b, 0x7823);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_246b(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_15_7823; /* fallthrough */
loc_15_7821:
    /* LD L,E */
    /* 15:7821 */     ctx->l = ctx->e;
    ctx->pc = 0x7822;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_7822:
    /* INC H */
    /* 15:7822 */     ctx->h = gb_inc8(ctx, ctx->h);
    ctx->pc = 0x7823;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_7823:
    /* LD HL,$0001 */
    /* 15:7823 */     ctx->hl = 0x0001;
    ctx->pc = 0x7826;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,DE */
pc_7826:
    /* 15:7826 */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x7827;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),A */
pc_7827:
    /* 15:7827 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7828;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_7828:
    /* 15:7828 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x7829;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),C */
pc_7829:
    /* 15:7829 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->c);
    gb_tick(ctx, 1);
    ctx->pc = 0x782a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_782a:
    /* INC HL */
    /* 15:782a */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x782b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),B */
pc_782b:
    /* 15:782b */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->b);
    gb_tick(ctx, 1);
    ctx->pc = 0x782c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET */
pc_782c:
    /* 15:782c */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_15_782d:
    /* LD HL,$000e */
    /* 15:782d */     ctx->hl = 0x000e;
    ctx->pc = 0x7830;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,DE */
pc_7830:
    /* 15:7830 */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x7831;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB A */
pc_7831:
    /* 15:7831 */     gb_sub8(ctx, ctx->a);
    ctx->pc = 0x7832;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_7832; /* fallthrough */
loc_15_782e:
    /* LD C,$00 */
    /* 15:782e */     ctx->c = 0x00;
    ctx->pc = 0x7830;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,DE */
    /* 15:7830 */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x7831;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB A */
    /* 15:7831 */     gb_sub8(ctx, ctx->a);
    ctx->pc = 0x7832;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_7832:
    /* CP (HL) */
    /* 15:7832 */     gb_tick(ctx, 7);
    gb_cp8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x7833;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,5 */
pc_7833:
    /* 15:7833 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x783a, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_783a;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7835, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_7835; /* fallthrough */
loc_15_7834:
    /* DEC B */
    /* 15:7834 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x7835;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_7835:
    /* DEC (HL) */
    /* 15:7835 */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_dec8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x7836;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_7836:
    /* 15:7836 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x7837;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP (HL) */
pc_7837:
    /* 15:7837 */     gb_tick(ctx, 7);
    gb_cp8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x7838;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR Z,2 */
pc_7838:
    /* 15:7838 */     if (ctx->f_z) {
        gbrt_timed_jump(ctx, 0x783c, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_783c;
    } /* Z */
    gbrt_timed_jump(ctx, 0x783a, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_783a:
    /* DEC (HL) */
    /* 15:783a */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_dec8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x783b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET */
pc_783b:
    /* 15:783b */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_15_783c:
    /* LD BC,$784b */
    /* 15:783c */     ctx->bc = 0x784b;
    ctx->pc = 0x783f;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_783f; /* fallthrough */
loc_15_783d:
    /* LD C,E */
    /* 15:783d */     ctx->c = ctx->e;
    ctx->pc = 0x783e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_783e:
    /* LD A,B */
    /* 15:783e */     ctx->a = ctx->b;
    ctx->pc = 0x783f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_783f:
    /* CALL $246b */
    /* 15:783f */     gbrt_timed_call(ctx, 0x246b, 0x7842);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_246b(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_15_7842; /* fallthrough */
loc_15_7840:
    /* LD L,E */
    /* 15:7840 */     ctx->l = ctx->e;
    ctx->pc = 0x7841;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC H */
pc_7841:
    /* 15:7841 */     ctx->h = gb_inc8(ctx, ctx->h);
    ctx->pc = 0x7842;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_7842:
    /* LD HL,$0001 */
    /* 15:7842 */     ctx->hl = 0x0001;
    ctx->pc = 0x7845;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_7845:
    /* ADD HL,DE */
    /* 15:7845 */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x7846;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),A */
pc_7846:
    /* 15:7846 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7847;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_7847:
    /* 15:7847 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x7848;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),C */
pc_7848:
    /* 15:7848 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->c);
    gb_tick(ctx, 1);
    ctx->pc = 0x7849;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_7849:
    /* 15:7849 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x784a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),B */
pc_784a:
    /* 15:784a */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->b);
    gb_tick(ctx, 1);
    ctx->pc = 0x784b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_784b:
    /* LD HL,$0010 */
    /* 15:784b */     ctx->hl = 0x0010;
    ctx->pc = 0x784e;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,DE */
pc_784e:
    /* 15:784e */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x784f;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_784f:
    /* LD A,(HL) */
    /* 15:784f */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x7850;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC A */
pc_7850:
    /* 15:7850 */     ctx->a = gb_inc8(ctx, ctx->a);
    ctx->pc = 0x7851;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$0010 */
pc_7851:
    /* 15:7851 */     ctx->hl = 0x0010;
    ctx->pc = 0x7854;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,DE */
pc_7854:
    /* 15:7854 */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x7855;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_7855:
    /* LD (HL),A */
    /* 15:7855 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7856;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $04 */
pc_7856:
    /* 15:7856 */     gb_cp8(ctx, 0x04);
    ctx->pc = 0x7858;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP C,$77af */
pc_7858:
    /* 15:7858 */     if (ctx->f_c) {
        gbrt_timed_jump(ctx, 0x77af, 16);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_77af;
    } /* C */
    gbrt_timed_jump(ctx, 0x785b, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_785b:
    /* PUSH DE */
    /* 15:785b */     gbrt_timed_push16(ctx, ctx->de);
    ctx->pc = 0x785c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH AF */
pc_785c:
    /* 15:785c */     gb_pack_flags(ctx); gbrt_timed_push16(ctx, ctx->af & 0xFFF0);
    ctx->pc = 0x785d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,$00 */
pc_785d:
    /* 15:785d */     ctx->a = 0x00;
    ctx->pc = 0x785f;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_785f:
    /* LDH ($FF00+$4f),A */
    /* 15:785f */     gb_tick(ctx, 11);
    gb_write8(ctx, GB_IO_BASE + 0x4f, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7861;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* POP AF */
pc_7861:
    /* 15:7861 */     ctx->af = gbrt_timed_pop16(ctx) & 0xFFF0; gb_unpack_flags(ctx);
    ctx->pc = 0x7862;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$8100 */
pc_7862:
    /* 15:7862 */     ctx->hl = GB_VRAM_BASE + 0x0100;
    ctx->pc = 0x7865;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB A */
pc_7865:
    /* 15:7865 */     gb_sub8(ctx, ctx->a);
    ctx->pc = 0x7866;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,$60 */
pc_7866:
    /* 15:7866 */     ctx->b = 0x60;
    ctx->pc = 0x7868;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_7868:
    /* LD C,$10 */
    /* 15:7868 */     ctx->c = 0x10;
    ctx->pc = 0x786a;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_786a:
    /* EI */
    /* 15:786a */     ctx->ime_pending = 1;
    ctx->pc = 0x786b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DI */
pc_786b:
    /* 15:786b */     ctx->ime = 0; ctx->ime_pending = 0; /* Also cancel pending EI */
    ctx->pc = 0x786c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH A,($FF00+$41) */
pc_786c:
    /* 15:786c */     gb_tick(ctx, 11);
    ctx->a = gb_read8(ctx, GB_IO_STAT);
    gb_tick(ctx, 1);
    ctx->pc = 0x786e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND $02 */
pc_786e:
    /* 15:786e */     gb_and8(ctx, 0x02);
    ctx->pc = 0x7870;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-8 */
pc_7870:
    /* 15:7870 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x786a, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_786a;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7872, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_7872; /* fallthrough */
loc_15_786f:
    /* LD (BC),A */
    /* 15:786f */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7870;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-8 */
    /* 15:7870 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x786a, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_786a;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7872, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_7872:
    /* LD (HL+),A */
    /* 15:7872 */     gbrt_timed_hl_write_auto(ctx, ctx->a, 1);
    ctx->pc = 0x7873;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC C */
pc_7873:
    /* 15:7873 */     ctx->c = gb_dec8(ctx, ctx->c);
    ctx->pc = 0x7874;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-12 */
pc_7874:
    /* 15:7874 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x786a, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_786a;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7876, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_7876:
    /* DEC B */
    /* 15:7876 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x7877;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-17 */
pc_7877:
    /* 15:7877 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7868, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_7868;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7879, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_7879:
    /* EI */
    /* 15:7879 */     ctx->ime_pending = 1;
    ctx->pc = 0x787a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* POP DE */
pc_787a:
    /* 15:787a */     ctx->de = gbrt_timed_pop16(ctx);
    ctx->pc = 0x787b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$788b */
pc_787b:
    /* 15:787b */     ctx->bc = 0x788b;
    ctx->pc = 0x787e;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL $246b */
pc_787e:
    /* 15:787e */     gbrt_timed_call(ctx, 0x246b, 0x7881);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_246b(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_15_7881:
    /* LD HL,$0001 */
    /* 15:7881 */     ctx->hl = 0x0001;
    ctx->pc = 0x7884;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,DE */
pc_7884:
    /* 15:7884 */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x7885;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),A */
pc_7885:
    /* 15:7885 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7886;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_7886:
    /* 15:7886 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x7887;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),C */
pc_7887:
    /* 15:7887 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->c);
    gb_tick(ctx, 1);
    ctx->pc = 0x7888;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_7888:
    /* 15:7888 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x7889;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),B */
pc_7889:
    /* 15:7889 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->b);
    gb_tick(ctx, 1);
    ctx->pc = 0x788a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET */
pc_788a:
    /* 15:788a */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_15_77a9(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_77af(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_77b0(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_77b2(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_77d5(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_77e6(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_77ea(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_77f6(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_77fa(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_77fd(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_77ff(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_7800(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_7801(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_7803(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_7804(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_7806(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_7807(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_7808(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_780e(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_780f(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_7815(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_7818(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_7819(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_7820(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_7821(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_7822(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_782a(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_782d(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_782e(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_7832(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_7834(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_783d(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_783e(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_783f(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_7840(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_7845(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_784b(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_784f(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_7855(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_785f(GBContext* ctx) {
    body_15_77a9(ctx);
}

void func_15_786f(GBContext* ctx) {
    body_15_77a9(ctx);
}

/* Shared body at 15:788b */
static void body_15_788b(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x788b: goto loc_15_788b;
        case 0x788c: goto pc_788c;
        case 0x788d: goto pc_788d;
        case 0x788f: goto pc_788f;
        case 0x7892: goto loc_15_7892;
        case 0x7893: goto pc_7893;
        case 0x7896: goto pc_7896;
        case 0x7898: goto pc_7898;
        case 0x789a: goto pc_789a;
        case 0x789c: goto loc_15_789c;
        case 0x789d: goto loc_15_789d;
        case 0x789e: goto pc_789e;
        case 0x789f: goto loc_15_789f;
        case 0x78a0: goto pc_78a0;
        case 0x78a1: goto pc_78a1;
        case 0x78a2: goto pc_78a2;
        case 0x78a3: goto pc_78a3;
        case 0x78a5: goto pc_78a5;
        case 0x78a6: goto pc_78a6;
        case 0x78a8: goto pc_78a8;
        case 0x78a9: goto pc_78a9;
        case 0x78aa: goto pc_78aa;
        case 0x78ab: goto pc_78ab;
        case 0x78ac: goto pc_78ac;
        case 0x78ad: goto pc_78ad;
        case 0x78af: goto loc_15_78af;
        case 0x78b1: goto pc_78b1;
        case 0x78b3: goto pc_78b3;
        case 0x78b5: goto loc_15_78b5;
        case 0x78b7: goto pc_78b7;
        case 0x78b8: goto pc_78b8;
        case 0x78b9: goto pc_78b9;
        case 0x78ba: goto pc_78ba;
        case 0x78bb: goto pc_78bb;
        case 0x78bc: goto pc_78bc;
        case 0x78be: goto pc_78be;
        case 0x78bf: goto pc_78bf;
        case 0x78c0: goto loc_15_78c0;
        case 0x78c1: goto pc_78c1;
        case 0x78c2: goto loc_15_78c2;
        case 0x78c3: goto pc_78c3;
        case 0x78c4: goto pc_78c4;
        case 0x78c5: goto pc_78c5;
        case 0x78c6: goto pc_78c6;
        case 0x78c8: goto loc_15_78c8;
        case 0x78c9: goto loc_15_78c9;
        case 0x78ca: goto pc_78ca;
        case 0x78cb: goto loc_15_78cb;
        case 0x78cc: goto loc_15_78cc;
        case 0x78cd: goto loc_15_78cd;
        case 0x78ce: goto loc_15_78ce;
        case 0x78d0: goto pc_78d0;
        case 0x78d1: goto pc_78d1;
        case 0x78d2: goto pc_78d2;
        case 0x78d3: goto pc_78d3;
        case 0x78d4: goto pc_78d4;
        case 0x78d5: goto pc_78d5;
        case 0x78d7: goto pc_78d7;
        case 0x78d8: goto pc_78d8;
        case 0x78da: goto pc_78da;
        case 0x78db: goto loc_15_78db;
        case 0x78dc: goto pc_78dc;
        case 0x78dd: goto pc_78dd;
        case 0x78de: goto pc_78de;
        case 0x78df: goto pc_78df;
        case 0x78e1: goto loc_15_78e1;
        case 0x78e4: goto pc_78e4;
        case 0x78e6: goto pc_78e6;
        case 0x78e9: goto pc_78e9;
        case 0x78ea: goto pc_78ea;
        case 0x78ed: goto pc_78ed;
        case 0x78f0: goto loc_15_78f0;
        case 0x78f3: goto pc_78f3;
        case 0x78f4: goto pc_78f4;
        case 0x78f5: goto pc_78f5;
        case 0x78f6: goto pc_78f6;
        case 0x78f7: goto pc_78f7;
        case 0x78f8: goto pc_78f8;
        case 0x78f9: goto pc_78f9;
        default: break;
    }

loc_15_788b:
    /* PUSH DE */
    /* 15:788b */     gbrt_timed_push16(ctx, ctx->de);
    ctx->pc = 0x788c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH AF */
pc_788c:
    /* 15:788c */     gb_pack_flags(ctx); gbrt_timed_push16(ctx, ctx->af & 0xFFF0);
    ctx->pc = 0x788d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,$01 */
pc_788d:
    /* 15:788d */     ctx->a = 0x01;
    ctx->pc = 0x788f;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL $262d */
pc_788f:
    /* 15:788f */     gbrt_timed_call(ctx, 0x262d, 0x7892);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_262d(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_15_7892:
    /* POP AF */
    /* 15:7892 */     ctx->af = gbrt_timed_pop16(ctx) & 0xFFF0; gb_unpack_flags(ctx);
    ctx->pc = 0x7893;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD HL,$d000 */
pc_7893:
    /* 15:7893 */     ctx->hl = GB_WRAMX_BASE;
    ctx->pc = 0x7896;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,$10 */
pc_7896:
    /* 15:7896 */     ctx->d = 0x10;
    ctx->pc = 0x7898;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,$b0 */
pc_7898:
    /* 15:7898 */     ctx->b = 0xb0;
    ctx->pc = 0x789a;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,$0a */
pc_789a:
    /* 15:789a */     ctx->c = 0x0a;
    ctx->pc = 0x789c;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_789c:
    /* LD (HL),$28 */
    /* 15:789c */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x28);
    gb_tick(ctx, 1);
    ctx->pc = 0x789e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_789e:
    /* 15:789e */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x789f;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_789f; /* fallthrough */
loc_15_789d:
    /* JR Z,35 */
    /* 15:789d */     if (ctx->f_z) {
        gbrt_timed_jump(ctx, 0x78c2, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_78c2;
    } /* Z */
    gbrt_timed_jump(ctx, 0x789f, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_789f:
    /* LD (HL),B */
    /* 15:789f */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->b);
    gb_tick(ctx, 1);
    ctx->pc = 0x78a0;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_78a0:
    /* 15:78a0 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x78a1;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),D */
pc_78a1:
    /* 15:78a1 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x78a2;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_78a2:
    /* 15:78a2 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x78a3;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$00 */
pc_78a3:
    /* 15:78a3 */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x78a5;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_78a5:
    /* 15:78a5 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x78a6;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,$08 */
pc_78a6:
    /* 15:78a6 */     ctx->a = 0x08;
    ctx->pc = 0x78a8;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,B */
pc_78a8:
    /* 15:78a8 */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x78a9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,A */
pc_78a9:
    /* 15:78a9 */     ctx->b = ctx->a;
    ctx->pc = 0x78aa;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_78aa:
    /* 15:78aa */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x78ab;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_78ab:
    /* 15:78ab */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x78ac;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC C */
pc_78ac:
    /* 15:78ac */     ctx->c = gb_dec8(ctx, ctx->c);
    ctx->pc = 0x78ad;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-19 */
pc_78ad:
    /* 15:78ad */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x789c, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_789c;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x78af, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_78af:
    /* LD D,$30 */
    /* 15:78af */     ctx->d = 0x30;
    ctx->pc = 0x78b1;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,$b0 */
pc_78b1:
    /* 15:78b1 */     ctx->b = 0xb0;
    ctx->pc = 0x78b3;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,$0a */
pc_78b3:
    /* 15:78b3 */     ctx->c = 0x0a;
    ctx->pc = 0x78b5;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_78b5:
    /* LD (HL),$38 */
    /* 15:78b5 */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x38);
    gb_tick(ctx, 1);
    ctx->pc = 0x78b7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_78b7:
    /* 15:78b7 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x78b8;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),B */
pc_78b8:
    /* 15:78b8 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->b);
    gb_tick(ctx, 1);
    ctx->pc = 0x78b9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_78b9:
    /* 15:78b9 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x78ba;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),D */
pc_78ba:
    /* 15:78ba */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x78bb;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_78bb:
    /* 15:78bb */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x78bc;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$00 */
pc_78bc:
    /* 15:78bc */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x78be;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_78be:
    /* 15:78be */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x78bf;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,$08 */
pc_78bf:
    /* 15:78bf */     ctx->a = 0x08;
    ctx->pc = 0x78c1;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,B */
pc_78c1:
    /* 15:78c1 */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x78c2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_78c2; /* fallthrough */
loc_15_78c0:
    /* LD ($4780),SP */
    /* 15:78c0 */     gb_write16(ctx, 0x4780, ctx->sp);
    ctx->pc = 0x78c3;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_78c3:
    /* 15:78c3 */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x78c4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_78c4:
    /* 15:78c4 */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x78c5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC C */
pc_78c5:
    /* 15:78c5 */     ctx->c = gb_dec8(ctx, ctx->c);
    ctx->pc = 0x78c6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-19 */
pc_78c6:
    /* 15:78c6 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x78b5, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_78b5;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x78c8, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_78c8; /* fallthrough */
loc_15_78c2:
    /* LD B,A */
    /* 15:78c2 */     ctx->b = ctx->a;
    ctx->pc = 0x78c3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
    /* 15:78c3 */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x78c4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
    /* 15:78c4 */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x78c5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC C */
    /* 15:78c5 */     ctx->c = gb_dec8(ctx, ctx->c);
    ctx->pc = 0x78c6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-19 */
    /* 15:78c6 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x78b5, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_78b5;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x78c8, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_78c8:
    /* LD D,$50 */
    /* 15:78c8 */     ctx->d = 0x50;
    ctx->pc = 0x78ca;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,$b0 */
pc_78ca:
    /* 15:78ca */     ctx->b = 0xb0;
    ctx->pc = 0x78cc;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_78cc; /* fallthrough */
loc_15_78c9:
    /* LD D,B */
    /* 15:78c9 */     ctx->d = ctx->b;
    ctx->pc = 0x78ca;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,$b0 */
    /* 15:78ca */     ctx->b = 0xb0;
    ctx->pc = 0x78cc;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_78cc; /* fallthrough */
loc_15_78cb:
    /* OR B */
    /* 15:78cb */     gb_or8(ctx, ctx->b);
    ctx->pc = 0x78cc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_78cc:
    /* LD C,$0a */
    /* 15:78cc */     ctx->c = 0x0a;
    ctx->pc = 0x78ce;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_15_78ce; /* fallthrough */
loc_15_78cd:
    /* LD A,(BC) */
    /* 15:78cd */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->bc);
    gb_tick(ctx, 1);
    ctx->pc = 0x78ce;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_78ce:
    /* LD (HL),$48 */
    /* 15:78ce */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x48);
    gb_tick(ctx, 1);
    ctx->pc = 0x78d0;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_78d0:
    /* 15:78d0 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x78d1;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),B */
pc_78d1:
    /* 15:78d1 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->b);
    gb_tick(ctx, 1);
    ctx->pc = 0x78d2;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_78d2:
    /* 15:78d2 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x78d3;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),D */
pc_78d3:
    /* 15:78d3 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x78d4;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_78d4:
    /* 15:78d4 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x78d5;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),$00 */
pc_78d5:
    /* 15:78d5 */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x78d7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_78d7:
    /* 15:78d7 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x78d8;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,$08 */
pc_78d8:
    /* 15:78d8 */     ctx->a = 0x08;
    ctx->pc = 0x78da;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,B */
pc_78da:
    /* 15:78da */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x78db;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_78db:
    /* LD B,A */
    /* 15:78db */     ctx->b = ctx->a;
    ctx->pc = 0x78dc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_78dc:
    /* 15:78dc */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x78dd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_78dd:
    /* 15:78dd */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x78de;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC C */
pc_78de:
    /* 15:78de */     ctx->c = gb_dec8(ctx, ctx->c);
    ctx->pc = 0x78df;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-19 */
pc_78df:
    /* 15:78df */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x78ce, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_15_78ce;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x78e1, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_15_78e1:
    /* LD A,($c2c5) */
    /* 15:78e1 */     gb_tick(ctx, 15);
    ctx->a = gb_read8(ctx, GB_WRAM0_BASE + 0x02c5);
    gb_tick(ctx, 1);
    ctx->pc = 0x78e4;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* OR $02 */
pc_78e4:
    /* 15:78e4 */     gb_or8(ctx, 0x02);
    ctx->pc = 0x78e6;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($c2c5),A */
pc_78e6:
    /* 15:78e6 */     gb_tick(ctx, 15);
    gb_write8(ctx, GB_WRAM0_BASE + 0x02c5, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x78e9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* POP DE */
pc_78e9:
    /* 15:78e9 */     ctx->de = gbrt_timed_pop16(ctx);
    ctx->pc = 0x78ea;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$78fa */
pc_78ea:
    /* 15:78ea */     ctx->bc = 0x78fa;
    ctx->pc = 0x78ed;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL $246b */
pc_78ed:
    /* 15:78ed */     gbrt_timed_call(ctx, 0x246b, 0x78f0);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_246b(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_15_78f0:
    /* LD HL,$0001 */
    /* 15:78f0 */     ctx->hl = 0x0001;
    ctx->pc = 0x78f3;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,DE */
pc_78f3:
    /* 15:78f3 */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x78f4;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),A */
pc_78f4:
    /* 15:78f4 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x78f5;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_78f5:
    /* 15:78f5 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x78f6;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),C */
pc_78f6:
    /* 15:78f6 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->c);
    gb_tick(ctx, 1);
    ctx->pc = 0x78f7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_78f7:
    /* 15:78f7 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x78f8;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),B */
pc_78f8:
    /* 15:78f8 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->b);
    gb_tick(ctx, 1);
    ctx->pc = 0x78f9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET */
pc_78f9:
    /* 15:78f9 */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_15_788b(GBContext* ctx) {
    body_15_788b(ctx);
}

void func_15_789d(GBContext* ctx) {
    body_15_788b(ctx);
}

void func_15_78c0(GBContext* ctx) {
    body_15_788b(ctx);
}

void func_15_78c2(GBContext* ctx) {
    body_15_788b(ctx);
}

void func_15_78c8(GBContext* ctx) {
    body_15_788b(ctx);
}

void func_15_78c9(GBContext* ctx) {
    body_15_788b(ctx);
}

void func_15_78cb(GBContext* ctx) {
    body_15_788b(ctx);
}

void func_15_78cc(GBContext* ctx) {
    body_15_788b(ctx);
}

void func_15_78cd(GBContext* ctx) {
    body_15_788b(ctx);
}

void func_15_78ce(GBContext* ctx) {
    body_15_788b(ctx);
}

void func_15_78db(GBContext* ctx) {
    body_15_788b(ctx);
}

/* Shared body at 15:78f1 */
static void body_15_78f1(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x78f1: goto loc_15_78f1;
        case 0x78f4: goto pc_78f4;
        case 0x78f5: goto pc_78f5;
        case 0x78f6: goto pc_78f6;
        case 0x78f7: goto pc_78f7;
        case 0x78f8: goto pc_78f8;
        case 0x78f9: goto pc_78f9;
        default: break;
    }

loc_15_78f1:
    /* LD BC,$1900 */
    /* 15:78f1 */     ctx->bc = 0x1900;
    ctx->pc = 0x78f4;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),A */
pc_78f4:
    /* 15:78f4 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x78f5;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_78f5:
    /* 15:78f5 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x78f6;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),C */
pc_78f6:
    /* 15:78f6 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->c);
    gb_tick(ctx, 1);
    ctx->pc = 0x78f7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC HL */
pc_78f7:
    /* 15:78f7 */     gbrt_timed_inc16(ctx, &ctx->hl);
    ctx->pc = 0x78f8;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),B */
pc_78f8:
    /* 15:78f8 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->b);
    gb_tick(ctx, 1);
    ctx->pc = 0x78f9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET */
pc_78f9:
    /* 15:78f9 */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_15_78f1(GBContext* ctx) {
    body_15_78f1(ctx);
}

/* Shared body at 15:78fa */
static void body_15_78fa(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_15_78fa:
    /* JP $24f6 */
    /* 15:78fa */     gbrt_timed_jump(ctx, 0x24f6, 16);
    if (ctx->single_step_mode) return;
    func_24f6(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_15_78fa(GBContext* ctx) {
    body_15_78fa(ctx);
}

