/* Generated by gbrecomp from Lufia - The Legend Returns (USA) */
#include "Lufia___The_Legend_Returns__USA__internal.h"

/* Shared body at 77:4741 */
static void body_77_4741(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4741: goto loc_77_4741;
        case 0x4742: goto loc_77_4742;
        case 0x4743: goto pc_4743;
        case 0x4744: goto pc_4744;
        case 0x4745: goto loc_77_4745;
        case 0x4747: goto loc_77_4747;
        case 0x4748: goto pc_4748;
        case 0x4749: goto pc_4749;
        case 0x474a: goto pc_474a;
        case 0x474b: goto loc_77_474b;
        case 0x474c: goto pc_474c;
        case 0x474f: goto pc_474f;
        case 0x4750: goto pc_4750;
        case 0x4751: goto pc_4751;
        case 0x4752: goto pc_4752;
        case 0x4753: goto pc_4753;
        case 0x4754: goto pc_4754;
        case 0x4757: goto pc_4757;
        case 0x4758: goto pc_4758;
        case 0x4759: goto pc_4759;
        case 0x475a: goto loc_77_475a;
        case 0x475b: goto pc_475b;
        case 0x475e: goto pc_475e;
        case 0x475f: goto pc_475f;
        case 0x4760: goto loc_77_4760;
        case 0x4761: goto pc_4761;
        case 0x4762: goto pc_4762;
        case 0x4763: goto pc_4763;
        case 0x4766: goto pc_4766;
        case 0x4767: goto pc_4767;
        case 0x4768: goto pc_4768;
        case 0x4769: goto loc_77_4769;
        case 0x476a: goto pc_476a;
        case 0x476d: goto pc_476d;
        case 0x476e: goto pc_476e;
        case 0x476f: goto pc_476f;
        case 0x4770: goto loc_77_4770;
        case 0x4771: goto pc_4771;
        case 0x4772: goto pc_4772;
        case 0x4775: goto pc_4775;
        case 0x4776: goto pc_4776;
        case 0x4777: goto pc_4777;
        case 0x4778: goto loc_77_4778;
        case 0x4779: goto pc_4779;
        case 0x477c: goto pc_477c;
        case 0x477d: goto pc_477d;
        case 0x477e: goto loc_77_477e;
        case 0x477f: goto loc_77_477f;
        case 0x4780: goto loc_77_4780;
        case 0x4781: goto pc_4781;
        case 0x4784: goto pc_4784;
        case 0x4785: goto pc_4785;
        case 0x4786: goto pc_4786;
        case 0x4787: goto loc_77_4787;
        case 0x4788: goto pc_4788;
        case 0x478b: goto pc_478b;
        case 0x478c: goto pc_478c;
        case 0x478d: goto pc_478d;
        case 0x478e: goto pc_478e;
        case 0x478f: goto pc_478f;
        case 0x4790: goto pc_4790;
        case 0x4793: goto pc_4793;
        case 0x4794: goto pc_4794;
        case 0x4795: goto pc_4795;
        case 0x4796: goto pc_4796;
        case 0x4797: goto pc_4797;
        case 0x479a: goto pc_479a;
        case 0x479b: goto pc_479b;
        case 0x479c: goto pc_479c;
        case 0x479d: goto pc_479d;
        case 0x479e: goto pc_479e;
        case 0x479f: goto pc_479f;
        case 0x47a2: goto pc_47a2;
        case 0x47a3: goto pc_47a3;
        case 0x47a4: goto pc_47a4;
        case 0x47a5: goto pc_47a5;
        case 0x47a6: goto pc_47a6;
        case 0x47a9: goto pc_47a9;
        case 0x47aa: goto pc_47aa;
        case 0x47ab: goto pc_47ab;
        case 0x47ac: goto pc_47ac;
        case 0x47ad: goto pc_47ad;
        case 0x47ae: goto pc_47ae;
        case 0x47b1: goto pc_47b1;
        case 0x47b2: goto pc_47b2;
        case 0x47b3: goto pc_47b3;
        case 0x47b4: goto pc_47b4;
        case 0x47b5: goto pc_47b5;
        case 0x47b8: goto pc_47b8;
        case 0x47b9: goto pc_47b9;
        case 0x47ba: goto pc_47ba;
        case 0x47bb: goto pc_47bb;
        case 0x47be: goto pc_47be;
        case 0x47c0: goto pc_47c0;
        case 0x47c1: goto pc_47c1;
        case 0x47c2: goto pc_47c2;
        case 0x47c5: goto pc_47c5;
        case 0x47c6: goto pc_47c6;
        case 0x47c9: goto pc_47c9;
        case 0x47ca: goto pc_47ca;
        case 0x47cd: goto pc_47cd;
        case 0x47cf: goto pc_47cf;
        case 0x47d0: goto pc_47d0;
        case 0x47d1: goto pc_47d1;
        case 0x47d4: goto pc_47d4;
        case 0x47d5: goto pc_47d5;
        case 0x47d8: goto pc_47d8;
        case 0x47d9: goto pc_47d9;
        case 0x47dc: goto pc_47dc;
        case 0x47de: goto pc_47de;
        case 0x47df: goto pc_47df;
        case 0x47e0: goto pc_47e0;
        case 0x47e3: goto pc_47e3;
        case 0x47e4: goto pc_47e4;
        case 0x47e7: goto pc_47e7;
        case 0x47e8: goto pc_47e8;
        case 0x47eb: goto pc_47eb;
        case 0x47ed: goto pc_47ed;
        case 0x47ee: goto pc_47ee;
        case 0x47ef: goto pc_47ef;
        case 0x47f0: goto pc_47f0;
        case 0x47f1: goto pc_47f1;
        case 0x47f4: goto pc_47f4;
        case 0x47f5: goto pc_47f5;
        case 0x47f6: goto pc_47f6;
        case 0x47f7: goto pc_47f7;
        case 0x47fa: goto pc_47fa;
        case 0x47fc: goto pc_47fc;
        case 0x47fd: goto pc_47fd;
        case 0x47fe: goto pc_47fe;
        case 0x47ff: goto pc_47ff;
        case 0x4800: goto pc_4800;
        case 0x4803: goto pc_4803;
        case 0x4804: goto pc_4804;
        case 0x4805: goto pc_4805;
        case 0x4806: goto pc_4806;
        case 0x4809: goto pc_4809;
        case 0x480b: goto pc_480b;
        case 0x480c: goto pc_480c;
        case 0x480d: goto pc_480d;
        case 0x480e: goto pc_480e;
        case 0x480f: goto pc_480f;
        case 0x4812: goto pc_4812;
        case 0x4813: goto pc_4813;
        case 0x4814: goto pc_4814;
        case 0x4815: goto pc_4815;
        case 0x4816: goto pc_4816;
        case 0x4817: goto pc_4817;
        case 0x481a: goto pc_481a;
        case 0x481b: goto pc_481b;
        case 0x481c: goto pc_481c;
        case 0x481d: goto pc_481d;
        case 0x481e: goto pc_481e;
        case 0x4821: goto pc_4821;
        case 0x4822: goto pc_4822;
        case 0x4823: goto pc_4823;
        case 0x4824: goto pc_4824;
        case 0x4825: goto pc_4825;
        case 0x4826: goto pc_4826;
        case 0x4829: goto pc_4829;
        case 0x482a: goto pc_482a;
        case 0x482b: goto pc_482b;
        case 0x482c: goto pc_482c;
        case 0x482d: goto pc_482d;
        case 0x4830: goto pc_4830;
        case 0x4831: goto pc_4831;
        case 0x4832: goto pc_4832;
        case 0x4833: goto pc_4833;
        case 0x4834: goto pc_4834;
        case 0x4835: goto pc_4835;
        case 0x4838: goto pc_4838;
        case 0x4839: goto pc_4839;
        case 0x483a: goto pc_483a;
        case 0x483b: goto pc_483b;
        case 0x483c: goto pc_483c;
        case 0x483f: goto pc_483f;
        case 0x4840: goto pc_4840;
        case 0x4841: goto pc_4841;
        case 0x4842: goto pc_4842;
        case 0x4843: goto pc_4843;
        case 0x4844: goto pc_4844;
        case 0x4847: goto pc_4847;
        case 0x4848: goto pc_4848;
        case 0x4849: goto pc_4849;
        case 0x484a: goto pc_484a;
        case 0x484b: goto pc_484b;
        case 0x484e: goto pc_484e;
        case 0x484f: goto pc_484f;
        case 0x4850: goto pc_4850;
        case 0x4851: goto pc_4851;
        case 0x4852: goto pc_4852;
        case 0x4853: goto pc_4853;
        case 0x4856: goto pc_4856;
        case 0x4857: goto pc_4857;
        case 0x4858: goto pc_4858;
        case 0x4859: goto pc_4859;
        case 0x485a: goto pc_485a;
        case 0x485d: goto pc_485d;
        case 0x485e: goto pc_485e;
        case 0x485f: goto pc_485f;
        case 0x4860: goto pc_4860;
        case 0x4861: goto pc_4861;
        case 0x4862: goto pc_4862;
        case 0x4865: goto pc_4865;
        case 0x4866: goto pc_4866;
        case 0x4867: goto pc_4867;
        case 0x4868: goto pc_4868;
        case 0x4869: goto pc_4869;
        case 0x486c: goto pc_486c;
        case 0x486d: goto pc_486d;
        case 0x486e: goto pc_486e;
        case 0x486f: goto pc_486f;
        case 0x4870: goto loc_77_4870;
        case 0x4871: goto pc_4871;
        case 0x4874: goto pc_4874;
        case 0x4875: goto pc_4875;
        case 0x4876: goto pc_4876;
        case 0x4877: goto pc_4877;
        case 0x4878: goto pc_4878;
        case 0x487b: goto pc_487b;
        case 0x487c: goto pc_487c;
        case 0x487d: goto pc_487d;
        case 0x487e: goto pc_487e;
        case 0x4880: goto pc_4880;
        case 0x4883: goto pc_4883;
        case 0x4884: goto pc_4884;
        case 0x4885: goto pc_4885;
        case 0x4886: goto pc_4886;
        case 0x4887: goto pc_4887;
        case 0x488a: goto pc_488a;
        case 0x488b: goto pc_488b;
        case 0x488c: goto pc_488c;
        default: break;
    }

loc_77_4741:
    /* LD E,C */
    /* 77:4741 */     ctx->e = ctx->c;
    ctx->pc = 0x4742;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_77_4742:
    /* NOP */
    /* 77:4742 */     /* NOP */
    ctx->pc = 0x4743;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_4743:
    /* 77:4743 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x4744;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_4744:
    /* 77:4744 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x4745;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_77_4745:
    /* LD BC,$6cce */
    /* 77:4745 */     ctx->bc = 0x6cce;
    ctx->pc = 0x4748;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4748:
    /* 77:4748 */     /* NOP */
    ctx->pc = 0x4749;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4749:
    /* 77:4749 */     /* NOP */
    ctx->pc = 0x474a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_474a:
    /* 77:474a */     gbrt_timed_rst(ctx, 0x38, 0x474b);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_77_474b; /* fallthrough */
loc_77_4747:
    /* LD L,H */
    /* 77:4747 */     ctx->l = ctx->h;
    ctx->pc = 0x4748;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
    /* 77:4748 */     /* NOP */
    ctx->pc = 0x4749;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
    /* 77:4749 */     /* NOP */
    ctx->pc = 0x474a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
    /* 77:474a */     gbrt_timed_rst(ctx, 0x38, 0x474b);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_77_474b:
    /* LD L,H */
    /* 77:474b */     ctx->l = ctx->h;
    ctx->pc = 0x474c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$ff00 */
pc_474c:
    /* 77:474c */     ctx->bc = GB_IO_JOYP;
    ctx->pc = 0x474f;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_474f:
    /* 77:474f */     ctx->l = ctx->h;
    ctx->pc = 0x4750;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_4750:
    /* 77:4750 */     ctx->e = ctx->c;
    ctx->pc = 0x4751;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4751:
    /* 77:4751 */     /* NOP */
    ctx->pc = 0x4752;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_4752:
    /* 77:4752 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4753;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_4753:
    /* 77:4753 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x4754;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_4754:
    /* 77:4754 */     ctx->bc = 0x6cce;
    ctx->pc = 0x4757;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4757:
    /* 77:4757 */     /* NOP */
    ctx->pc = 0x4758;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4758:
    /* 77:4758 */     /* NOP */
    ctx->pc = 0x4759;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_4759:
    /* 77:4759 */     gbrt_timed_rst(ctx, 0x38, 0x475a);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_77_475a:
    /* LD L,H */
    /* 77:475a */     ctx->l = ctx->h;
    ctx->pc = 0x475b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$ff00 */
pc_475b:
    /* 77:475b */     ctx->bc = GB_IO_JOYP;
    ctx->pc = 0x475e;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_475e:
    /* 77:475e */     ctx->l = ctx->h;
    ctx->pc = 0x475f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_475f:
    /* 77:475f */     ctx->e = ctx->c;
    ctx->pc = 0x4760;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_77_4760:
    /* NOP */
    /* 77:4760 */     /* NOP */
    ctx->pc = 0x4761;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_4761:
    /* 77:4761 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4762;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_4762:
    /* 77:4762 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x4763;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_4763:
    /* 77:4763 */     ctx->bc = 0x6cce;
    ctx->pc = 0x4766;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4766:
    /* 77:4766 */     /* NOP */
    ctx->pc = 0x4767;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4767:
    /* 77:4767 */     /* NOP */
    ctx->pc = 0x4768;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_4768:
    /* 77:4768 */     gbrt_timed_rst(ctx, 0x38, 0x4769);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_77_4769:
    /* LD L,H */
    /* 77:4769 */     ctx->l = ctx->h;
    ctx->pc = 0x476a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$ff00 */
pc_476a:
    /* 77:476a */     ctx->bc = GB_IO_JOYP;
    ctx->pc = 0x476d;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_476d:
    /* 77:476d */     ctx->l = ctx->h;
    ctx->pc = 0x476e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_476e:
    /* 77:476e */     ctx->e = ctx->c;
    ctx->pc = 0x476f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_476f:
    /* 77:476f */     /* NOP */
    ctx->pc = 0x4770;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_77_4770:
    /* INC BC */
    /* 77:4770 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4771;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_4771:
    /* 77:4771 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x4772;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_4772:
    /* 77:4772 */     ctx->bc = 0x6cce;
    ctx->pc = 0x4775;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4775:
    /* 77:4775 */     /* NOP */
    ctx->pc = 0x4776;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4776:
    /* 77:4776 */     /* NOP */
    ctx->pc = 0x4777;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_4777:
    /* 77:4777 */     gbrt_timed_rst(ctx, 0x38, 0x4778);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_77_4778:
    /* LD L,H */
    /* 77:4778 */     ctx->l = ctx->h;
    ctx->pc = 0x4779;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$ff00 */
pc_4779:
    /* 77:4779 */     ctx->bc = GB_IO_JOYP;
    ctx->pc = 0x477c;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_477c:
    /* 77:477c */     ctx->l = ctx->h;
    ctx->pc = 0x477d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_477d:
    /* 77:477d */     ctx->e = ctx->c;
    ctx->pc = 0x477e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_77_477e:
    /* NOP */
    /* 77:477e */     /* NOP */
    ctx->pc = 0x477f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_77_477f:
    /* LD (BC),A */
    /* 77:477f */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4780;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_77_4780:
    /* SCF */
    /* 77:4780 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x4781;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_4781:
    /* 77:4781 */     ctx->bc = 0x6cce;
    ctx->pc = 0x4784;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4784:
    /* 77:4784 */     /* NOP */
    ctx->pc = 0x4785;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4785:
    /* 77:4785 */     /* NOP */
    ctx->pc = 0x4786;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_4786:
    /* 77:4786 */     gbrt_timed_rst(ctx, 0x38, 0x4787);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_77_4787:
    /* LD L,H */
    /* 77:4787 */     ctx->l = ctx->h;
    ctx->pc = 0x4788;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$ff00 */
pc_4788:
    /* 77:4788 */     ctx->bc = GB_IO_JOYP;
    ctx->pc = 0x478b;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_478b:
    /* 77:478b */     ctx->l = ctx->h;
    ctx->pc = 0x478c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_478c:
    /* 77:478c */     ctx->e = ctx->c;
    ctx->pc = 0x478d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_478d:
    /* 77:478d */     /* NOP */
    ctx->pc = 0x478e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_478e:
    /* 77:478e */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x478f;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_478f:
    /* 77:478f */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x4790;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_4790:
    /* 77:4790 */     ctx->bc = 0x6cce;
    ctx->pc = 0x4793;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4793:
    /* 77:4793 */     /* NOP */
    ctx->pc = 0x4794;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4794:
    /* 77:4794 */     /* NOP */
    ctx->pc = 0x4795;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4795:
    /* 77:4795 */     /* NOP */
    ctx->pc = 0x4796;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_4796:
    /* 77:4796 */     ctx->l = ctx->h;
    ctx->pc = 0x4797;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0000 */
pc_4797:
    /* 77:4797 */     ctx->bc = 0x0000;
    ctx->pc = 0x479a;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_479a:
    /* 77:479a */     ctx->l = ctx->h;
    ctx->pc = 0x479b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_479b:
    /* 77:479b */     ctx->e = ctx->c;
    ctx->pc = 0x479c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_479c:
    /* 77:479c */     /* NOP */
    ctx->pc = 0x479d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_479d:
    /* 77:479d */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x479e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_479e:
    /* 77:479e */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x479f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_479f:
    /* 77:479f */     ctx->bc = 0x6cce;
    ctx->pc = 0x47a2;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47a2:
    /* 77:47a2 */     /* NOP */
    ctx->pc = 0x47a3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47a3:
    /* 77:47a3 */     /* NOP */
    ctx->pc = 0x47a4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47a4:
    /* 77:47a4 */     /* NOP */
    ctx->pc = 0x47a5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_47a5:
    /* 77:47a5 */     ctx->l = ctx->h;
    ctx->pc = 0x47a6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0000 */
pc_47a6:
    /* 77:47a6 */     ctx->bc = 0x0000;
    ctx->pc = 0x47a9;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_47a9:
    /* 77:47a9 */     ctx->l = ctx->h;
    ctx->pc = 0x47aa;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_47aa:
    /* 77:47aa */     ctx->e = ctx->c;
    ctx->pc = 0x47ab;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47ab:
    /* 77:47ab */     /* NOP */
    ctx->pc = 0x47ac;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_47ac:
    /* 77:47ac */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x47ad;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_47ad:
    /* 77:47ad */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x47ae;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_47ae:
    /* 77:47ae */     ctx->bc = 0x6cce;
    ctx->pc = 0x47b1;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47b1:
    /* 77:47b1 */     /* NOP */
    ctx->pc = 0x47b2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47b2:
    /* 77:47b2 */     /* NOP */
    ctx->pc = 0x47b3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47b3:
    /* 77:47b3 */     /* NOP */
    ctx->pc = 0x47b4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_47b4:
    /* 77:47b4 */     ctx->l = ctx->h;
    ctx->pc = 0x47b5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0000 */
pc_47b5:
    /* 77:47b5 */     ctx->bc = 0x0000;
    ctx->pc = 0x47b8;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_47b8:
    /* 77:47b8 */     ctx->l = ctx->h;
    ctx->pc = 0x47b9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_47b9:
    /* 77:47b9 */     ctx->e = ctx->c;
    ctx->pc = 0x47ba;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47ba:
    /* 77:47ba */     /* NOP */
    ctx->pc = 0x47bb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0137 */
pc_47bb:
    /* 77:47bb */     ctx->bc = 0x0137;
    ctx->pc = 0x47be;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,$6c */
pc_47be:
    /* 77:47be */     gb_adc8(ctx, 0x6c);
    ctx->pc = 0x47c0;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47c0:
    /* 77:47c0 */     /* NOP */
    ctx->pc = 0x47c1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47c1:
    /* 77:47c1 */     /* NOP */
    ctx->pc = 0x47c2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$016c */
pc_47c2:
    /* 77:47c2 */     ctx->bc = 0x016c;
    ctx->pc = 0x47c5;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47c5:
    /* 77:47c5 */     /* NOP */
    ctx->pc = 0x47c6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$596c */
pc_47c6:
    /* 77:47c6 */     ctx->bc = 0x596c;
    ctx->pc = 0x47c9;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47c9:
    /* 77:47c9 */     /* NOP */
    ctx->pc = 0x47ca;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0137 */
pc_47ca:
    /* 77:47ca */     ctx->bc = 0x0137;
    ctx->pc = 0x47cd;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,$6c */
pc_47cd:
    /* 77:47cd */     gb_adc8(ctx, 0x6c);
    ctx->pc = 0x47cf;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47cf:
    /* 77:47cf */     /* NOP */
    ctx->pc = 0x47d0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47d0:
    /* 77:47d0 */     /* NOP */
    ctx->pc = 0x47d1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$016c */
pc_47d1:
    /* 77:47d1 */     ctx->bc = 0x016c;
    ctx->pc = 0x47d4;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47d4:
    /* 77:47d4 */     /* NOP */
    ctx->pc = 0x47d5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$596c */
pc_47d5:
    /* 77:47d5 */     ctx->bc = 0x596c;
    ctx->pc = 0x47d8;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47d8:
    /* 77:47d8 */     /* NOP */
    ctx->pc = 0x47d9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0137 */
pc_47d9:
    /* 77:47d9 */     ctx->bc = 0x0137;
    ctx->pc = 0x47dc;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,$6c */
pc_47dc:
    /* 77:47dc */     gb_adc8(ctx, 0x6c);
    ctx->pc = 0x47de;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47de:
    /* 77:47de */     /* NOP */
    ctx->pc = 0x47df;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47df:
    /* 77:47df */     /* NOP */
    ctx->pc = 0x47e0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$016c */
pc_47e0:
    /* 77:47e0 */     ctx->bc = 0x016c;
    ctx->pc = 0x47e3;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47e3:
    /* 77:47e3 */     /* NOP */
    ctx->pc = 0x47e4;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$596c */
pc_47e4:
    /* 77:47e4 */     ctx->bc = 0x596c;
    ctx->pc = 0x47e7;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47e7:
    /* 77:47e7 */     /* NOP */
    ctx->pc = 0x47e8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0137 */
pc_47e8:
    /* 77:47e8 */     ctx->bc = 0x0137;
    ctx->pc = 0x47eb;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,$6c */
pc_47eb:
    /* 77:47eb */     gb_adc8(ctx, 0x6c);
    ctx->pc = 0x47ed;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47ed:
    /* 77:47ed */     /* NOP */
    ctx->pc = 0x47ee;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47ee:
    /* 77:47ee */     /* NOP */
    ctx->pc = 0x47ef;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_47ef:
    /* 77:47ef */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x47f0;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_47f0:
    /* 77:47f0 */     ctx->l = ctx->h;
    ctx->pc = 0x47f1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0200 */
pc_47f1:
    /* 77:47f1 */     ctx->bc = 0x0200;
    ctx->pc = 0x47f4;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_47f4:
    /* 77:47f4 */     ctx->l = ctx->h;
    ctx->pc = 0x47f5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_47f5:
    /* 77:47f5 */     ctx->e = ctx->c;
    ctx->pc = 0x47f6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47f6:
    /* 77:47f6 */     /* NOP */
    ctx->pc = 0x47f7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0137 */
pc_47f7:
    /* 77:47f7 */     ctx->bc = 0x0137;
    ctx->pc = 0x47fa;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,$6c */
pc_47fa:
    /* 77:47fa */     gb_adc8(ctx, 0x6c);
    ctx->pc = 0x47fc;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47fc:
    /* 77:47fc */     /* NOP */
    ctx->pc = 0x47fd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_47fd:
    /* 77:47fd */     /* NOP */
    ctx->pc = 0x47fe;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_47fe:
    /* 77:47fe */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x47ff;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_47ff:
    /* 77:47ff */     ctx->l = ctx->h;
    ctx->pc = 0x4800;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0200 */
pc_4800:
    /* 77:4800 */     ctx->bc = 0x0200;
    ctx->pc = 0x4803;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_4803:
    /* 77:4803 */     ctx->l = ctx->h;
    ctx->pc = 0x4804;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_4804:
    /* 77:4804 */     ctx->e = ctx->c;
    ctx->pc = 0x4805;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4805:
    /* 77:4805 */     /* NOP */
    ctx->pc = 0x4806;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0137 */
pc_4806:
    /* 77:4806 */     ctx->bc = 0x0137;
    ctx->pc = 0x4809;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,$6c */
pc_4809:
    /* 77:4809 */     gb_adc8(ctx, 0x6c);
    ctx->pc = 0x480b;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_480b:
    /* 77:480b */     /* NOP */
    ctx->pc = 0x480c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_480c:
    /* 77:480c */     /* NOP */
    ctx->pc = 0x480d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_480d:
    /* 77:480d */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x480e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_480e:
    /* 77:480e */     ctx->l = ctx->h;
    ctx->pc = 0x480f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0200 */
pc_480f:
    /* 77:480f */     ctx->bc = 0x0200;
    ctx->pc = 0x4812;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_4812:
    /* 77:4812 */     ctx->l = ctx->h;
    ctx->pc = 0x4813;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_4813:
    /* 77:4813 */     ctx->e = ctx->c;
    ctx->pc = 0x4814;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4814:
    /* 77:4814 */     /* NOP */
    ctx->pc = 0x4815;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4815:
    /* 77:4815 */     /* NOP */
    ctx->pc = 0x4816;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_4816:
    /* 77:4816 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x4817;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_4817:
    /* 77:4817 */     ctx->bc = 0x6cce;
    ctx->pc = 0x481a;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_481a:
    /* 77:481a */     /* NOP */
    ctx->pc = 0x481b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_481b:
    /* 77:481b */     /* NOP */
    ctx->pc = 0x481c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_481c:
    /* 77:481c */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x481d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_481d:
    /* 77:481d */     ctx->l = ctx->h;
    ctx->pc = 0x481e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0200 */
pc_481e:
    /* 77:481e */     ctx->bc = 0x0200;
    ctx->pc = 0x4821;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_4821:
    /* 77:4821 */     ctx->l = ctx->h;
    ctx->pc = 0x4822;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_4822:
    /* 77:4822 */     ctx->e = ctx->c;
    ctx->pc = 0x4823;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4823:
    /* 77:4823 */     /* NOP */
    ctx->pc = 0x4824;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4824:
    /* 77:4824 */     /* NOP */
    ctx->pc = 0x4825;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_4825:
    /* 77:4825 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x4826;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_4826:
    /* 77:4826 */     ctx->bc = 0x6cce;
    ctx->pc = 0x4829;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4829:
    /* 77:4829 */     /* NOP */
    ctx->pc = 0x482a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_482a:
    /* 77:482a */     /* NOP */
    ctx->pc = 0x482b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_482b:
    /* 77:482b */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x482c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_482c:
    /* 77:482c */     ctx->l = ctx->h;
    ctx->pc = 0x482d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0200 */
pc_482d:
    /* 77:482d */     ctx->bc = 0x0200;
    ctx->pc = 0x4830;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_4830:
    /* 77:4830 */     ctx->l = ctx->h;
    ctx->pc = 0x4831;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_4831:
    /* 77:4831 */     ctx->e = ctx->c;
    ctx->pc = 0x4832;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4832:
    /* 77:4832 */     /* NOP */
    ctx->pc = 0x4833;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4833:
    /* 77:4833 */     /* NOP */
    ctx->pc = 0x4834;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_4834:
    /* 77:4834 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x4835;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_4835:
    /* 77:4835 */     ctx->bc = 0x6cce;
    ctx->pc = 0x4838;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4838:
    /* 77:4838 */     /* NOP */
    ctx->pc = 0x4839;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4839:
    /* 77:4839 */     /* NOP */
    ctx->pc = 0x483a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_483a:
    /* 77:483a */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x483b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_483b:
    /* 77:483b */     ctx->l = ctx->h;
    ctx->pc = 0x483c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0200 */
pc_483c:
    /* 77:483c */     ctx->bc = 0x0200;
    ctx->pc = 0x483f;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_483f:
    /* 77:483f */     ctx->l = ctx->h;
    ctx->pc = 0x4840;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_4840:
    /* 77:4840 */     ctx->e = ctx->c;
    ctx->pc = 0x4841;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4841:
    /* 77:4841 */     /* NOP */
    ctx->pc = 0x4842;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4842:
    /* 77:4842 */     /* NOP */
    ctx->pc = 0x4843;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_4843:
    /* 77:4843 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x4844;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_4844:
    /* 77:4844 */     ctx->bc = 0x6cce;
    ctx->pc = 0x4847;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4847:
    /* 77:4847 */     /* NOP */
    ctx->pc = 0x4848;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4848:
    /* 77:4848 */     /* NOP */
    ctx->pc = 0x4849;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_4849:
    /* 77:4849 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x484a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_484a:
    /* 77:484a */     ctx->l = ctx->h;
    ctx->pc = 0x484b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0200 */
pc_484b:
    /* 77:484b */     ctx->bc = 0x0200;
    ctx->pc = 0x484e;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_484e:
    /* 77:484e */     ctx->l = ctx->h;
    ctx->pc = 0x484f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_484f:
    /* 77:484f */     ctx->e = ctx->c;
    ctx->pc = 0x4850;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4850:
    /* 77:4850 */     /* NOP */
    ctx->pc = 0x4851;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4851:
    /* 77:4851 */     /* NOP */
    ctx->pc = 0x4852;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_4852:
    /* 77:4852 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x4853;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_4853:
    /* 77:4853 */     ctx->bc = 0x6cce;
    ctx->pc = 0x4856;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4856:
    /* 77:4856 */     /* NOP */
    ctx->pc = 0x4857;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4857:
    /* 77:4857 */     /* NOP */
    ctx->pc = 0x4858;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_4858:
    /* 77:4858 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4859;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_4859:
    /* 77:4859 */     ctx->l = ctx->h;
    ctx->pc = 0x485a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0300 */
pc_485a:
    /* 77:485a */     ctx->bc = 0x0300;
    ctx->pc = 0x485d;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_485d:
    /* 77:485d */     ctx->l = ctx->h;
    ctx->pc = 0x485e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_485e:
    /* 77:485e */     ctx->e = ctx->c;
    ctx->pc = 0x485f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_485f:
    /* 77:485f */     /* NOP */
    ctx->pc = 0x4860;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4860:
    /* 77:4860 */     /* NOP */
    ctx->pc = 0x4861;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_4861:
    /* 77:4861 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x4862;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_4862:
    /* 77:4862 */     ctx->bc = 0x6cce;
    ctx->pc = 0x4865;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4865:
    /* 77:4865 */     /* NOP */
    ctx->pc = 0x4866;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4866:
    /* 77:4866 */     /* NOP */
    ctx->pc = 0x4867;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_4867:
    /* 77:4867 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4868;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_4868:
    /* 77:4868 */     ctx->l = ctx->h;
    ctx->pc = 0x4869;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0300 */
pc_4869:
    /* 77:4869 */     ctx->bc = 0x0300;
    ctx->pc = 0x486c;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_486c:
    /* 77:486c */     ctx->l = ctx->h;
    ctx->pc = 0x486d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_486d:
    /* 77:486d */     ctx->e = ctx->c;
    ctx->pc = 0x486e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_486e:
    /* 77:486e */     /* NOP */
    ctx->pc = 0x486f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_486f:
    /* 77:486f */     gbrt_timed_rst(ctx, 0x38, 0x4870);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_77_4870:
    /* SCF */
    /* 77:4870 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x4871;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_4871:
    /* 77:4871 */     ctx->bc = 0x6cce;
    ctx->pc = 0x4874;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4874:
    /* 77:4874 */     /* NOP */
    ctx->pc = 0x4875;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4875:
    /* 77:4875 */     /* NOP */
    ctx->pc = 0x4876;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_4876:
    /* 77:4876 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4877;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_4877:
    /* 77:4877 */     ctx->l = ctx->h;
    ctx->pc = 0x4878;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0300 */
pc_4878:
    /* 77:4878 */     ctx->bc = 0x0300;
    ctx->pc = 0x487b;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_487b:
    /* 77:487b */     ctx->l = ctx->h;
    ctx->pc = 0x487c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_487c:
    /* 77:487c */     ctx->e = ctx->c;
    ctx->pc = 0x487d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_487d:
    /* 77:487d */     /* NOP */
    ctx->pc = 0x487e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $37 */
pc_487e:
    /* 77:487e */     gb_cp8(ctx, 0x37);
    ctx->pc = 0x4880;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_4880:
    /* 77:4880 */     ctx->bc = 0x6cce;
    ctx->pc = 0x4883;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4883:
    /* 77:4883 */     /* NOP */
    ctx->pc = 0x4884;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4884:
    /* 77:4884 */     /* NOP */
    ctx->pc = 0x4885;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_4885:
    /* 77:4885 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x4886;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_4886:
    /* 77:4886 */     ctx->l = ctx->h;
    ctx->pc = 0x4887;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0400 */
pc_4887:
    /* 77:4887 */     ctx->bc = 0x0400;
    ctx->pc = 0x488a;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_488a:
    /* 77:488a */     ctx->l = ctx->h;
    ctx->pc = 0x488b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_488b:
    /* 77:488b */     ctx->e = ctx->c;
    ctx->pc = 0x488c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_488c:
    /* 77:488c */     /* NOP */
    ctx->pc = 0x488d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x488d in bank 119 */
    return;
}

void func_77_4741(GBContext* ctx) {
    body_77_4741(ctx);
}

void func_77_4742(GBContext* ctx) {
    body_77_4741(ctx);
}

void func_77_4745(GBContext* ctx) {
    body_77_4741(ctx);
}

void func_77_4747(GBContext* ctx) {
    body_77_4741(ctx);
}

void func_77_4760(GBContext* ctx) {
    body_77_4741(ctx);
}

void func_77_4770(GBContext* ctx) {
    body_77_4741(ctx);
}

void func_77_477e(GBContext* ctx) {
    body_77_4741(ctx);
}

void func_77_477f(GBContext* ctx) {
    body_77_4741(ctx);
}

void func_77_4780(GBContext* ctx) {
    body_77_4741(ctx);
}

/* Shared body at 77:57cc */
static void body_77_57cc(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_77_57cc:
    /* RET */
    /* 77:57cc */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_77_57cc(GBContext* ctx) {
    body_77_57cc(ctx);
}

