/* Generated by gbrecomp from Lufia - The Legend Returns (USA) */
#include "Lufia___The_Legend_Returns__USA__internal.h"

/* Shared body at 69:4d44 */
static void body_69_4d44(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4d44: goto loc_69_4d44;
        case 0x4d45: goto loc_69_4d45;
        case 0x4d47: goto loc_69_4d47;
        case 0x4d48: goto pc_4d48;
        case 0x4d4b: goto loc_69_4d4b;
        case 0x4d4c: goto pc_4d4c;
        case 0x4d4d: goto pc_4d4d;
        case 0x4d4f: goto loc_69_4d4f;
        case 0x4d50: goto loc_69_4d50;
        case 0x4d51: goto loc_69_4d51;
        case 0x4d52: goto pc_4d52;
        case 0x4d53: goto pc_4d53;
        case 0x4d54: goto pc_4d54;
        case 0x4d55: goto pc_4d55;
        case 0x4d56: goto pc_4d56;
        case 0x4d59: goto pc_4d59;
        case 0x4d5a: goto pc_4d5a;
        case 0x4d5b: goto pc_4d5b;
        case 0x4d5c: goto pc_4d5c;
        default: break;
    }

loc_69_4d44:
    /* LD (BC),A */
    /* 69:4d44 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4d45;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_69_4d45:
    /* ADC A,$1f */
    /* 69:4d45 */     gb_adc8(ctx, 0x1f);
    ctx->pc = 0x4d47;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_69_4d47:
    /* NOP */
    /* 69:4d47 */     /* NOP */
    ctx->pc = 0x4d48;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$1114 */
pc_4d48:
    /* 69:4d48 */     ctx->bc = 0x1114;
    ctx->pc = 0x4d4b;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_69_4d4b:
    /* NOP */
    /* 69:4d4b */     /* NOP */
    ctx->pc = 0x4d4c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4d4c:
    /* 69:4d4c */     /* NOP */
    ctx->pc = 0x4d4d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-4 */
pc_4d4d:
    /* 69:4d4d */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x4d4b, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_69_4d4b;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x4d4f, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_69_4d4f:
    /* ADD HL,BC */
    /* 69:4d4f */     gb_add16(ctx, ctx->bc);
    ctx->pc = 0x4d50;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_69_4d50:
    /* RST $38 */
    /* 69:4d50 */     gbrt_timed_rst(ctx, 0x38, 0x4d51);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_69_4d51:
    /* LD L,H */
    /* 69:4d51 */     ctx->l = ctx->h;
    ctx->pc = 0x4d52;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,E */
pc_4d52:
    /* 69:4d52 */     ctx->d = ctx->e;
    ctx->pc = 0x4d53;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4d53:
    /* 69:4d53 */     /* NOP */
    ctx->pc = 0x4d54;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* EI */
pc_4d54:
    /* 69:4d54 */     ctx->ime_pending = 1;
    ctx->pc = 0x4d55;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_4d55:
    /* 69:4d55 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x4d56;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$4cce */
pc_4d56:
    /* 69:4d56 */     ctx->bc = 0x4cce;
    ctx->pc = 0x4d59;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC DE */
pc_4d59:
    /* 69:4d59 */     gbrt_timed_inc16(ctx, &ctx->de);
    ctx->pc = 0x4d5a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_4d5a:
    /* 69:4d5a */     ctx->l = ctx->h;
    ctx->pc = 0x4d5b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,E */
pc_4d5b:
    /* 69:4d5b */     ctx->d = ctx->e;
    ctx->pc = 0x4d5c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4d5c:
    /* 69:4d5c */     /* NOP */
    ctx->pc = 0x4d5d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x4d5d in bank 105 */
    return;
}

void func_69_4d44(GBContext* ctx) {
    body_69_4d44(ctx);
}

void func_69_4d45(GBContext* ctx) {
    body_69_4d44(ctx);
}

void func_69_4d47(GBContext* ctx) {
    body_69_4d44(ctx);
}

void func_69_4d50(GBContext* ctx) {
    body_69_4d44(ctx);
}

/* Shared body at 69:6e69 */
static void body_69_6e69(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_69_6e69:
    /* RET */
    /* 69:6e69 */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_69_6e69(GBContext* ctx) {
    body_69_6e69(ctx);
}

/* Shared body at 69:79cb */
static void body_69_79cb(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_69_79cb:
    /* RETI */
    /* 69:79cb */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* fallthrough to function */
    func_69_79cc(ctx);
    return;
}

void func_69_79cb(GBContext* ctx) {
    body_69_79cb(ctx);
}

