/* Generated by gbrecomp from Lufia - The Legend Returns (USA) */
#include "Lufia___The_Legend_Returns__USA__internal.h"

/* Shared body at 79:4a00 */
static void body_79_4a00(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_79_4a00:
    /* RET */
    /* 79:4a00 */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_79_4a00(GBContext* ctx) {
    body_79_4a00(ctx);
}

/* Shared body at 79:4be0 */
static void body_79_4be0(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4be0: goto loc_79_4be0;
        case 0x4be1: goto pc_4be1;
        case 0x4be4: goto loc_79_4be4;
        case 0x4be5: goto pc_4be5;
        case 0x4be6: goto pc_4be6;
        case 0x4be7: goto pc_4be7;
        case 0x4be8: goto pc_4be8;
        case 0x4be9: goto pc_4be9;
        case 0x4bea: goto pc_4bea;
        case 0x4beb: goto pc_4beb;
        case 0x4bec: goto pc_4bec;
        case 0x4bee: goto pc_4bee;
        case 0x4bf1: goto pc_4bf1;
        default: break;
    }

loc_79_4be0:
    /* DEC D */
    /* 79:4be0 */     ctx->d = gb_dec8(ctx, ctx->d);
    ctx->pc = 0x4be1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL Z,$7265 */
pc_4be1:
    /* 79:4be1 */     if (ctx->f_z) {
        gbrt_timed_call(ctx, 0x7265, 0x4be4);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        func_79_7265(ctx);
        return;
    } /* Z */
    gbrt_timed_jump(ctx, 0x4be4, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_4be4:
    /* INC BC */
    /* 79:4be4 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4be5;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,L */
pc_4be5:
    /* 79:4be5 */     ctx->b = ctx->l;
    ctx->pc = 0x4be6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,(HL) */
pc_4be6:
    /* 79:4be6 */     gb_tick(ctx, 7);
    ctx->l = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4be7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
pc_4be7:
    /* 79:4be7 */     ctx->h = ctx->l;
    ctx->pc = 0x4be8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),D */
pc_4be8:
    /* 79:4be8 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x4be9;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,A */
pc_4be9:
    /* 79:4be9 */     ctx->h = ctx->a;
    ctx->pc = 0x4bea;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,C */
pc_4bea:
    /* 79:4bea */     ctx->l = ctx->c;
    ctx->pc = 0x4beb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
pc_4beb:
    /* 79:4beb */     ctx->h = ctx->l;
    ctx->pc = 0x4bec;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,$04 */
pc_4bec:
    /* 79:4bec */     ctx->l = 0x04;
    ctx->pc = 0x4bee;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0013 */
pc_4bee:
    /* 79:4bee */     ctx->bc = 0x0013;
    ctx->pc = 0x4bf1;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_4bf1:
    /* 79:4bf1 */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x4bf2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x4bf2 in bank 121 */
    return;
}

void func_79_4be0(GBContext* ctx) {
    body_79_4be0(ctx);
}

/* Shared body at 79:61ea */
static void body_79_61ea(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_79_61ea:
    /* RETI */
    /* 79:61ea */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x61eb in bank 121 */
    return;
}

void func_79_61ea(GBContext* ctx) {
    body_79_61ea(ctx);
}

/* Shared body at 79:67dc */
static void body_79_67dc(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_79_67dc:
    /* JP $0421 */
    /* 79:67dc */     gbrt_timed_jump(ctx, 0x421, 16);
    if (ctx->single_step_mode) return;
    func_0421(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_79_67dc(GBContext* ctx) {
    body_79_67dc(ctx);
}

/* Shared body at 79:6920 */
static void body_79_6920(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x6920: goto loc_79_6920;
        case 0x6922: goto pc_6922;
        default: break;
    }

loc_79_6920:
    /* LD D,$44 */
    /* 79:6920 */     ctx->d = 0x44;
    ctx->pc = 0x6922;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_6922:
    /* 79:6922 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x6923;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x6923 in bank 121 */
    return;
}

void func_79_6920(GBContext* ctx) {
    body_79_6920(ctx);
}

/* Shared body at 79:7e47 */
static void body_79_7e47(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x7e47: goto loc_79_7e47;
        case 0x7e48: goto loc_79_7e48;
        case 0x7e4b: goto pc_7e4b;
        case 0x7e4c: goto pc_7e4c;
        case 0x7e4d: goto pc_7e4d;
        case 0x7e4e: goto loc_79_7e4e;
        case 0x7e4f: goto pc_7e4f;
        case 0x7e52: goto pc_7e52;
        case 0x7e53: goto pc_7e53;
        case 0x7e54: goto loc_79_7e54;
        case 0x7e55: goto loc_79_7e55;
        case 0x7e56: goto pc_7e56;
        case 0x7e57: goto loc_79_7e57;
        case 0x7e59: goto pc_7e59;
        case 0x7e5a: goto pc_7e5a;
        case 0x7e5b: goto pc_7e5b;
        case 0x7e5c: goto loc_79_7e5c;
        case 0x7e5d: goto pc_7e5d;
        case 0x7e5f: goto loc_79_7e5f;
        case 0x7e60: goto pc_7e60;
        case 0x7e61: goto pc_7e61;
        case 0x7e63: goto pc_7e63;
        case 0x7e64: goto pc_7e64;
        case 0x7e65: goto pc_7e65;
        case 0x7e66: goto loc_79_7e66;
        case 0x7e67: goto loc_79_7e67;
        case 0x7e68: goto loc_79_7e68;
        case 0x7e6a: goto pc_7e6a;
        case 0x7e6b: goto loc_79_7e6b;
        case 0x7e6c: goto pc_7e6c;
        case 0x7e6d: goto loc_79_7e6d;
        case 0x7e6e: goto pc_7e6e;
        case 0x7e71: goto pc_7e71;
        case 0x7e72: goto pc_7e72;
        case 0x7e73: goto pc_7e73;
        case 0x7e74: goto loc_79_7e74;
        case 0x7e75: goto pc_7e75;
        case 0x7e78: goto pc_7e78;
        case 0x7e7b: goto pc_7e7b;
        case 0x7e7c: goto pc_7e7c;
        case 0x7e7d: goto pc_7e7d;
        case 0x7e7e: goto pc_7e7e;
        case 0x7e7f: goto pc_7e7f;
        case 0x7e80: goto pc_7e80;
        case 0x7e81: goto pc_7e81;
        case 0x7e82: goto pc_7e82;
        case 0x7e83: goto pc_7e83;
        case 0x7e84: goto pc_7e84;
        case 0x7e86: goto loc_79_7e86;
        case 0x7e87: goto pc_7e87;
        case 0x7e88: goto pc_7e88;
        case 0x7e89: goto pc_7e89;
        case 0x7e8a: goto pc_7e8a;
        case 0x7e8b: goto pc_7e8b;
        case 0x7e8c: goto pc_7e8c;
        case 0x7e8d: goto pc_7e8d;
        case 0x7e8e: goto pc_7e8e;
        case 0x7e8f: goto pc_7e8f;
        case 0x7e90: goto pc_7e90;
        case 0x7e91: goto pc_7e91;
        case 0x7e92: goto pc_7e92;
        case 0x7e93: goto pc_7e93;
        case 0x7e94: goto loc_79_7e94;
        case 0x7e95: goto loc_79_7e95;
        case 0x7e96: goto pc_7e96;
        case 0x7e97: goto pc_7e97;
        case 0x7e98: goto pc_7e98;
        case 0x7e99: goto pc_7e99;
        case 0x7e9a: goto pc_7e9a;
        case 0x7e9b: goto pc_7e9b;
        case 0x7e9c: goto pc_7e9c;
        case 0x7e9d: goto pc_7e9d;
        case 0x7e9e: goto pc_7e9e;
        case 0x7e9f: goto pc_7e9f;
        case 0x7ea0: goto pc_7ea0;
        case 0x7ea1: goto pc_7ea1;
        case 0x7ea4: goto pc_7ea4;
        case 0x7ea6: goto pc_7ea6;
        case 0x7ea7: goto pc_7ea7;
        case 0x7ea9: goto pc_7ea9;
        case 0x7eab: goto pc_7eab;
        case 0x7eac: goto pc_7eac;
        case 0x7ead: goto pc_7ead;
        case 0x7eae: goto loc_79_7eae;
        case 0x7eb0: goto pc_7eb0;
        case 0x7eb1: goto pc_7eb1;
        case 0x7eb2: goto pc_7eb2;
        case 0x7eb3: goto pc_7eb3;
        case 0x7eb5: goto pc_7eb5;
        case 0x7eb6: goto pc_7eb6;
        case 0x7eb7: goto pc_7eb7;
        case 0x7eb8: goto pc_7eb8;
        case 0x7eb9: goto loc_79_7eb9;
        case 0x7eba: goto pc_7eba;
        case 0x7ebb: goto pc_7ebb;
        case 0x7ebd: goto loc_79_7ebd;
        case 0x7ebe: goto pc_7ebe;
        case 0x7ebf: goto pc_7ebf;
        case 0x7ec0: goto pc_7ec0;
        case 0x7ec1: goto loc_79_7ec1;
        case 0x7ec2: goto loc_79_7ec2;
        case 0x7ec3: goto loc_79_7ec3;
        case 0x7ec4: goto loc_79_7ec4;
        case 0x7ec5: goto loc_79_7ec5;
        case 0x7ec6: goto pc_7ec6;
        case 0x7ec8: goto pc_7ec8;
        case 0x7ec9: goto loc_79_7ec9;
        case 0x7eca: goto loc_79_7eca;
        case 0x7ecb: goto loc_79_7ecb;
        case 0x7ece: goto pc_7ece;
        case 0x7ecf: goto pc_7ecf;
        case 0x7ed0: goto pc_7ed0;
        case 0x7ed1: goto pc_7ed1;
        case 0x7ed2: goto pc_7ed2;
        case 0x7ed3: goto pc_7ed3;
        case 0x7ed5: goto pc_7ed5;
        case 0x7ed6: goto pc_7ed6;
        case 0x7ed7: goto pc_7ed7;
        case 0x7ed8: goto loc_79_7ed8;
        case 0x7ed9: goto pc_7ed9;
        case 0x7eda: goto pc_7eda;
        case 0x7edb: goto pc_7edb;
        case 0x7edd: goto pc_7edd;
        case 0x7ede: goto pc_7ede;
        case 0x7edf: goto pc_7edf;
        case 0x7ee0: goto pc_7ee0;
        case 0x7ee1: goto loc_79_7ee1;
        case 0x7ee2: goto loc_79_7ee2;
        case 0x7ee3: goto loc_79_7ee3;
        case 0x7ee4: goto loc_79_7ee4;
        case 0x7ee6: goto pc_7ee6;
        case 0x7ee7: goto pc_7ee7;
        case 0x7ee8: goto loc_79_7ee8;
        case 0x7ee9: goto pc_7ee9;
        case 0x7eea: goto pc_7eea;
        case 0x7eeb: goto pc_7eeb;
        case 0x7eec: goto loc_79_7eec;
        case 0x7eed: goto loc_79_7eed;
        case 0x7eee: goto loc_79_7eee;
        case 0x7eef: goto loc_79_7eef;
        case 0x7ef0: goto loc_79_7ef0;
        case 0x7ef1: goto loc_79_7ef1;
        case 0x7ef2: goto pc_7ef2;
        case 0x7ef5: goto pc_7ef5;
        case 0x7ef6: goto pc_7ef6;
        case 0x7ef8: goto loc_79_7ef8;
        case 0x7ef9: goto pc_7ef9;
        case 0x7efb: goto loc_79_7efb;
        case 0x7efc: goto pc_7efc;
        case 0x7efd: goto pc_7efd;
        case 0x7efe: goto pc_7efe;
        case 0x7eff: goto pc_7eff;
        case 0x7f00: goto loc_79_7f00;
        case 0x7f02: goto loc_79_7f02;
        case 0x7f04: goto loc_79_7f04;
        case 0x7f05: goto pc_7f05;
        case 0x7f06: goto pc_7f06;
        case 0x7f07: goto pc_7f07;
        case 0x7f08: goto pc_7f08;
        case 0x7f09: goto pc_7f09;
        case 0x7f0a: goto pc_7f0a;
        case 0x7f0b: goto loc_79_7f0b;
        case 0x7f0c: goto loc_79_7f0c;
        case 0x7f0d: goto loc_79_7f0d;
        case 0x7f0e: goto loc_79_7f0e;
        case 0x7f0f: goto pc_7f0f;
        case 0x7f10: goto loc_79_7f10;
        case 0x7f11: goto loc_79_7f11;
        case 0x7f12: goto pc_7f12;
        case 0x7f13: goto loc_79_7f13;
        case 0x7f14: goto loc_79_7f14;
        case 0x7f15: goto loc_79_7f15;
        case 0x7f16: goto loc_79_7f16;
        case 0x7f18: goto loc_79_7f18;
        case 0x7f19: goto loc_79_7f19;
        case 0x7f1a: goto loc_79_7f1a;
        case 0x7f1b: goto loc_79_7f1b;
        case 0x7f1c: goto pc_7f1c;
        case 0x7f1d: goto pc_7f1d;
        case 0x7f1e: goto loc_79_7f1e;
        case 0x7f1f: goto loc_79_7f1f;
        case 0x7f20: goto loc_79_7f20;
        case 0x7f21: goto loc_79_7f21;
        case 0x7f23: goto loc_79_7f23;
        case 0x7f24: goto pc_7f24;
        case 0x7f25: goto pc_7f25;
        case 0x7f26: goto loc_79_7f26;
        case 0x7f27: goto loc_79_7f27;
        case 0x7f28: goto pc_7f28;
        case 0x7f29: goto pc_7f29;
        case 0x7f2b: goto loc_79_7f2b;
        case 0x7f2c: goto pc_7f2c;
        case 0x7f2d: goto pc_7f2d;
        case 0x7f2e: goto loc_79_7f2e;
        case 0x7f2f: goto loc_79_7f2f;
        case 0x7f32: goto pc_7f32;
        case 0x7f35: goto loc_79_7f35;
        case 0x7f36: goto pc_7f36;
        case 0x7f37: goto pc_7f37;
        case 0x7f38: goto loc_79_7f38;
        case 0x7f39: goto pc_7f39;
        case 0x7f3a: goto pc_7f3a;
        case 0x7f3b: goto pc_7f3b;
        case 0x7f3c: goto pc_7f3c;
        case 0x7f3d: goto pc_7f3d;
        case 0x7f3e: goto pc_7f3e;
        case 0x7f3f: goto loc_79_7f3f;
        case 0x7f40: goto pc_7f40;
        case 0x7f41: goto pc_7f41;
        case 0x7f42: goto pc_7f42;
        case 0x7f43: goto pc_7f43;
        case 0x7f46: goto pc_7f46;
        case 0x7f49: goto pc_7f49;
        case 0x7f4a: goto pc_7f4a;
        case 0x7f4c: goto pc_7f4c;
        case 0x7f4f: goto loc_79_7f4f;
        case 0x7f50: goto pc_7f50;
        case 0x7f51: goto pc_7f51;
        case 0x7f52: goto pc_7f52;
        case 0x7f53: goto pc_7f53;
        case 0x7f56: goto pc_7f56;
        case 0x7f57: goto pc_7f57;
        case 0x7f59: goto pc_7f59;
        case 0x7f5a: goto pc_7f5a;
        case 0x7f5b: goto pc_7f5b;
        case 0x7f5c: goto pc_7f5c;
        case 0x7f5d: goto pc_7f5d;
        case 0x7f5f: goto loc_79_7f5f;
        case 0x7f61: goto loc_79_7f61;
        case 0x7f62: goto pc_7f62;
        case 0x7f63: goto loc_79_7f63;
        case 0x7f64: goto pc_7f64;
        case 0x7f65: goto pc_7f65;
        case 0x7f66: goto pc_7f66;
        case 0x7f67: goto loc_79_7f67;
        case 0x7f68: goto pc_7f68;
        case 0x7f69: goto pc_7f69;
        case 0x7f6a: goto pc_7f6a;
        case 0x7f6c: goto loc_79_7f6c;
        case 0x7f6e: goto loc_79_7f6e;
        case 0x7f71: goto loc_79_7f71;
        case 0x7f73: goto pc_7f73;
        case 0x7f76: goto pc_7f76;
        case 0x7f77: goto pc_7f77;
        case 0x7f79: goto loc_79_7f79;
        case 0x7f7a: goto pc_7f7a;
        case 0x7f7c: goto loc_79_7f7c;
        case 0x7f7f: goto loc_79_7f7f;
        case 0x7f80: goto pc_7f80;
        case 0x7f81: goto pc_7f81;
        case 0x7f82: goto pc_7f82;
        case 0x7f83: goto loc_79_7f83;
        case 0x7f84: goto loc_79_7f84;
        case 0x7f85: goto pc_7f85;
        case 0x7f87: goto loc_79_7f87;
        case 0x7f88: goto pc_7f88;
        case 0x7f89: goto pc_7f89;
        case 0x7f8a: goto pc_7f8a;
        case 0x7f8b: goto pc_7f8b;
        case 0x7f8c: goto pc_7f8c;
        case 0x7f8e: goto loc_79_7f8e;
        case 0x7f8f: goto pc_7f8f;
        case 0x7f90: goto pc_7f90;
        case 0x7f91: goto pc_7f91;
        case 0x7f92: goto pc_7f92;
        case 0x7f93: goto loc_79_7f93;
        case 0x7f94: goto pc_7f94;
        case 0x7f95: goto pc_7f95;
        case 0x7f97: goto pc_7f97;
        case 0x7f9a: goto pc_7f9a;
        case 0x7f9b: goto pc_7f9b;
        case 0x7f9c: goto pc_7f9c;
        case 0x7f9e: goto pc_7f9e;
        case 0x7fa0: goto pc_7fa0;
        case 0x7fa2: goto loc_79_7fa2;
        case 0x7fc9: goto loc_79_7fc9;
        case 0x7fca: goto loc_79_7fca;
        case 0x7fcb: goto loc_79_7fcb;
        case 0x7fcc: goto pc_7fcc;
        case 0x7fcf: goto loc_79_7fcf;
        case 0x7fd0: goto pc_7fd0;
        case 0x7fd1: goto pc_7fd1;
        case 0x7fd2: goto pc_7fd2;
        case 0x7fd3: goto pc_7fd3;
        case 0x7fd4: goto pc_7fd4;
        case 0x7fd5: goto pc_7fd5;
        case 0x7fd6: goto pc_7fd6;
        case 0x7fd8: goto pc_7fd8;
        case 0x7fdb: goto pc_7fdb;
        case 0x7fdc: goto pc_7fdc;
        case 0x7fdd: goto pc_7fdd;
        case 0x7fdf: goto pc_7fdf;
        case 0x7fe0: goto pc_7fe0;
        case 0x7fe2: goto loc_79_7fe2;
        case 0x7fe3: goto pc_7fe3;
        case 0x7fe4: goto pc_7fe4;
        case 0x7fe5: goto loc_79_7fe5;
        case 0x7fe6: goto loc_79_7fe6;
        case 0x7fe7: goto pc_7fe7;
        case 0x7fe8: goto loc_79_7fe8;
        case 0x7fea: goto pc_7fea;
        case 0x7fed: goto pc_7fed;
        case 0x7fee: goto pc_7fee;
        case 0x7fef: goto loc_79_7fef;
        case 0x7ff0: goto pc_7ff0;
        case 0x7ff1: goto pc_7ff1;
        case 0x7ff3: goto pc_7ff3;
        case 0x7ff5: goto pc_7ff5;
        case 0x7ff6: goto pc_7ff6;
        case 0x7ff7: goto pc_7ff7;
        case 0x7ff8: goto pc_7ff8;
        case 0x7ffa: goto pc_7ffa;
        case 0x7ffd: goto pc_7ffd;
        case 0x7ffe: goto pc_7ffe;
        default: break;
    }

loc_79_7e47:
    /* SCF */
    /* 79:7e47 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x7e48;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7e48:
    /* LD BC,$6cce */
    /* 79:7e48 */     ctx->bc = 0x6cce;
    ctx->pc = 0x7e4b;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7e4b:
    /* 79:7e4b */     /* NOP */
    ctx->pc = 0x7e4c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7e4c:
    /* 79:7e4c */     /* NOP */
    ctx->pc = 0x7e4d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_7e4d:
    /* 79:7e4d */     gbrt_timed_rst(ctx, 0x38, 0x7e4e);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7e4e:
    /* SCF */
    /* 79:7e4e */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x7e4f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_7e4f:
    /* 79:7e4f */     ctx->bc = 0x6cce;
    ctx->pc = 0x7e52;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7e52:
    /* 79:7e52 */     /* NOP */
    ctx->pc = 0x7e53;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7e53:
    /* 79:7e53 */     /* NOP */
    ctx->pc = 0x7e54;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7e54:
    /* RST $38 */
    /* 79:7e54 */     gbrt_timed_rst(ctx, 0x38, 0x7e55);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7e55:
    /* SCF */
    /* 79:7e55 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x7e56;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_7e56:
    /* 79:7e56 */     ctx->bc = 0x6cce;
    ctx->pc = 0x7e59;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7e59:
    /* 79:7e59 */     /* NOP */
    ctx->pc = 0x7e5a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7e5a:
    /* 79:7e5a */     /* NOP */
    ctx->pc = 0x7e5b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_7e5b:
    /* 79:7e5b */     gbrt_timed_rst(ctx, 0x38, 0x7e5c);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_79_7e5c; /* fallthrough */
loc_79_7e57:
    /* ADC A,$6c */
    /* 79:7e57 */     gb_adc8(ctx, 0x6c);
    ctx->pc = 0x7e59;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
    /* 79:7e59 */     /* NOP */
    ctx->pc = 0x7e5a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
    /* 79:7e5a */     /* NOP */
    ctx->pc = 0x7e5b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
    /* 79:7e5b */     gbrt_timed_rst(ctx, 0x38, 0x7e5c);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7e5c:
    /* SCF */
    /* 79:7e5c */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x7e5d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$58ce */
pc_7e5d:
    /* 79:7e5d */     ctx->bc = 0x58ce;
    ctx->pc = 0x7e60;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7e60:
    /* 79:7e60 */     /* NOP */
    ctx->pc = 0x7e61;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,$6c */
pc_7e61:
    /* 79:7e61 */     ctx->e = 0x6c;
    ctx->pc = 0x7e63;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7e63:
    /* 79:7e63 */     /* NOP */
    ctx->pc = 0x7e64;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7e64:
    /* 79:7e64 */     /* NOP */
    ctx->pc = 0x7e65;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_7e65:
    /* 79:7e65 */     gbrt_timed_rst(ctx, 0x38, 0x7e66);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_79_7e66; /* fallthrough */
loc_79_7e5f:
    /* LD E,B */
    /* 79:7e5f */     ctx->e = ctx->b;
    ctx->pc = 0x7e60;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
    /* 79:7e60 */     /* NOP */
    ctx->pc = 0x7e61;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,$6c */
    /* 79:7e61 */     ctx->e = 0x6c;
    ctx->pc = 0x7e63;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
    /* 79:7e63 */     /* NOP */
    ctx->pc = 0x7e64;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
    /* 79:7e64 */     /* NOP */
    ctx->pc = 0x7e65;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
    /* 79:7e65 */     gbrt_timed_rst(ctx, 0x38, 0x7e66);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7e66:
    /* SCF */
    /* 79:7e66 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x7e67;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7e67:
    /* LD BC,$6cce */
    /* 79:7e67 */     ctx->bc = 0x6cce;
    ctx->pc = 0x7e6a;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7e6a:
    /* 79:7e6a */     /* NOP */
    ctx->pc = 0x7e6b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_79_7e6b; /* fallthrough */
loc_79_7e68:
    /* ADC A,$6c */
    /* 79:7e68 */     gb_adc8(ctx, 0x6c);
    ctx->pc = 0x7e6a;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
    /* 79:7e6a */     /* NOP */
    ctx->pc = 0x7e6b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7e6b:
    /* NOP */
    /* 79:7e6b */     /* NOP */
    ctx->pc = 0x7e6c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_7e6c:
    /* 79:7e6c */     gbrt_timed_rst(ctx, 0x38, 0x7e6d);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7e6d:
    /* SCF */
    /* 79:7e6d */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x7e6e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_7e6e:
    /* 79:7e6e */     ctx->bc = 0x6cce;
    ctx->pc = 0x7e71;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7e71:
    /* 79:7e71 */     /* NOP */
    ctx->pc = 0x7e72;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7e72:
    /* 79:7e72 */     /* NOP */
    ctx->pc = 0x7e73;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_7e73:
    /* 79:7e73 */     gbrt_timed_rst(ctx, 0x38, 0x7e74);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7e74:
    /* SCF */
    /* 79:7e74 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x7e75;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$76ce */
pc_7e75:
    /* 79:7e75 */     ctx->bc = 0x76ce;
    ctx->pc = 0x7e78;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($033f),SP */
pc_7e78:
    /* 79:7e78 */     gb_write16(ctx, 0x033f, ctx->sp);
    ctx->pc = 0x7e7b;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CCF */
pc_7e7b:
    /* 79:7e7b */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = !ctx->f_c;
    ctx->pc = 0x7e7c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CCF */
pc_7e7c:
    /* 79:7e7c */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = !ctx->f_c;
    ctx->pc = 0x7e7d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CCF */
pc_7e7d:
    /* 79:7e7d */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = !ctx->f_c;
    ctx->pc = 0x7e7e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,E */
pc_7e7e:
    /* 79:7e7e */     ctx->b = ctx->e;
    ctx->pc = 0x7e7f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),D */
pc_7e7f:
    /* 79:7e7f */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x7e80;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RLA */
pc_7e80:
    /* 79:7e80 */     gb_rla(ctx);
    ctx->pc = 0x7e81;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,B */
pc_7e81:
    /* 79:7e81 */     ctx->e = ctx->b;
    ctx->pc = 0x7e82;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
pc_7e82:
    /* 79:7e82 */     ctx->h = ctx->l;
    ctx->pc = 0x7e83;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,H */
pc_7e83:
    /* 79:7e83 */     ctx->h = ctx->h;
    ctx->pc = 0x7e84;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,98 */
pc_7e84:
    /* 79:7e84 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7ee8, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7e86, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7e86:
    /* LD A,C */
    /* 79:7e86 */     ctx->a = ctx->c;
    ctx->pc = 0x7e87;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_7e87:
    /* 79:7e87 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7e88;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CCF */
pc_7e88:
    /* 79:7e88 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = !ctx->f_c;
    ctx->pc = 0x7e89;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_7e89:
    /* 79:7e89 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7e8a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,(HL) */
pc_7e8a:
    /* 79:7e8a */     gb_tick(ctx, 7);
    ctx->c = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x7e8b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,L */
pc_7e8b:
    /* 79:7e8b */     ctx->b = ctx->l;
    ctx->pc = 0x7e8c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,(HL) */
pc_7e8c:
    /* 79:7e8c */     gb_tick(ctx, 7);
    ctx->d = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x7e8d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,L */
pc_7e8d:
    /* 79:7e8d */     ctx->b = ctx->l;
    ctx->pc = 0x7e8e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,D */
pc_7e8e:
    /* 79:7e8e */     ctx->d = ctx->d;
    ctx->pc = 0x7e8f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,H */
pc_7e8f:
    /* 79:7e8f */     ctx->c = ctx->h;
    ctx->pc = 0x7e90;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,C */
pc_7e90:
    /* 79:7e90 */     ctx->b = ctx->c;
    ctx->pc = 0x7e91;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,(HL) */
pc_7e91:
    /* 79:7e91 */     gb_tick(ctx, 7);
    ctx->c = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x7e92;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,H */
pc_7e92:
    /* 79:7e92 */     ctx->b = ctx->h;
    ctx->pc = 0x7e93;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,67 */
pc_7e93:
    /* 79:7e93 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7ed8, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7e95, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_79_7e95; /* fallthrough */
loc_79_7e94:
    /* LD B,E */
    /* 79:7e94 */     ctx->b = ctx->e;
    ctx->pc = 0x7e95;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7e95:
    /* LD C,A */
    /* 79:7e95 */     ctx->c = ctx->a;
    ctx->pc = 0x7e96;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,L */
pc_7e96:
    /* 79:7e96 */     ctx->c = ctx->l;
    ctx->pc = 0x7e97;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_7e97:
    /* 79:7e97 */     ctx->d = ctx->b;
    ctx->pc = 0x7e98;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,C */
pc_7e98:
    /* 79:7e98 */     ctx->b = ctx->c;
    ctx->pc = 0x7e99;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,(HL) */
pc_7e99:
    /* 79:7e99 */     gb_tick(ctx, 7);
    ctx->c = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x7e9a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_7e9a:
    /* 79:7e9a */     ctx->e = ctx->c;
    ctx->pc = 0x7e9b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_7e9b:
    /* 79:7e9b */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7e9c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CCF */
pc_7e9c:
    /* 79:7e9c */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = !ctx->f_c;
    ctx->pc = 0x7e9d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_7e9d:
    /* 79:7e9d */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7e9e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CCF */
pc_7e9e:
    /* 79:7e9e */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = !ctx->f_c;
    ctx->pc = 0x7e9f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_7e9f:
    /* 79:7e9f */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x7ea0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_7ea0:
    /* 79:7ea0 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x7ea1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$8237 */
pc_7ea1:
    /* 79:7ea1 */     ctx->bc = GB_VRAM_BASE + 0x0237;
    ctx->pc = 0x7ea4;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,$37 */
pc_7ea4:
    /* 79:7ea4 */     gb_adc8(ctx, 0x37);
    ctx->pc = 0x7ea6;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC A */
pc_7ea6:
    /* 79:7ea6 */     ctx->a = gb_inc8(ctx, ctx->a);
    ctx->pc = 0x7ea7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,$e8 */
pc_7ea7:
    /* 79:7ea7 */     gb_adc8(ctx, 0xe8);
    ctx->pc = 0x7ea9;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND $16 */
pc_7ea9:
    /* 79:7ea9 */     gb_and8(ctx, 0x16);
    ctx->pc = 0x7eab;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,L */
pc_7eab:
    /* 79:7eab */     ctx->a = ctx->l;
    ctx->pc = 0x7eac;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_7eac:
    /* 79:7eac */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7ead;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_7ead:
    /* 79:7ead */     gbrt_timed_rst(ctx, 0x38, 0x7eae);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7eae:
    /* STOP */
    /* 79:7eae */     ctx->pc = 0x7eb0;
    gb_stop(ctx);
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7eb0:
    /* 79:7eb0 */     /* NOP */
    ctx->pc = 0x7eb1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_7eb1:
    /* 79:7eb1 */     ctx->d = ctx->b;
    ctx->pc = 0x7eb2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,B */
pc_7eb2:
    /* 79:7eb2 */     ctx->c = ctx->b;
    ctx->pc = 0x7eb3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,$00 */
pc_7eb3:
    /* 79:7eb3 */     ctx->c = 0x00;
    ctx->pc = 0x7eb5;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (DE),A */
pc_7eb5:
    /* 79:7eb5 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->de, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7eb6;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7eb6:
    /* 79:7eb6 */     /* NOP */
    ctx->pc = 0x7eb7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC DE */
pc_7eb7:
    /* 79:7eb7 */     gbrt_timed_inc16(ctx, &ctx->de);
    ctx->pc = 0x7eb8;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7eb8:
    /* 79:7eb8 */     /* NOP */
    ctx->pc = 0x7eb9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7eb9:
    /* INC D */
    /* 79:7eb9 */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x7eba;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7eba:
    /* 79:7eba */     /* NOP */
    ctx->pc = 0x7ebb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR 0 */
pc_7ebb:
    /* 79:7ebb */     gbrt_timed_jump(ctx, 0x7ebd, 12); return;
    if (ctx->single_step_mode) return;
loc_79_7ebd:
    /* ADD HL,DE */
    /* 79:7ebd */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x7ebe;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7ebe:
    /* 79:7ebe */     /* NOP */
    ctx->pc = 0x7ebf;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7ebf:
    /* 79:7ebf */     /* NOP */
    ctx->pc = 0x7ec0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(DE) */
pc_7ec0:
    /* 79:7ec0 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->de);
    gb_tick(ctx, 1);
    ctx->pc = 0x7ec1;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7ec1:
    /* NOP */
    /* 79:7ec1 */     /* NOP */
    ctx->pc = 0x7ec2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7ec2:
    /* RST $38 */
    /* 79:7ec2 */     gbrt_timed_rst(ctx, 0x38, 0x7ec3);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7ec3:
    /* RST $38 */
    /* 79:7ec3 */     gbrt_timed_rst(ctx, 0x38, 0x7ec4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7ec4:
    /* RST $38 */
    /* 79:7ec4 */     gbrt_timed_rst(ctx, 0x38, 0x7ec5);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7ec5:
    /* NOP */
    /* 79:7ec5 */     /* NOP */
    ctx->pc = 0x7ec6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,$00 */
pc_7ec6:
    /* 79:7ec6 */     ctx->e = 0x00;
    ctx->pc = 0x7ec8;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_7ec8:
    /* 79:7ec8 */     gbrt_timed_rst(ctx, 0x38, 0x7ec9);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7ec9:
    /* RST $38 */
    /* 79:7ec9 */     gbrt_timed_rst(ctx, 0x38, 0x7eca);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7eca:
    /* RST $38 */
    /* 79:7eca */     gbrt_timed_rst(ctx, 0x38, 0x7ecb);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7ecb:
    /* LD SP,$0000 */
    /* 79:7ecb */     ctx->sp = 0x0000;
    ctx->pc = 0x7ece;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7ece:
    /* 79:7ece */     /* NOP */
    ctx->pc = 0x7ecf;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,DE */
pc_7ecf:
    /* 79:7ecf */     gb_add16(ctx, ctx->de);
    ctx->pc = 0x7ed0;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7ed0:
    /* 79:7ed0 */     /* NOP */
    ctx->pc = 0x7ed1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_7ed1:
    /* 79:7ed1 */     ctx->d = ctx->b;
    ctx->pc = 0x7ed2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,B */
pc_7ed2:
    /* 79:7ed2 */     ctx->c = ctx->b;
    ctx->pc = 0x7ed3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,$00 */
pc_7ed3:
    /* 79:7ed3 */     ctx->c = 0x00;
    ctx->pc = 0x7ed5;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (DE),A */
pc_7ed5:
    /* 79:7ed5 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->de, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7ed6;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7ed6:
    /* 79:7ed6 */     /* NOP */
    ctx->pc = 0x7ed7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC E */
pc_7ed7:
    /* 79:7ed7 */     ctx->e = gb_inc8(ctx, ctx->e);
    ctx->pc = 0x7ed8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7ed8:
    /* NOP */
    /* 79:7ed8 */     /* NOP */
    ctx->pc = 0x7ed9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC E */
pc_7ed9:
    /* 79:7ed9 */     ctx->e = gb_dec8(ctx, ctx->e);
    ctx->pc = 0x7eda;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7eda:
    /* 79:7eda */     /* NOP */
    ctx->pc = 0x7edb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,$00 */
pc_7edb:
    /* 79:7edb */     ctx->e = 0x00;
    ctx->pc = 0x7edd;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRA */
pc_7edd:
    /* 79:7edd */     gb_rra(ctx);
    ctx->pc = 0x7ede;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7ede:
    /* 79:7ede */     /* NOP */
    ctx->pc = 0x7edf;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7edf:
    /* 79:7edf */     /* NOP */
    ctx->pc = 0x7ee0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,0 */
pc_7ee0:
    /* 79:7ee0 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7ee2, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7ee2, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_79_7ee2; /* fallthrough */
loc_79_7ee1:
    /* NOP */
    /* 79:7ee1 */     /* NOP */
    ctx->pc = 0x7ee2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7ee2:
    /* RST $38 */
    /* 79:7ee2 */     gbrt_timed_rst(ctx, 0x38, 0x7ee3);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7ee3:
    /* LD BC,$0021 */
    /* 79:7ee3 */     ctx->bc = 0x0021;
    ctx->pc = 0x7ee6;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_7ee6:
    /* 79:7ee6 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7ee7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRA */
pc_7ee7:
    /* 79:7ee7 */     gb_rra(ctx);
    ctx->pc = 0x7ee8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_79_7ee8; /* fallthrough */
loc_79_7ee4:
    /* LD HL,$0200 */
    /* 79:7ee4 */     ctx->hl = 0x0200;
    ctx->pc = 0x7ee7;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRA */
    /* 79:7ee7 */     gb_rra(ctx);
    ctx->pc = 0x7ee8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7ee8:
    /* INC D */
    /* 79:7ee8 */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x7ee9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_7ee9:
    /* 79:7ee9 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7eea;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB D */
pc_7eea:
    /* 79:7eea */     gb_sub8(ctx, ctx->d);
    ctx->pc = 0x7eeb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR -1 */
pc_7eeb:
    /* 79:7eeb */     gbrt_timed_jump(ctx, 0x7eec, 12); return;
    if (ctx->single_step_mode) return;
loc_79_7eec:
    /* RST $38 */
    /* 79:7eec */     gbrt_timed_rst(ctx, 0x38, 0x7eed);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7eed:
    /* RST $38 */
    /* 79:7eed */     gbrt_timed_rst(ctx, 0x38, 0x7eee);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7eee:
    /* RST $38 */
    /* 79:7eee */     gbrt_timed_rst(ctx, 0x38, 0x7eef);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7eef:
    /* RST $38 */
    /* 79:7eef */     gbrt_timed_rst(ctx, 0x38, 0x7ef0);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7ef0:
    /* RST $38 */
    /* 79:7ef0 */     gbrt_timed_rst(ctx, 0x38, 0x7ef1);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7ef1:
    /* NOP */
    /* 79:7ef1 */     /* NOP */
    ctx->pc = 0x7ef2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($6e4f),SP */
pc_7ef2:
    /* 79:7ef2 */     gb_write16(ctx, 0x6e4f, ctx->sp);
    ctx->pc = 0x7ef5;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
pc_7ef5:
    /* 79:7ef5 */     ctx->h = ctx->l;
    ctx->pc = 0x7ef6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,24 */
pc_7ef6:
    /* 79:7ef6 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7f10, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7ef8, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7ef8:
    /* SUB L */
    /* 79:7ef8 */     gb_sub8(ctx, ctx->l);
    ctx->pc = 0x7ef9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,24 */
pc_7ef9:
    /* 79:7ef9 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7f13, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7efb, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7efb:
    /* INC (HL) */
    /* 79:7efb */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_inc8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x7efc;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC L */
pc_7efc:
    /* 79:7efc */     ctx->l = gb_inc8(ctx, ctx->l);
    ctx->pc = 0x7efd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_7efd:
    /* 79:7efd */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7efe;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,C */
pc_7efe:
    /* 79:7efe */     ctx->l = ctx->c;
    ctx->pc = 0x7eff;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,(HL) */
pc_7eff:
    /* 79:7eff */     gb_tick(ctx, 7);
    ctx->l = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x7f00;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f00:
    /* JR NZ,97 */
    /* 79:7f00 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7f63, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7f02, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f02:
    /* JR NZ,99 */
    /* 79:7f02 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7f67, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7f04, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f04:
    /* LD H,L */
    /* 79:7f04 */     ctx->h = ctx->l;
    ctx->pc = 0x7f05;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),D */
pc_7f05:
    /* 79:7f05 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x7f06;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),H */
pc_7f06:
    /* 79:7f06 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->h);
    gb_tick(ctx, 1);
    ctx->pc = 0x7f07;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,C */
pc_7f07:
    /* 79:7f07 */     ctx->h = ctx->c;
    ctx->pc = 0x7f08;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,C */
pc_7f08:
    /* 79:7f08 */     ctx->l = ctx->c;
    ctx->pc = 0x7f09;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,(HL) */
pc_7f09:
    /* 79:7f09 */     gb_tick(ctx, 7);
    ctx->l = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x7f0a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,20 */
pc_7f0a:
    /* 79:7f0a */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7f20, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7f0c, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_79_7f0c; /* fallthrough */
loc_79_7f0b:
    /* INC D */
    /* 79:7f0b */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x7f0c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f0c:
    /* LD D,A */
    /* 79:7f0c */     ctx->d = ctx->a;
    ctx->pc = 0x7f0d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f0d:
    /* LD L,$04 */
    /* 79:7f0d */     ctx->l = 0x04;
    ctx->pc = 0x7f0f;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$1408 */
pc_7f0f:
    /* 79:7f0f */     ctx->bc = 0x1408;
    ctx->pc = 0x7f12;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,B */
pc_7f12:
    /* 79:7f12 */     ctx->c = ctx->b;
    ctx->pc = 0x7f13;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_79_7f13; /* fallthrough */
loc_79_7f0e:
    /* INC B */
    /* 79:7f0e */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x7f0f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$1408 */
    /* 79:7f0f */     ctx->bc = 0x1408;
    ctx->pc = 0x7f12;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,B */
    /* 79:7f12 */     ctx->c = ctx->b;
    ctx->pc = 0x7f13;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_79_7f13; /* fallthrough */
loc_79_7f10:
    /* LD ($4814),SP */
    /* 79:7f10 */     gb_write16(ctx, 0x4814, ctx->sp);
    ctx->pc = 0x7f13;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_79_7f13; /* fallthrough */
loc_79_7f11:
    /* INC D */
    /* 79:7f11 */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x7f12;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,B */
    /* 79:7f12 */     ctx->c = ctx->b;
    ctx->pc = 0x7f13;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f13:
    /* JR NZ,26 */
    /* 79:7f13 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7f2f, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7f15, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_79_7f15; /* fallthrough */
loc_79_7f14:
    /* LD A,(DE) */
    /* 79:7f14 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->de);
    gb_tick(ctx, 1);
    ctx->pc = 0x7f15;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f15:
    /* DAA */
    /* 79:7f15 */     gb_daa(ctx);
    ctx->pc = 0x7f16;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f16:
    /* JR NZ,22 */
    /* 79:7f16 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7f2e, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7f18, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f18:
    /* LD H,C */
    /* 79:7f18 */     ctx->h = ctx->c;
    ctx->pc = 0x7f19;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f19:
    /* INC L */
    /* 79:7f19 */     ctx->l = gb_inc8(ctx, ctx->l);
    ctx->pc = 0x7f1a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f1a:
    /* INC BC */
    /* 79:7f1a */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7f1b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f1b:
    /* LD L,C */
    /* 79:7f1b */     ctx->l = ctx->c;
    ctx->pc = 0x7f1c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,(HL) */
pc_7f1c:
    /* 79:7f1c */     gb_tick(ctx, 7);
    ctx->l = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x7f1d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-102 */
pc_7f1d:
    /* 79:7f1d */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7eb9, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7f1f, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_79_7f1f; /* fallthrough */
loc_79_7f1e:
    /* SBC A,D */
    /* 79:7f1e */     gb_sbc8(ctx, ctx->d);
    ctx->pc = 0x7f1f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f1f:
    /* LD H,L */
    /* 79:7f1f */     ctx->h = ctx->l;
    ctx->pc = 0x7f20;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f20:
    /* LD (HL),D */
    /* 79:7f20 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x7f21;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f21:
    /* JR NZ,21 */
    /* 79:7f21 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7f38, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7f23, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f23:
    /* LD (HL),A */
    /* 79:7f23 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7f24;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_7f24:
    /* 79:7f24 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7f25;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_7f25:
    /* 79:7f25 */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x7f26;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f26:
    /* RET Z */
    /* 79:7f26 */     if (ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* Z */
    gbrt_timed_jump(ctx, 0x7f27, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f27:
    /* LD H,L */
    /* 79:7f27 */     ctx->h = ctx->l;
    ctx->pc = 0x7f28;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,(HL) */
pc_7f28:
    /* 79:7f28 */     gb_tick(ctx, 7);
    ctx->l = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x7f29;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,20 */
pc_7f29:
    /* 79:7f29 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7f3f, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7f2b, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f2b:
    /* DEC (HL) */
    /* 79:7f2b */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_dec8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x7f2c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_7f2c:
    /* 79:7f2c */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x7f2d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC DE */
pc_7f2d:
    /* 79:7f2d */     gbrt_timed_inc16(ctx, &ctx->de);
    ctx->pc = 0x7f2e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f2e:
    /* INC B */
    /* 79:7f2e */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x7f2f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f2f:
    /* LD BC,$104b */
    /* 79:7f2f */     ctx->bc = 0x104b;
    ctx->pc = 0x7f32;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL NZ,$0d15 */
pc_7f32:
    /* 79:7f32 */     if (!ctx->f_z) {
        gbrt_timed_call(ctx, 0xd15, 0x7f35);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        func_0d15(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7f35, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f35:
    /* LD (BC),A */
    /* 79:7f35 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7f36;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_7f36:
    /* 79:7f36 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x7f37;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,$ce */
pc_7f37:
    /* 79:7f37 */     ctx->e = 0xce;
    ctx->pc = 0x7f39;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CPL */
pc_7f39:
    /* 79:7f39 */     ctx->a = ~ctx->a; ctx->f_n = 1; ctx->f_h = 1;
    ctx->pc = 0x7f3a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7f3a:
    /* 79:7f3a */     /* NOP */
    ctx->pc = 0x7f3b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC D */
pc_7f3b:
    /* 79:7f3b */     ctx->d = gb_dec8(ctx, ctx->d);
    ctx->pc = 0x7f3c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC BC */
pc_7f3c:
    /* 79:7f3c */     gbrt_timed_dec16(ctx, &ctx->bc);
    ctx->pc = 0x7f3d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC L */
pc_7f3d:
    /* 79:7f3d */     ctx->l = gb_dec8(ctx, ctx->l);
    ctx->pc = 0x7f3e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7f3e:
    /* 79:7f3e */     /* NOP */
    ctx->pc = 0x7f3f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_79_7f3f; /* fallthrough */
loc_79_7f38:
    /* ADC A,$2f */
    /* 79:7f38 */     gb_adc8(ctx, 0x2f);
    ctx->pc = 0x7f3a;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
    /* 79:7f3a */     /* NOP */
    ctx->pc = 0x7f3b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC D */
    /* 79:7f3b */     ctx->d = gb_dec8(ctx, ctx->d);
    ctx->pc = 0x7f3c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC BC */
    /* 79:7f3c */     gbrt_timed_dec16(ctx, &ctx->bc);
    ctx->pc = 0x7f3d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC L */
    /* 79:7f3d */     ctx->l = gb_dec8(ctx, ctx->l);
    ctx->pc = 0x7f3e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
    /* 79:7f3e */     /* NOP */
    ctx->pc = 0x7f3f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f3f:
    /* DEC (HL) */
    /* 79:7f3f */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_dec8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x7f40;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7f40:
    /* 79:7f40 */     /* NOP */
    ctx->pc = 0x7f41;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC D */
pc_7f41:
    /* 79:7f41 */     ctx->d = gb_dec8(ctx, ctx->d);
    ctx->pc = 0x7f42;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC C */
pc_7f42:
    /* 79:7f42 */     ctx->c = gb_dec8(ctx, ctx->c);
    ctx->pc = 0x7f43;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0036 */
pc_7f43:
    /* 79:7f43 */     ctx->bc = 0x0036;
    ctx->pc = 0x7f46;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD SP,$0200 */
pc_7f46:
    /* 79:7f46 */     ctx->sp = 0x0200;
    ctx->pc = 0x7f49;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_7f49:
    /* 79:7f49 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x7f4a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,$ce */
pc_7f4a:
    /* 79:7f4a */     ctx->e = 0xce;
    ctx->pc = 0x7f4c;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL $1650 */
pc_7f4c:
    /* 79:7f4c */     gbrt_timed_call(ctx, 0x1650, 0x7f4f);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_1650(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7f4f:
    /* DEC (HL) */
    /* 79:7f4f */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_dec8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x7f50;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_7f50:
    /* 79:7f50 */     ctx->d = ctx->b;
    ctx->pc = 0x7f51;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC D */
pc_7f51:
    /* 79:7f51 */     ctx->d = gb_dec8(ctx, ctx->d);
    ctx->pc = 0x7f52;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC C */
pc_7f52:
    /* 79:7f52 */     ctx->c = gb_inc8(ctx, ctx->c);
    ctx->pc = 0x7f53;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$5036 */
pc_7f53:
    /* 79:7f53 */     ctx->bc = 0x5036;
    ctx->pc = 0x7f56;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_7f56:
    /* 79:7f56 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x7f57;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,$ce */
pc_7f57:
    /* 79:7f57 */     ctx->e = 0xce;
    ctx->pc = 0x7f59;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC DE */
pc_7f59:
    /* 79:7f59 */     gbrt_timed_inc16(ctx, &ctx->de);
    ctx->pc = 0x7f5a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_7f5a:
    /* 79:7f5a */     ctx->d = ctx->b;
    ctx->pc = 0x7f5b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_7f5b:
    /* 79:7f5b */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x7f5c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,H */
pc_7f5c:
    /* 79:7f5c */     ctx->d = ctx->h;
    ctx->pc = 0x7f5d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-111 */
pc_7f5d:
    /* 79:7f5d */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7ef0, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7f5f, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f5f:
    /* JR NZ,105 */
    /* 79:7f5f */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7fca, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7f61, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f61:
    /* LD L,(HL) */
    /* 79:7f61 */     gb_tick(ctx, 7);
    ctx->l = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x7f62;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_7f62:
    /* 79:7f62 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7f63;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f63:
    /* LD H,C */
    /* 79:7f63 */     ctx->h = ctx->c;
    ctx->pc = 0x7f64;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,H */
pc_7f64:
    /* 79:7f64 */     ctx->h = ctx->h;
    ctx->pc = 0x7f65;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* HALT */
pc_7f65:
    /* 79:7f65 */     gbrt_execute_halt(ctx, 0x7f66, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
    /* LD H,C */
pc_7f66:
    /* 79:7f66 */     ctx->h = ctx->c;
    ctx->pc = 0x7f67;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f67:
    /* LD L,(HL) */
    /* 79:7f67 */     gb_tick(ctx, 7);
    ctx->l = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x7f68;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,E */
pc_7f68:
    /* 79:7f68 */     ctx->h = ctx->e;
    ctx->pc = 0x7f69;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
pc_7f69:
    /* 79:7f69 */     ctx->h = ctx->l;
    ctx->pc = 0x7f6a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-91 */
pc_7f6a:
    /* 79:7f6a */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7f11, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        func_79_7f11(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7f6c, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f6c:
    /* JR NZ,21 */
    /* 79:7f6c */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7f83, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7f6e, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f6e:
    /* CALL $ae03 */
    /* 79:7f6e */     gbrt_timed_call(ctx, 0xae03, 0x7f71);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
        return;
    if (ctx->single_step_mode) return;
loc_79_7f71:
    /* LD L,$04 */
    /* 79:7f71 */     ctx->l = 0x04;
    ctx->pc = 0x7f73;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$1408 */
pc_7f73:
    /* 79:7f73 */     ctx->bc = 0x1408;
    ctx->pc = 0x7f76;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,C */
pc_7f76:
    /* 79:7f76 */     gb_adc8(ctx, ctx->c);
    ctx->pc = 0x7f77;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,105 */
pc_7f77:
    /* 79:7f77 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7fe2, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7f79, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f79:
    /* LD L,L */
    /* 79:7f79 */     ctx->l = ctx->l;
    ctx->pc = 0x7f7a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,23 */
pc_7f7a:
    /* 79:7f7a */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7f93, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7f7c, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f7c:
    goto loc_79_7f7c; /* fallthrough */
loc_79_7f7f:
    /* INC BC */
    /* 79:7f7f */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7f80;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,E */
pc_7f80:
    /* 79:7f80 */     gb_sbc8(ctx, ctx->e);
    ctx->pc = 0x7f81;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),E */
pc_7f81:
    /* 79:7f81 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->e);
    gb_tick(ctx, 1);
    ctx->pc = 0x7f82;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,100 */
pc_7f82:
    /* 79:7f82 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7fe8, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7f84, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_79_7f84; /* fallthrough */
loc_79_7f83:
    /* LD H,H */
    /* 79:7f83 */     ctx->h = ctx->h;
    ctx->pc = 0x7f84;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f84:
    /* LD (HL),L */
    /* 79:7f84 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->l);
    gb_tick(ctx, 1);
    ctx->pc = 0x7f85;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-110 */
pc_7f85:
    /* 79:7f85 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7f19, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7f87, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f87:
    /* LD (HL),E */
    /* 79:7f87 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->e);
    gb_tick(ctx, 1);
    ctx->pc = 0x7f88;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
pc_7f88:
    /* 79:7f88 */     ctx->h = ctx->l;
    ctx->pc = 0x7f89;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_7f89:
    /* 79:7f89 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7f8a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RLA */
pc_7f8a:
    /* 79:7f8a */     gb_rla(ctx);
    ctx->pc = 0x7f8b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,E */
pc_7f8b:
    /* 79:7f8b */     ctx->e = ctx->e;
    ctx->pc = 0x7f8c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,20 */
pc_7f8c:
    /* 79:7f8c */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x7fa2, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x7f8e, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f8e:
    /* DEC D */
    /* 79:7f8e */     ctx->d = gb_dec8(ctx, ctx->d);
    ctx->pc = 0x7f8f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,(HL) */
pc_7f8f:
    /* 79:7f8f */     gb_tick(ctx, 7);
    ctx->l = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x7f90;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,C */
pc_7f90:
    /* 79:7f90 */     ctx->l = ctx->c;
    ctx->pc = 0x7f91;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,L */
pc_7f91:
    /* 79:7f91 */     ctx->l = ctx->l;
    ctx->pc = 0x7f92;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,L */
pc_7f92:
    /* 79:7f92 */     ctx->l = ctx->l;
    ctx->pc = 0x7f93;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7f93:
    /* LD (HL),E */
    /* 79:7f93 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->e);
    gb_tick(ctx, 1);
    ctx->pc = 0x7f94;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),H */
pc_7f94:
    /* 79:7f94 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->h);
    gb_tick(ctx, 1);
    ctx->pc = 0x7f95;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,$04 */
pc_7f95:
    /* 79:7f95 */     ctx->l = 0x04;
    ctx->pc = 0x7f97;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0013 */
pc_7f97:
    /* 79:7f97 */     ctx->bc = 0x0013;
    ctx->pc = 0x7f9a;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_7f9a:
    /* 79:7f9a */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x7f9b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,C */
pc_7f9b:
    /* 79:7f9b */     ctx->b = ctx->c;
    ctx->pc = 0x7f9c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,$20 */
pc_7f9c:
    /* 79:7f9c */     ctx->l = 0x20;
    ctx->pc = 0x7f9e;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND $20 */
pc_7f9e:
    /* 79:7f9e */     gb_and8(ctx, 0x20);
    ctx->pc = 0x7fa0;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD SP,3 */
pc_7fa0:
    /* 79:7fa0 */     gbrt_timed_add_sp(ctx, 0x7fa1);
    ctx->pc = 0x7fa2;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7fa2:
    goto loc_79_7fa2; /* fallthrough */
loc_79_7fc9:
    /* LD L,H */
    /* 79:7fc9 */     ctx->l = ctx->h;
    ctx->pc = 0x7fca;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7fca:
    /* LD (HL),D */
    /* 79:7fca */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x7fcb;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7fcb:
    /* LD (HL),L */
    /* 79:7fcb */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->l);
    gb_tick(ctx, 1);
    ctx->pc = 0x7fcc;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP C,$1403 */
pc_7fcc:
    /* 79:7fcc */     if (ctx->f_c) {
        gbrt_timed_jump(ctx, 0x1403, 16);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        func_1403(ctx);
        return;
    } /* C */
    gbrt_timed_jump(ctx, 0x7fcf, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7fcf:
    /* INC (HL) */
    /* 79:7fcf */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_inc8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x7fd0;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,E */
pc_7fd0:
    /* 79:7fd0 */     ctx->l = ctx->e;
    ctx->pc = 0x7fd1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
pc_7fd1:
    /* 79:7fd1 */     ctx->h = ctx->l;
    ctx->pc = 0x7fd2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,B */
pc_7fd2:
    /* 79:7fd2 */     ctx->l = ctx->b;
    ctx->pc = 0x7fd3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),D */
pc_7fd3:
    /* 79:7fd3 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x7fd4;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
pc_7fd4:
    /* 79:7fd4 */     ctx->h = ctx->l;
    ctx->pc = 0x7fd5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,(HL) */
pc_7fd5:
    /* 79:7fd5 */     gb_tick(ctx, 7);
    ctx->l = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x7fd6;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,$04 */
pc_7fd6:
    /* 79:7fd6 */     ctx->l = 0x04;
    ctx->pc = 0x7fd8;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0031 */
pc_7fd8:
    /* 79:7fd8 */     ctx->bc = 0x0031;
    ctx->pc = 0x7fdb;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_7fdb:
    /* 79:7fdb */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7fdc;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_7fdc:
    /* 79:7fdc */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x7fdd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,$ce */
pc_7fdd:
    /* 79:7fdd */     ctx->e = 0xce;
    ctx->pc = 0x7fdf;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,C */
pc_7fdf:
    /* 79:7fdf */     ctx->b = ctx->c;
    ctx->pc = 0x7fe0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* STOP */
pc_7fe0:
    /* 79:7fe0 */     ctx->pc = 0x7fe2;
    gb_stop(ctx);
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
loc_79_7fe2:
    /* LD (BC),A */
    /* 79:7fe2 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7fe3;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC (HL) */
pc_7fe3:
    /* 79:7fe3 */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_dec8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x7fe4;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7fe4:
    /* 79:7fe4 */     /* NOP */
    ctx->pc = 0x7fe5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_79_7fe5:
    /* STOP */
    /* 79:7fe5 */     ctx->pc = 0x7fe7;
    gb_stop(ctx);
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0036 */
pc_7fe7:
    /* 79:7fe7 */     ctx->bc = 0x0036;
    ctx->pc = 0x7fea;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD SP,$0000 */
pc_7fea:
    /* 79:7fea */     ctx->sp = 0x0000;
    ctx->pc = 0x7fed;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,C */
pc_7fed:
    /* 79:7fed */     ctx->b = ctx->c;
    ctx->pc = 0x7fee;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_7fee:
    /* 79:7fee */     gbrt_timed_rst(ctx, 0x38, 0x7fef);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_79_7fef; /* fallthrough */
loc_79_7fe6:
    /* DEC C */
    /* 79:7fe6 */     ctx->c = gb_dec8(ctx, ctx->c);
    ctx->pc = 0x7fe7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0036 */
    /* 79:7fe7 */     ctx->bc = 0x0036;
    ctx->pc = 0x7fea;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD SP,$0000 */
    /* 79:7fea */     ctx->sp = 0x0000;
    ctx->pc = 0x7fed;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,C */
    /* 79:7fed */     ctx->b = ctx->c;
    ctx->pc = 0x7fee;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
    /* 79:7fee */     gbrt_timed_rst(ctx, 0x38, 0x7fef);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_79_7fef; /* fallthrough */
loc_79_7fe8:
    /* LD (HL),$00 */
    /* 79:7fe8 */     gb_tick(ctx, 11);
    gb_write8(ctx, ctx->hl, 0x00);
    gb_tick(ctx, 1);
    ctx->pc = 0x7fea;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD SP,$0000 */
    /* 79:7fea */     ctx->sp = 0x0000;
    ctx->pc = 0x7fed;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,C */
    /* 79:7fed */     ctx->b = ctx->c;
    ctx->pc = 0x7fee;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
    /* 79:7fee */     gbrt_timed_rst(ctx, 0x38, 0x7fef);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_79_7fef:
    /* SCF */
    /* 79:7fef */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x7ff0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(BC) */
pc_7ff0:
    /* 79:7ff0 */     gb_tick(ctx, 7);
    ctx->a = gb_read8(ctx, ctx->bc);
    gb_tick(ctx, 1);
    ctx->pc = 0x7ff1;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,$41 */
pc_7ff1:
    /* 79:7ff1 */     gb_adc8(ctx, 0x41);
    ctx->pc = 0x7ff3;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* STOP */
pc_7ff3:
    /* 79:7ff3 */     ctx->pc = 0x7ff5;
    gb_stop(ctx);
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_7ff5:
    /* 79:7ff5 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x7ff6;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC (HL) */
pc_7ff6:
    /* 79:7ff6 */     {
        const uint16_t gbrt_rmw_addr = ctx->hl;
        uint8_t gbrt_rmw_value = gbrt_timed_bus_read8(ctx, gbrt_rmw_addr, 7);
        gbrt_rmw_value = gb_dec8(ctx, gbrt_rmw_value);
        gbrt_timed_bus_rmw_write8(ctx, gbrt_rmw_addr, gbrt_rmw_value);
    }
    ctx->pc = 0x7ff7;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7ff7:
    /* 79:7ff7 */     /* NOP */
    ctx->pc = 0x7ff8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* STOP */
pc_7ff8:
    /* 79:7ff8 */     ctx->pc = 0x7ffa;
    gb_stop(ctx);
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0036 */
pc_7ffa:
    /* 79:7ffa */     ctx->bc = 0x0036;
    ctx->pc = 0x7ffd;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),B */
pc_7ffd:
    /* 79:7ffd */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->b);
    gb_tick(ctx, 1);
    ctx->pc = 0x7ffe;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($ff09),SP */
pc_7ffe:
    /* 79:7ffe */     gb_write16(ctx, GB_IO_BASE + 0x09, ctx->sp);
    ctx->pc = 0x8001;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x8001 in bank 121 */
    return;
}

void func_79_7e47(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7e48(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7e54(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7e57(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7e5f(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7e67(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7e68(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7e6b(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7e94(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7ec1(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7ec2(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7ec3(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7ec5(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7ee1(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7ee4(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7ef1(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7f00(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7f0b(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7f0d(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7f0e(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7f11(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7f14(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7f16(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7f1a(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7f1b(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7f1e(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7f21(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7f26(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7f7f(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7fc9(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7fcb(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7fe5(GBContext* ctx) {
    body_79_7e47(ctx);
}

void func_79_7fe6(GBContext* ctx) {
    body_79_7e47(ctx);
}

