/* Generated by gbrecomp from Lufia - The Legend Returns (USA) */
#include "Lufia___The_Legend_Returns__USA__internal.h"

/* Shared body at 76:698a */
static void body_76_698a(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x698a: goto loc_76_698a;
        case 0x698b: goto pc_698b;
        case 0x698c: goto pc_698c;
        case 0x698d: goto loc_76_698d;
        case 0x698e: goto pc_698e;
        case 0x698f: goto pc_698f;
        case 0x6992: goto loc_76_6992;
        default: break;
    }

loc_76_698a:
    /* INC BC */
    /* 76:698a */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x698b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC D */
pc_698b:
    /* 76:698b */     ctx->d = gb_dec8(ctx, ctx->d);
    ctx->pc = 0x698c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET NC */
pc_698c:
    /* 76:698c */     if (!ctx->f_c) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NC */
    gbrt_timed_jump(ctx, 0x698d, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_76_698d:
    /* INC D */
    /* 76:698d */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x698e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC DE */
pc_698e:
    /* 76:698e */     gbrt_timed_inc16(ctx, &ctx->de);
    ctx->pc = 0x698f;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP NC,$b920 */
pc_698f:
    /* 76:698f */     if (!ctx->f_c) {
        gbrt_timed_jump(ctx, 0xb920, 16);
        if (gbrt_generated_safepoint(ctx)) return;
        return;
    } /* NC */
    gbrt_timed_jump(ctx, 0x6992, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_76_6992:
    /* INC BC */
    /* 76:6992 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x6993;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x6993 in bank 118 */
    return;
}

void func_76_698a(GBContext* ctx) {
    body_76_698a(ctx);
}

/* Shared body at 76:7990 */
static void body_76_7990(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x7990: goto loc_76_7990;
        case 0x7991: goto pc_7991;
        case 0x7992: goto pc_7992;
        case 0x7993: goto pc_7993;
        case 0x7994: goto loc_76_7994;
        case 0x7995: goto pc_7995;
        case 0x7998: goto pc_7998;
        case 0x7999: goto pc_7999;
        case 0x799a: goto pc_799a;
        case 0x799b: goto pc_799b;
        case 0x799c: goto pc_799c;
        case 0x799f: goto pc_799f;
        case 0x79a0: goto pc_79a0;
        case 0x79a1: goto pc_79a1;
        case 0x79a2: goto pc_79a2;
        case 0x79a4: goto pc_79a4;
        case 0x79a7: goto pc_79a7;
        case 0x79a8: goto pc_79a8;
        case 0x79a9: goto pc_79a9;
        case 0x79aa: goto pc_79aa;
        case 0x79ab: goto pc_79ab;
        case 0x79ae: goto pc_79ae;
        case 0x79af: goto pc_79af;
        case 0x79b0: goto pc_79b0;
        default: break;
    }

loc_76_7990:
    /* LD L,H */
    /* 76:7990 */     ctx->l = ctx->h;
    ctx->pc = 0x7991;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_7991:
    /* 76:7991 */     ctx->e = ctx->c;
    ctx->pc = 0x7992;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7992:
    /* 76:7992 */     /* NOP */
    ctx->pc = 0x7993;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_7993:
    /* 76:7993 */     gbrt_timed_rst(ctx, 0x38, 0x7994);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_76_7994:
    /* SCF */
    /* 76:7994 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x7995;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_7995:
    /* 76:7995 */     ctx->bc = 0x6cce;
    ctx->pc = 0x7998;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7998:
    /* 76:7998 */     /* NOP */
    ctx->pc = 0x7999;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7999:
    /* 76:7999 */     /* NOP */
    ctx->pc = 0x799a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_799a:
    /* 76:799a */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x799b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_799b:
    /* 76:799b */     ctx->l = ctx->h;
    ctx->pc = 0x799c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0300 */
pc_799c:
    /* 76:799c */     ctx->bc = 0x0300;
    ctx->pc = 0x799f;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_799f:
    /* 76:799f */     ctx->l = ctx->h;
    ctx->pc = 0x79a0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_79a0:
    /* 76:79a0 */     ctx->e = ctx->c;
    ctx->pc = 0x79a1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_79a1:
    /* 76:79a1 */     /* NOP */
    ctx->pc = 0x79a2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $37 */
pc_79a2:
    /* 76:79a2 */     gb_cp8(ctx, 0x37);
    ctx->pc = 0x79a4;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_79a4:
    /* 76:79a4 */     ctx->bc = 0x6cce;
    ctx->pc = 0x79a7;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_79a7:
    /* 76:79a7 */     /* NOP */
    ctx->pc = 0x79a8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_79a8:
    /* 76:79a8 */     /* NOP */
    ctx->pc = 0x79a9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_79a9:
    /* 76:79a9 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x79aa;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_79aa:
    /* 76:79aa */     ctx->l = ctx->h;
    ctx->pc = 0x79ab;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0400 */
pc_79ab:
    /* 76:79ab */     ctx->bc = 0x0400;
    ctx->pc = 0x79ae;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_79ae:
    /* 76:79ae */     ctx->l = ctx->h;
    ctx->pc = 0x79af;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_79af:
    /* 76:79af */     ctx->e = ctx->c;
    ctx->pc = 0x79b0;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_79b0:
    /* 76:79b0 */     /* NOP */
    ctx->pc = 0x79b1;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x79b1 in bank 118 */
    return;
}

void func_76_7990(GBContext* ctx) {
    body_76_7990(ctx);
}

/* Shared body at 76:7a25 */
static void body_76_7a25(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x79dd: goto loc_76_79dd;
        case 0x79de: goto pc_79de;
        case 0x79e1: goto pc_79e1;
        case 0x79e2: goto pc_79e2;
        case 0x79e3: goto pc_79e3;
        case 0x79e4: goto pc_79e4;
        case 0x79e5: goto pc_79e5;
        case 0x79e8: goto pc_79e8;
        case 0x79e9: goto pc_79e9;
        case 0x7a25: goto loc_76_7a25;
        case 0x7a27: goto pc_7a27;
        case 0x7a2a: goto pc_7a2a;
        case 0x7a2b: goto pc_7a2b;
        case 0x7a2d: goto pc_7a2d;
        case 0x7a2e: goto pc_7a2e;
        case 0x7a2f: goto pc_7a2f;
        case 0x7a30: goto pc_7a30;
        case 0x7a33: goto loc_76_7a33;
        case 0x7a34: goto pc_7a34;
        case 0x7a35: goto pc_7a35;
        case 0x7a36: goto pc_7a36;
        case 0x7a37: goto pc_7a37;
        case 0x7a38: goto pc_7a38;
        case 0x7a39: goto pc_7a39;
        case 0x7a3a: goto pc_7a3a;
        case 0x7a3b: goto pc_7a3b;
        case 0x7a3c: goto pc_7a3c;
        case 0x7a3d: goto pc_7a3d;
        case 0x7a3e: goto pc_7a3e;
        case 0x7a40: goto pc_7a40;
        case 0x7a43: goto pc_7a43;
        case 0x7a45: goto pc_7a45;
        case 0x7a46: goto pc_7a46;
        case 0x7a47: goto loc_76_7a47;
        case 0x7a48: goto loc_76_7a48;
        case 0x7a49: goto pc_7a49;
        case 0x7a4a: goto pc_7a4a;
        default: break;
    }

loc_76_79dd:
    /* SCF */
    /* 76:79dd */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x79de;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_79de:
    /* 76:79de */     ctx->bc = 0x6cce;
    ctx->pc = 0x79e1;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_79e1:
    /* 76:79e1 */     ctx->e = ctx->c;
    ctx->pc = 0x79e2;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_79e2:
    /* 76:79e2 */     /* NOP */
    ctx->pc = 0x79e3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* PUSH AF */
pc_79e3:
    /* 76:79e3 */     gb_pack_flags(ctx); gbrt_timed_push16(ctx, ctx->af & 0xFFF0);
    ctx->pc = 0x79e4;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_79e4:
    /* 76:79e4 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x79e5;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$6cce */
pc_79e5:
    /* 76:79e5 */     ctx->bc = 0x6cce;
    ctx->pc = 0x79e8;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,C */
pc_79e8:
    /* 76:79e8 */     ctx->e = ctx->c;
    ctx->pc = 0x79e9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_79e9:
    /* 76:79e9 */     /* NOP */
    ctx->pc = 0x79ea;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x79ea in bank 118 */
    return;
loc_76_7a25:
    /* LD L,$04 */
    /* 76:7a25 */     ctx->l = 0x04;
    ctx->pc = 0x7a27;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$1708 */
pc_7a27:
    /* 76:7a27 */     ctx->bc = 0x1708;
    ctx->pc = 0x7a2a;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP B */
pc_7a2a:
    /* 76:7a2a */     gb_cp8(ctx, ctx->b);
    ctx->pc = 0x7a2b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,$20 */
pc_7a2b:
    /* 76:7a2b */     ctx->l = 0x20;
    ctx->pc = 0x7a2d;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC D */
pc_7a2d:
    /* 76:7a2d */     ctx->d = gb_dec8(ctx, ctx->d);
    ctx->pc = 0x7a2e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,BC */
pc_7a2e:
    /* 76:7a2e */     gb_add16(ctx, ctx->bc);
    ctx->pc = 0x7a2f;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_7a2f:
    /* 76:7a2f */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7a30;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CALL NC,$9820 */
pc_7a30:
    /* 76:7a30 */     if (!ctx->f_c) {
        gbrt_timed_call(ctx, 0x9820, 0x7a33);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        return;
    } /* NC */
    gbrt_timed_jump(ctx, 0x7a33, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_76_7a33:
    /* LD L,E */
    /* 76:7a33 */     ctx->l = ctx->e;
    ctx->pc = 0x7a34;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC D */
pc_7a34:
    /* 76:7a34 */     ctx->d = gb_dec8(ctx, ctx->d);
    ctx->pc = 0x7a35;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC H */
pc_7a35:
    /* 76:7a35 */     ctx->h = gb_dec8(ctx, ctx->h);
    ctx->pc = 0x7a36;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_7a36:
    /* 76:7a36 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7a37;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,C */
pc_7a37:
    /* 76:7a37 */     ctx->h = ctx->c;
    ctx->pc = 0x7a38;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,L */
pc_7a38:
    /* 76:7a38 */     ctx->l = ctx->l;
    ctx->pc = 0x7a39;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,H */
pc_7a39:
    /* 76:7a39 */     ctx->a = ctx->h;
    ctx->pc = 0x7a3a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),E */
pc_7a3a:
    /* 76:7a3a */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->e);
    gb_tick(ctx, 1);
    ctx->pc = 0x7a3b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,C */
pc_7a3b:
    /* 76:7a3b */     ctx->h = ctx->c;
    ctx->pc = 0x7a3c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,(HL) */
pc_7a3c:
    /* 76:7a3c */     gb_tick(ctx, 7);
    ctx->l = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x7a3d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),H */
pc_7a3d:
    /* 76:7a3d */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->h);
    gb_tick(ctx, 1);
    ctx->pc = 0x7a3e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,$04 */
pc_7a3e:
    /* 76:7a3e */     ctx->l = 0x04;
    ctx->pc = 0x7a40;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$0137 */
pc_7a40:
    /* 76:7a40 */     ctx->bc = 0x0137;
    ctx->pc = 0x7a43;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,$71 */
pc_7a43:
    /* 76:7a43 */     gb_adc8(ctx, 0x71);
    ctx->pc = 0x7a45;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),D */
pc_7a45:
    /* 76:7a45 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x7a46;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC DE */
pc_7a46:
    /* 76:7a46 */     gbrt_timed_inc16(ctx, &ctx->de);
    ctx->pc = 0x7a47;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_76_7a47:
    /* LD D,B */
    /* 76:7a47 */     ctx->d = ctx->b;
    ctx->pc = 0x7a48;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_76_7a48:
    /* LD B,C */
    /* 76:7a48 */     ctx->b = ctx->c;
    ctx->pc = 0x7a49;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,L */
pc_7a49:
    /* 76:7a49 */     ctx->l = ctx->l;
    ctx->pc = 0x7a4a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR -111 */
pc_7a4a:
    /* 76:7a4a */     gbrt_timed_jump(ctx, 0x79dd, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_76_79dd;
    if (ctx->single_step_mode) return;
}

void func_76_7a25(GBContext* ctx) {
    body_76_7a25(ctx);
}

void func_76_7a47(GBContext* ctx) {
    body_76_7a25(ctx);
}

void func_76_7a48(GBContext* ctx) {
    body_76_7a25(ctx);
}

