/* Generated by gbrecomp from Lufia - The Legend Returns (USA) */
#include "Lufia___The_Legend_Returns__USA__internal.h"

/* Shared body at 70:4452 */
static void body_70_4452(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_70_4452:
    /* JP $1420 */
    /* 70:4452 */     gbrt_timed_jump(ctx, 0x1420, 16);
    if (ctx->single_step_mode) return;
    func_1420(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_70_4452(GBContext* ctx) {
    body_70_4452(ctx);
}

/* Shared body at 70:4622 */
static void body_70_4622(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4622: goto loc_70_4622;
        case 0x4623: goto loc_70_4623;
        case 0x4624: goto pc_4624;
        case 0x4625: goto pc_4625;
        case 0x4626: goto pc_4626;
        case 0x4627: goto pc_4627;
        default: break;
    }

loc_70_4622:
    /* RST $08 */
    /* 70:4622 */     gbrt_timed_rst(ctx, 0x8, 0x4623);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_08(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_70_4623:
    /* NOP */
    /* 70:4623 */     /* NOP */
    ctx->pc = 0x4624;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC DE */
pc_4624:
    /* 70:4624 */     gbrt_timed_inc16(ctx, &ctx->de);
    ctx->pc = 0x4625;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (BC),A */
pc_4625:
    /* 70:4625 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->bc, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x4626;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,L */
pc_4626:
    /* 70:4626 */     ctx->d = ctx->l;
    ctx->pc = 0x4627;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,(HL) */
pc_4627:
    /* 70:4627 */     gb_tick(ctx, 7);
    ctx->l = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4628;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x4628 in bank 112 */
    return;
}

void func_70_4622(GBContext* ctx) {
    body_70_4622(ctx);
}

/* Shared body at 70:47cc */
static void body_70_47cc(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_70_47cc:
    /* JP HL */
    /* 70:47cc */     gbrt_timed_jump(ctx, ctx->hl, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
}

void func_70_47cc(GBContext* ctx) {
    body_70_47cc(ctx);
}

/* Shared body at 70:5ff5 */
static void body_70_5ff5(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x5ff5: goto loc_70_5ff5;
        case 0x5ff8: goto pc_5ff8;
        case 0x5ff9: goto pc_5ff9;
        case 0x5ffa: goto loc_70_5ffa;
        default: break;
    }

loc_70_5ff5:
    /* LD HL,$002f */
    /* 70:5ff5 */     ctx->hl = 0x002f;
    ctx->pc = 0x5ff8;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC D */
pc_5ff8:
    /* 70:5ff8 */     ctx->d = gb_dec8(ctx, ctx->d);
    ctx->pc = 0x5ff9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC HL */
pc_5ff9:
    /* 70:5ff9 */     gbrt_timed_dec16(ctx, &ctx->hl);
    ctx->pc = 0x5ffa;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_70_5ffa:
    /* RET */
    /* 70:5ffa */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_70_5ff5(GBContext* ctx) {
    body_70_5ff5(ctx);
}

void func_70_5ffa(GBContext* ctx) {
    body_70_5ff5(ctx);
}

/* Shared body at 70:6f6f */
static void body_70_6f6f(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_70_6f6f:
    /* JP $9220 */
    /* 70:6f6f */     gbrt_timed_jump(ctx, 0x9220, 16); return;
    if (ctx->single_step_mode) return;
}

void func_70_6f6f(GBContext* ctx) {
    body_70_6f6f(ctx);
}

/* Shared body at 70:73ba */
static void body_70_73ba(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x73ba: goto loc_70_73ba;
        case 0x73bb: goto pc_73bb;
        default: break;
    }

loc_70_73ba:
    /* INC BC */
    /* 70:73ba */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x73bb;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RETI */
pc_73bb:
    /* 70:73bb */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* fallthrough to function */
    func_70_73bc(ctx);
    return;
}

void func_70_73ba(GBContext* ctx) {
    body_70_73ba(ctx);
}

/* Shared body at 70:7ec2 */
static void body_70_7ec2(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_70_7ec2:
    /* JP $a720 */
    /* 70:7ec2 */     gbrt_timed_jump(ctx, 0xa720, 16); return;
    if (ctx->single_step_mode) return;
}

void func_70_7ec2(GBContext* ctx) {
    body_70_7ec2(ctx);
}

