/* Generated by gbrecomp from Lufia - The Legend Returns (USA) */
#include "Lufia___The_Legend_Returns__USA__internal.h"

/* Shared body at 0f:401c */
static void body_0f_401c(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x401c: goto loc_0f_401c;
        case 0x401d: goto pc_401d;
        case 0x401e: goto pc_401e;
        case 0x401f: goto pc_401f;
        case 0x4020: goto pc_4020;
        case 0x4021: goto loc_0f_4021;
        case 0x4022: goto loc_0f_4022;
        case 0x4023: goto pc_4023;
        case 0x4024: goto pc_4024;
        case 0x4026: goto pc_4026;
        case 0x4027: goto pc_4027;
        case 0x4028: goto pc_4028;
        case 0x4029: goto pc_4029;
        case 0x402c: goto pc_402c;
        default: break;
    }

loc_0f_401c:
    /* LD E,B */
    /* 0f:401c */     ctx->e = ctx->b;
    ctx->pc = 0x401d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_401d:
    /* 0f:401d */     gb_rrca(ctx);
    ctx->pc = 0x401e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,B */
pc_401e:
    /* 0f:401e */     gb_adc8(ctx, ctx->b);
    ctx->pc = 0x401f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,E */
pc_401f:
    /* 0f:401f */     ctx->e = ctx->e;
    ctx->pc = 0x4020;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_4020:
    /* 0f:4020 */     gb_rrca(ctx);
    ctx->pc = 0x4021;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_0f_4021:
    /* RST $08 */
    /* 0f:4021 */     gbrt_timed_rst(ctx, 0x8, 0x4022);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_08(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_0f_4022:
    /* LD E,(HL) */
    /* 0f:4022 */     gb_tick(ctx, 7);
    ctx->e = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4023;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_4023:
    /* 0f:4023 */     gb_rrca(ctx);
    ctx->pc = 0x4024;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,$00 */
pc_4024:
    /* 0f:4024 */     ctx->b = 0x00;
    ctx->pc = 0x4026;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SCF */
pc_4026:
    /* 0f:4026 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = 1;
    ctx->pc = 0x4027;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4027:
    /* 0f:4027 */     /* NOP */
    ctx->pc = 0x4028;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,L */
pc_4028:
    /* 0f:4028 */     gb_add8(ctx, ctx->l);
    ctx->pc = 0x4029;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$c606 */
pc_4029:
    /* 0f:4029 */     ctx->bc = GB_WRAM0_BASE + 0x0606;
    ctx->pc = 0x402c;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC E */
pc_402c:
    /* 0f:402c */     ctx->e = gb_inc8(ctx, ctx->e);
    ctx->pc = 0x402d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x402d in bank 15 */
    return;
}

void func_0f_401c(GBContext* ctx) {
    body_0f_401c(ctx);
}

void func_0f_4021(GBContext* ctx) {
    body_0f_401c(ctx);
}

