/* Generated by gbrecomp from Lufia - The Legend Returns (USA) */
#include "Lufia___The_Legend_Returns__USA__internal.h"

/* Shared body at 6d:512f */
static void body_6d_512f(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_6d_512f:
    /* RETI */
    /* 6d:512f */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x5130 in bank 109 */
    return;
}

void func_6d_512f(GBContext* ctx) {
    body_6d_512f(ctx);
}

/* Shared body at 6d:6220 */
static void body_6d_6220(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_6d_6220:
    /* RET */
    /* 6d:6220 */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_6d_6220(GBContext* ctx) {
    body_6d_6220(ctx);
}

