/* Generated by gbrecomp from Lufia - The Legend Returns (USA) */
#include "Lufia___The_Legend_Returns__USA__internal.h"

/* Shared body at 73:4e2b */
static void body_73_4e2b(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_73_4e2b:
    /* RETI */
    /* 73:4e2b */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x4e2c in bank 115 */
    return;
}

void func_73_4e2b(GBContext* ctx) {
    body_73_4e2b(ctx);
}

/* Shared body at 73:69c4 */
static void body_73_69c4(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_73_69c4:
    /* JP $1520 */
    /* 73:69c4 */     gbrt_timed_jump(ctx, 0x1520, 16);
    if (ctx->single_step_mode) return;
    func_1520(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_73_69c4(GBContext* ctx) {
    body_73_69c4(ctx);
}

