/* Generated by gbrecomp from Lufia - The Legend Returns (USA) */
#include "Lufia___The_Legend_Returns__USA__internal.h"

/* Shared body at 66:407c */
static void body_66_407c(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x407c: goto loc_66_407c;
        case 0x407e: goto pc_407e;
        case 0x407f: goto pc_407f;
        case 0x4082: goto pc_4082;
        case 0x4083: goto pc_4083;
        case 0x4086: goto pc_4086;
        case 0x4087: goto pc_4087;
        case 0x408a: goto pc_408a;
        case 0x408b: goto pc_408b;
        case 0x408c: goto pc_408c;
        case 0x408d: goto pc_408d;
        case 0x408e: goto pc_408e;
        case 0x408f: goto pc_408f;
        case 0x4092: goto pc_4092;
        case 0x4093: goto pc_4093;
        case 0x4094: goto pc_4094;
        case 0x4095: goto pc_4095;
        case 0x4096: goto pc_4096;
        case 0x4097: goto pc_4097;
        case 0x409a: goto pc_409a;
        case 0x409b: goto pc_409b;
        case 0x409c: goto pc_409c;
        case 0x409d: goto pc_409d;
        case 0x409e: goto pc_409e;
        case 0x409f: goto pc_409f;
        case 0x40a2: goto pc_40a2;
        case 0x40a3: goto pc_40a3;
        default: break;
    }

loc_66_407c:
    /* LD C,$00 */
    /* 66:407c */     ctx->c = 0x00;
    ctx->pc = 0x407e;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,D */
pc_407e:
    /* 66:407e */     gb_adc8(ctx, ctx->d);
    ctx->pc = 0x407f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($244b),SP */
pc_407f:
    /* 66:407f */     gb_write16(ctx, 0x244b, ctx->sp);
    ctx->pc = 0x4082;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_4082:
    /* 66:4082 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4083;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,($000e) */
pc_4083:
    /* 66:4083 */     gb_tick(ctx, 15);
    ctx->a = gb_read8(ctx, 0x000e);
    gb_tick(ctx, 1);
    ctx->pc = 0x4086;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB B */
pc_4086:
    /* 66:4086 */     gb_sub8(ctx, ctx->b);
    ctx->pc = 0x4087;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($311a),SP */
pc_4087:
    /* 66:4087 */     gb_write16(ctx, 0x311a, ctx->sp);
    ctx->pc = 0x408a;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_408a:
    /* 66:408a */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x408b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,B */
pc_408b:
    /* 66:408b */     ctx->c = ctx->b;
    ctx->pc = 0x408c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_408c:
    /* 66:408c */     gb_rrca(ctx);
    ctx->pc = 0x408d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_408d:
    /* 66:408d */     /* NOP */
    ctx->pc = 0x408e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB (HL) */
pc_408e:
    /* 66:408e */     gb_tick(ctx, 7);
    gb_sub8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x408f;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($3e47),SP */
pc_408f:
    /* 66:408f */     gb_write16(ctx, 0x3e47, ctx->sp);
    ctx->pc = 0x4092;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_4092:
    /* 66:4092 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4093;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,A */
pc_4093:
    /* 66:4093 */     gb_adc8(ctx, ctx->a);
    ctx->pc = 0x4094;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_4094:
    /* 66:4094 */     gb_rrca(ctx);
    ctx->pc = 0x4095;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4095:
    /* 66:4095 */     /* NOP */
    ctx->pc = 0x4096;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,H */
pc_4096:
    /* 66:4096 */     gb_sbc8(ctx, ctx->h);
    ctx->pc = 0x4097;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($03a6),SP */
pc_4097:
    /* 66:4097 */     gb_write16(ctx, 0x03a6, ctx->sp);
    ctx->pc = 0x409a;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_409a:
    /* 66:409a */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x409b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND H */
pc_409b:
    /* 66:409b */     gb_and8(ctx, ctx->h);
    ctx->pc = 0x409c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_409c:
    /* 66:409c */     gb_rrca(ctx);
    ctx->pc = 0x409d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_409d:
    /* 66:409d */     /* NOP */
    ctx->pc = 0x409e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* XOR B */
pc_409e:
    /* 66:409e */     gb_xor8(ctx, ctx->b);
    ctx->pc = 0x409f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($083f),SP */
pc_409f:
    /* 66:409f */     gb_write16(ctx, 0x083f, ctx->sp);
    ctx->pc = 0x40a2;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_40a2:
    /* 66:40a2 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x40a3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET */
pc_40a3:
    /* 66:40a3 */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_66_407c(GBContext* ctx) {
    body_66_407c(ctx);
}

/* Shared body at 66:407d */
static void body_66_407d(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x407d: goto loc_66_407d;
        case 0x407e: goto pc_407e;
        case 0x407f: goto pc_407f;
        case 0x4082: goto pc_4082;
        case 0x4083: goto pc_4083;
        case 0x4086: goto pc_4086;
        case 0x4087: goto pc_4087;
        case 0x408a: goto pc_408a;
        case 0x408b: goto pc_408b;
        case 0x408c: goto pc_408c;
        case 0x408d: goto pc_408d;
        case 0x408e: goto pc_408e;
        case 0x408f: goto pc_408f;
        case 0x4092: goto pc_4092;
        case 0x4093: goto pc_4093;
        case 0x4094: goto pc_4094;
        case 0x4095: goto pc_4095;
        case 0x4096: goto pc_4096;
        case 0x4097: goto pc_4097;
        case 0x409a: goto pc_409a;
        case 0x409b: goto pc_409b;
        case 0x409c: goto pc_409c;
        case 0x409d: goto pc_409d;
        case 0x409e: goto pc_409e;
        case 0x409f: goto pc_409f;
        case 0x40a2: goto pc_40a2;
        case 0x40a3: goto pc_40a3;
        default: break;
    }

loc_66_407d:
    /* NOP */
    /* 66:407d */     /* NOP */
    ctx->pc = 0x407e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,D */
pc_407e:
    /* 66:407e */     gb_adc8(ctx, ctx->d);
    ctx->pc = 0x407f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($244b),SP */
pc_407f:
    /* 66:407f */     gb_write16(ctx, 0x244b, ctx->sp);
    ctx->pc = 0x4082;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_4082:
    /* 66:4082 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4083;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,($000e) */
pc_4083:
    /* 66:4083 */     gb_tick(ctx, 15);
    ctx->a = gb_read8(ctx, 0x000e);
    gb_tick(ctx, 1);
    ctx->pc = 0x4086;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB B */
pc_4086:
    /* 66:4086 */     gb_sub8(ctx, ctx->b);
    ctx->pc = 0x4087;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($311a),SP */
pc_4087:
    /* 66:4087 */     gb_write16(ctx, 0x311a, ctx->sp);
    ctx->pc = 0x408a;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_408a:
    /* 66:408a */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x408b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,B */
pc_408b:
    /* 66:408b */     ctx->c = ctx->b;
    ctx->pc = 0x408c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_408c:
    /* 66:408c */     gb_rrca(ctx);
    ctx->pc = 0x408d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_408d:
    /* 66:408d */     /* NOP */
    ctx->pc = 0x408e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB (HL) */
pc_408e:
    /* 66:408e */     gb_tick(ctx, 7);
    gb_sub8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x408f;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($3e47),SP */
pc_408f:
    /* 66:408f */     gb_write16(ctx, 0x3e47, ctx->sp);
    ctx->pc = 0x4092;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_4092:
    /* 66:4092 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x4093;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADC A,A */
pc_4093:
    /* 66:4093 */     gb_adc8(ctx, ctx->a);
    ctx->pc = 0x4094;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_4094:
    /* 66:4094 */     gb_rrca(ctx);
    ctx->pc = 0x4095;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_4095:
    /* 66:4095 */     /* NOP */
    ctx->pc = 0x4096;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,H */
pc_4096:
    /* 66:4096 */     gb_sbc8(ctx, ctx->h);
    ctx->pc = 0x4097;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($03a6),SP */
pc_4097:
    /* 66:4097 */     gb_write16(ctx, 0x03a6, ctx->sp);
    ctx->pc = 0x409a;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_409a:
    /* 66:409a */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x409b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND H */
pc_409b:
    /* 66:409b */     gb_and8(ctx, ctx->h);
    ctx->pc = 0x409c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_409c:
    /* 66:409c */     gb_rrca(ctx);
    ctx->pc = 0x409d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_409d:
    /* 66:409d */     /* NOP */
    ctx->pc = 0x409e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* XOR B */
pc_409e:
    /* 66:409e */     gb_xor8(ctx, ctx->b);
    ctx->pc = 0x409f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD ($083f),SP */
pc_409f:
    /* 66:409f */     gb_write16(ctx, 0x083f, ctx->sp);
    ctx->pc = 0x40a2;
    gb_tick(ctx, 20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC B */
pc_40a2:
    /* 66:40a2 */     ctx->b = gb_inc8(ctx, ctx->b);
    ctx->pc = 0x40a3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET */
pc_40a3:
    /* 66:40a3 */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_66_407d(GBContext* ctx) {
    body_66_407d(ctx);
}

