/* Generated by gbrecomp from Lufia - The Legend Returns (USA) */
#include "Lufia___The_Legend_Returns__USA__internal.h"

/* Shared body at 78:4146 */
static void body_78_4146(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_78_4146:
    /* RETI */
    /* 78:4146 */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x4147 in bank 120 */
    return;
}

void func_78_4146(GBContext* ctx) {
    body_78_4146(ctx);
}

/* Shared body at 78:6014 */
static void body_78_6014(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_78_6014:
    /* RET */
    /* 78:6014 */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_78_6014(GBContext* ctx) {
    body_78_6014(ctx);
}

/* Shared body at 78:74dc */
static void body_78_74dc(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_78_74dc:
    /* RET */
    /* 78:74dc */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_78_74dc(GBContext* ctx) {
    body_78_74dc(ctx);
}

/* Shared body at 78:7afa */
static void body_78_7afa(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
loc_78_7afa:
    /* RET */
    /* 78:7afa */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_78_7afa(GBContext* ctx) {
    body_78_7afa(ctx);
}

/* Shared body at 78:7b4c */
static void body_78_7b4c(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x7b4c: goto loc_78_7b4c;
        case 0x7b4d: goto pc_7b4d;
        case 0x7b4e: goto pc_7b4e;
        case 0x7b4f: goto pc_7b4f;
        default: break;
    }

loc_78_7b4c:
    /* LD H,C */
    /* 78:7b4c */     ctx->h = ctx->c;
    ctx->pc = 0x7b4d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC BC */
pc_7b4d:
    /* 78:7b4d */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x7b4e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC D */
pc_7b4e:
    /* 78:7b4e */     ctx->d = gb_inc8(ctx, ctx->d);
    ctx->pc = 0x7b4f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JP $0327 */
pc_7b4f:
    /* 78:7b4f */     gbrt_timed_jump(ctx, 0x327, 16);
    if (ctx->single_step_mode) return;
    func_0327(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_78_7b4c(GBContext* ctx) {
    body_78_7b4c(ctx);
}

