/* Generated by gbrecomp from Lufia - The Legend Returns (USA) */
#include "Lufia___The_Legend_Returns__USA__internal.h"

/* Shared body at 6f:7f1a */
static void body_6f_7f1a(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x7f1a: goto loc_6f_7f1a;
        case 0x7f1b: goto loc_6f_7f1b;
        case 0x7f1c: goto pc_7f1c;
        default: break;
    }

loc_6f_7f1a:
    /* RST $38 */
    /* 6f:7f1a */     gbrt_timed_rst(ctx, 0x38, 0x7f1b);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_6f_7f1b:
    /* LD D,D */
    /* 6f:7f1b */     ctx->d = ctx->d;
    ctx->pc = 0x7f1c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_7f1c:
    /* 6f:7f1c */     /* NOP */
    ctx->pc = 0x7f1d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x7f1d in bank 111 */
    return;
}

void func_6f_7f1a(GBContext* ctx) {
    body_6f_7f1a(ctx);
}

